### ISSUE TITLE
7.1.X Sürümleri için durum

### ISSUE THREAD

**Issue by raoc999** [ingbrzy/MA-XML-8.0-TURKISH#100]
Arkadaşlar 7.1.X sürümleri için sorunları ve önerisi olanlar bu başlık altında Model ile birlikte içeriği yazsınlar. Özellikle Mi5 ürünleriyle ilgili şikayetler çok geliyor. Bazı yerle Çince diye. Ürünü bilmiyorum ama kaynak dosyalarında Çince yerler var , kabul ama Çinceden Türkçeye ancak Google yardımıyla çeviri yapılır. O da bazen hatalı olabilir. Ama genel olarak farklı hatalar var 4G gibi, anladığım kadarıyla resmi ROM olmadığından buradakiler bir şekilde ROM yapıyorlar ama tam verimli olmuyor.  Bir ara yeniden tüm modelleri ana dosyalarla karşılaştıracağım. Çünkü bende Note 2 ve Note 4 var birinde TR olan yer diğerinde İng. ama satır çevrilmiş.???! Neden nasıl bilemiyorum.

**Comment by raoc999** [comment]
7.1.16 ve 7.1.17 sürümlerinin içerikleri eklendi.

**Comment by raoc999** [comment]
7.1.19'da %20 altındayken ekrandan görüntü gidiyor, Note 4 için, başka kimsede oldu mu

**Comment by heyelan96** [comment]
Hafiften kararıyo geri aydınlanıyo%20 nin altında.redmi pro

**Comment by CenkayKESER** [comment]
Türkçe'de xposed kulunca tüm uygulamalar FC veriyor. Bu duruma da el atmak lazım.

**Comment by cenedi** [comment]
Mi5s'de böyle çince yazılar var. Sürüm 7,2,9
Ayarlar>Ek Ayarlar >Erişebilirlik>Güvenlik. Bu kısımda çıkıyor hocam bu yazılar.
Saygılar

![screenshot_2017-02-11-03-41-38-152_com android settings](https://cloud.githubusercontent.com/assets/25011005/22856317/b1f4125e-f097-11e6-8d71-518227a75580.png)

**Comment by raoc999** [comment]
Çince yerlerin İngilizcesi olmadığından Türkçe’ye çevirmedim. Bu ürünlerin global satışı daha başlamadı, adamlarda Çince üzerinden devam ediyorlar. Eğer İngilizceye çevrilirse Türkçeye çeviririm. Gerçi Google yardımıyla Çinceden çeviri yaptığım yerlerde var ama bazen istenilen olmuyor.

**Comment by cenedi** [comment]
Dediğim gibi çok önemli değil zaten. Teşekkürler ederim cvp için. Asıl sorun batarya ömrü. Bu sürümde berbat durumda. Çok şarj gidiyor. Cihaz 7 saat ekran süresinden 4-5 saate düştü. Umarım bir sonraki sürümde düzelir.

**Comment by ertanx** [comment]
Hocam ilgili yerleri ekledim; cihaz kenzo.
![2](https://cloud.githubusercontent.com/assets/18513609/22895976/0fbacece-f227-11e6-8ea5-9d9659ffbf37.png)
![3](https://cloud.githubusercontent.com/assets/18513609/22895977/0fbf1236-f227-11e6-9534-844e89a4b331.png)

**Comment by ertanx** [comment]
![1](https://cloud.githubusercontent.com/assets/18513609/22896128/9897a3ac-f227-11e6-90dc-e5bdc5d71052.png)
