### ISSUE TITLE
Sürüm 7.2.XX için Hatalar, Tavsiyeler

### ISSUE THREAD

**Issue by raoc999** [ingbrzy/MA-XML-8.0-TURKISH#101]
Arkadaşlar, lütfen 7.2.XX sürümlerinde gördüğünüzü hataları, düzeltilmesi veya değişmesi gereken yerleri "Model" adıyla birlikte gönderin. Model adı olmayınca söylenileni bulmam çok güç oluyor. Bazı modellerde aynı içerik farklı string ile ifade edilmiş. Birisi bir problem yazınca, bunda hata yok diyorum sonra başka bir modelde onun farklı şekilde olduğunu görüyorum... Teşekkürler. 7.2.13/14 eklendi.

**Comment by kutlusancak** [comment]
Merhabalar
Bazı 3. parti uygulamaların mesajlaşma kısmında gelen mesajı kopyalamak istediğimde tümünü seç,kopyala pop menüsü aktif olmuyor. Bir diger durum da uygulamaların kendi içinden parmak izi ile giriş aktif olmuyor, mesela telekom online işlemler veya banka uygulamalarında giriş ayarlarında parmak iziyle giriş özelliği var mesela samsunglarda kullanılıyorken bunlarda kullanılamıyor.  Telefonum mi5s fakat bir çok modelde mevcut bu iki durum.
Bu iki durumun bir problemden kaynaklı olduğunu düşünmüyorum mevcut romlarda bu fonksiyonlar olmayabilir, geliştirilirse miui adına biraz daha fonksiyonellik katacaktır.

**Comment by raoc999** [comment]
Doğru, aynı problemden bende müzdaribim, sanki adamlar parmakizi özelliğini sadece kilidi açmak için koymuşlar gibi. Miui arayüzü kopya gibi. eui arayüzü de aynı. geçen gün leetv telefon elime geçti. bizim çeviripte göremediğimiz her şey adamlarda var. geçişler menüler çok güzel hele kamera problemi de yok. iki arayüz arasında hiç fark yok gibi ama eui çok hızlı ve üstelik bolca animasyonlu. sanki her hafta eui'den birşeyler ekliyor gibiler.... gördükten sonra.... hızlı ve gelişmiş olan eui olduğuna göre mui oradan birşeyler alıyor diyebilirim. ne de olsa çok kişi bilmiyor, çin dışına da çıkmamış

**Comment by cantekinerdogan** [comment]
Merhaba,

Galeriden bir duvar kağıdını ana ekran ve kilit ekranına uygulayamıyorum. Hata verip kapanıyor. İndirdiğim duvar kağıdını galeriden kendi kendine sildi hatta. Fotoğraf üzerinden duvar kağıdı yapmayı da, Ayarlardan Duvar Kağıdı menüsüne gelerek de denedim.

Redmi 3 (7.2.23)

**Comment by aykutyenihan** [comment]
xiaomi.u romlarında redmi note 3 pro ve başka modellerde kameradan galeriye geçiş sorunu devam ediyormu? redmi note 3 pro global sürüm yüklü geçişte bir sorun yok mi4c de zaten yoktu?

**Comment by ertanx** [comment]
Cihaz Kenzo, 7.2.24;

![screenshot_2017-02-28-15-13-23-385_com miui home](https://cloud.githubusercontent.com/assets/18513609/23406860/2039a534-fdd2-11e6-8b73-edfeb264a09e.png)
![screenshot_2017-02-28-15-58-21-601_com miui home](https://cloud.githubusercontent.com/assets/18513609/23406862/204bf23e-fdd2-11e6-9df9-7c25fad9d5d9.png)
![screenshot_2017-02-28-15-59-33-848_com miui home](https://cloud.githubusercontent.com/assets/18513609/23406864/204da3e0-fdd2-11e6-978e-c8a3668e04c0.png)
![screenshot_2017-02-28-16-00-26-155_com android deskclock](https://cloud.githubusercontent.com/assets/18513609/23406863/204c7484-fdd2-11e6-88a9-35e584cfc455.png)
![screenshot_2017-02-28-16-03-52-853_com android phone](https://cloud.githubusercontent.com/assets/18513609/23406867/2066eecc-fdd2-11e6-9a2a-537044313ca1.png)
![screenshot_2017-02-28-16-06-03-342_com android calendar](https://cloud.githubusercontent.com/assets/18513609/23406861/204a0aa0-fdd2-11e6-9fae-9d83c2abbff1.png)
![screenshot_2017-02-28-16-06-24-901_com android email](https://cloud.githubusercontent.com/assets/18513609/23406866/205c02be-fdd2-11e6-84dd-3b90a90b877a.png)

**Comment by sonsuz05** [comment]
Hocam. Bu kameradan galeriye geçiş sorunu hâlâ devam ediyor. Model Redmi Note 2 Prime. Bir tavsiyeniz var mı?

**Comment by raoc999** [comment]
Yeni "Ekran Kayıt" yazılımı çevrilip eklendi.

**Comment by sonsuz05** [comment]
Hocam tekrar rahatsız ediyorum. Redmi note 2 7.2.24 sürümüne geçtikten sonra gelen güncellemeleri alamıyorum. Güncellemeyi indiriyor güncelle deyince update zip signature verification failed veya error applying update diye bir hata veriyor. Uygulama paketini indirip kendim recoveryden kurmaya çalıştım olmadı hatta twrpyi yükleyip onunlada denedim yine olmadı. Daha önce güncellemeleri sorunsuz yapıyordu. Yardımcı olabilirmisin. ( Redmi Note 2 )

**Comment by raoc999** [comment]
Telefonu Rootladıysan ve resmi rom dosyasını indirip kuruyarsan mı oluyor yoksa eu romları kurunca mı. Tahminim sen resmi rom dosyasını güncellemeden indiriyorsun. Veya farklı bir modelin yazılımını mı indirdim. TWRP ile kurulum yapacaksan dosyayı seçtikten sonra zip imzalamasını doğrula seçeneğini seçme. Eu romlarda imza doğrulaması farklı olduğundan devam etmiyor olabilir. Bu arada 7.3.2 sürümünü kurabilirsin…

 

TWRP – İmza doğrulaması seçilmeyecek… 

 

Orhan

**Comment by sonsuz05** [comment]
Öncelile cevabınız için teşekkürler. Telefon hiç rootlanmadı. http://en.miui.com/download-274.html bu adresteki romun 7.2.24 versiyonunu full inidirp TWRP ile yükledim. Sonra tekrar stock recovery yükledim. Daha önceleri güncellemeleri rahatlıkla alan telefon artık güncelleme almıyor. Ne kenedi güncelleyicisi ne stock recovery nede twrp ile güncelleme yapamadım. güncellemeleri parça parça denedim yine olmadı. Çözemedim bir türlü.

**Comment by raoc999** [comment]
Bence olaya baştan başla. Telefonu ROOT'la, dosya sistemini düzenle,
indirdiğin rom dosyasını telefona at ve kurulumu yap. Veya TWRP ile
telefonu açıp Wipe Data/Cache yapıp dene, önce yedeklemeyi yap...Başada
dönemiyorum diyorsan önce resmi rom dosyasının Fastboot olanını indir,
Xiaominin rom dosyası yüklem programıyla kur... Akıllı.be
<http://xn--cfa.be> sitesinden adım adım tarifler var. Siteyi inceleyim hem
bilgi hemde gerekli dosyaları bulabilirsin. Birde Note 2 telefonun iki
versiyonu var. Sen mediatek mi qualcomm işlmecili mi kuruyorsun?

recep.ali.orhan.cakmak

8 Mart 2017 08:34 tarihinde sonsuz05 <notifications@github.com> yazdı:
