### ISSUE TITLE
Sürüm: 7.3.2 Hakkında Problemler vb...

### ISSUE THREAD

**Issue by raoc999** [ingbrzy/MA-XML-8.0-TURKISH#102]
Değerli Arkadaşlar;

Tüm modelleri elden geçirdiğimden ve 7.3.1  için çok fazla satır geldiğinden tamamını yetiştiremedim. Şimdi ayarların bir kısmının derleyip ekliyorum. (00.24) Belkide ROM dosyaları derlendi. Velhasıl Tema, Hesap Kaydı, Sarı Sayfalar, Uzaktan Kumanda ve Şebeke ile ilgili bazı yerler İng., ayrıca daha önce bahsedilen yazı ing. yerleri daha eklemedim. Sırayla gidiyorum, hemde yeni eklenen satırları ekliyorum. Eğer aksilik olmazsa haftaiçi eklemeler yapıp, gelecek haftaya daha iyi olacak. Herkese teşekkürler. Yinede gördüğünüz yerleri gönderin lütfen ama model numarası yazmayı unutmayın.
Orhan ÇAKMAK

**Comment by Ceyhun27** [comment]
![screenshot_2017-03-03-19-59-51-444_com android settings](https://cloud.githubusercontent.com/assets/26170423/23561463/6c01eb96-004f-11e7-85a6-4f22bb3007d0.png)
![screenshot_2017-03-03-19-55-06-509_com android phone](https://cloud.githubusercontent.com/assets/26170423/23561505/96181e96-004f-11e7-920e-61f92f578de9.png)
![screenshot_2017-03-03-19-52-16-344_com android settings]
![screenshot_2017-03-03-19-35-28-132_com android settings](https://cloud.githubusercontent.com/assets/26170423/23561554/c08ebc98-004f-11e7-8659-5bd8fa37c63d.png)
![screenshot_2017-03-03-19-32-50-586_com android browser](https://cloud.githubusercontent.com/assets/26170423/23561566/c78b5574-004f-11e7-9176-0be9719d4aeb.png)
![screenshot_2017-03-03-19-32-30-136_lockscreen](https://cloud.githubusercontent.com/assets/26170423/23561583/e49422f4-004f-11e7-96c3-8dd7fe59e48c.png)


(https://cloud.githubusercontent.com/assets/26170423/23561516/9e669028-004f-11e7-9c10-a1f7214354a9.png)
![screenshot_2017-03-03-19-37-01-113_com android thememanager](https://cloud.githubusercontent.com/assets/26170423/23561521/a4f36c4a-004f-11e7-8aa6-f9dd787a1794.png)
![screenshot_2017-03-03-19-36-46-900_com android settings](https://cloud.githubusercontent.com/assets/26170423/23561536/b50c1bcc-004f-11e7-9945-00beaafca511.png)

**Comment by Ceyhun27** [comment]
Global sürümden eu haftalık sürüme geçtim. Be zaman arka planda Google veya miui senkronizasyonu olsa bildirim kısmında simgesi görünüyor. Bu hata mıdır özellik mıdır bilmiyorum. 
Yaptığınız çalışmalar çok güzel. Sistemli ve düzenli. Teşekkürler.

**Comment by sedat27** [comment]
Orhan merhaba.
Epeydir sorun yoktu ama son guncellemeden sonra baya bisey cikti. Yukarida verilmis bende ekleyeyim
![screenshot_2017-03-04-00-33-33-688_com miui gallery](https://cloud.githubusercontent.com/assets/9906622/23569831/75f98848-0072-11e7-8539-0246f9a46e49.png)
 Ayrica bir sorun daha var. Mimixte rehberde yan tarafta bulunan harfler rusça. Alfabe kismi. Ve neye bassan z harfine gidiyor. Tum dillerde boyle. Bunun ne ile ilgisi vardir?

**Comment by raoc999** [comment]
Arkadaşlar bu haftaki güncellemeleri Perşembe akşamı yüklemedim ama çok demek ki çok önceden dosyaları çekiyorlar. Yani yaptığın güncellemeler telefonlara yansımamış. Çok yer çevrilmemiş gözüküyor. Gelecek hafta 7.3.2 için gelen satırlar çevrilmiş olarak gözükecek. Ayrıca tüm modelleri yeniden gözden geçiriyorum. Şimdilik Hermes, Nikel, Kenzo, Cancro ve Aqua üzerinden devam ediyorum. Rom dosyası 4.4 olanlar ile ilgilenmiyorum. Zaten eu 4.4 olan ürünlere artık destek vermiyor.
