### ISSUE TITLE
Sürüm 7.3.9 Hakkında +/-

### ISSUE THREAD

**Issue by raoc999** [ingbrzy/MA-XML-8.0-TURKISH#103]
Arkadaşlar, bir kaç yerde İngilizce kalan kısımlar var onları düzelteceğim, önceden de yazdığım gibi tek tek tüm modelleri derliyorum.

**Comment by aykutyenihan** [comment]
kilit ekranında yukarı kaydır kısmı ve alarm kurma ayarlarında ingilizce kalan yerler ve yanlış ifadeler var gördüğüm kadarıyla
