### ISSUE TITLE
XML issues

### ISSUE THREAD

**Issue by ingbrzy** [ingbrzy/MA-XML-8.0-TURKISH#106]
https://translators.xiaomi.eu/XML_MIUI8-Turkish-tr.html

**Comment by ingbrzy** [comment]
![image](https://cloud.githubusercontent.com/assets/1762519/26276931/33d250e2-3d82-11e7-8446-4a7467b9e46b.png)

**Comment by ingbrzy** [comment]
@raoc999

**Comment by raoc999** [comment]
I fixed. I have a request. Can we sort the lines of all the files? There are also many unnecessary or invalid lines. Can we delete unnecessary and obsolete lines? Thanks by Orhan

**Comment by ingbrzy** [comment]
XML issues again
https://github.com/ingbrzy/MA-XML-8.0-TURKISH

@raoc999

**Comment by raoc999** [comment]
I know and i will fix, thanks
