### ISSUE TITLE
Türkçe dil bugları

### ISSUE THREAD

**Issue by Veysel78** [ingbrzy/MA-XML-8.0-TURKISH#107]
Alarmda, galeride bazı türkçeleşmemiş kelimeler mevcut.

**Comment by Veysel78** [comment]
Mi mix sürüm 8.2.3

**Comment by raoc999** [comment]
Artık aylık güncelleme yapıyorum, çok işim var yetiştiremiyorum ama bir ay sonra işler azalır eklemeleri yaparım. Akşamları boşta kalıyorum ama yorgunluktan oturamıyorum, şimdi de Ramazan geldi, biten dosyaları ekliyorum... Sonra telafi edeceğim....
