### ISSUE TITLE
7.6.15

### ISSUE THREAD

**Issue by burak1987** [ingbrzy/MA-XML-8.0-TURKISH#109]
İyi günler öncelikle çeviri için çok teşekkür ediyorum mi mix kullanıcısıyım .7.6.15 sürümü telefonumda yüklü bazı yerler ingilizce özellikle pil bölümünde ve telefon şarj olurken dolum süresi ile ilgili yerler ingilizce ve gelen cevapsız aramalar ingilizce  sizden ricam düzeltme gibi şansımız varsa düzeltelim...Çok teşekkür ediyorum...

**Comment by raoc999** [comment]
Arkadaşlar gelecek haftadan itibaren güncelleme ye devam edeceğim.

**Comment by burak1987** [comment]
Şimdiden kolay gelsin... Bekliyoruz

**Comment by burak1987** [comment]
![screenshot_2017-06-21-17-39-28-768_com android mms](https://user-images.githubusercontent.com/29512909/27391164-dc5bd430-56ab-11e7-9fa9-dfdbc2c4a738.png)

**Comment by burak1987** [comment]
![screenshot_2017-06-21-17-41-05-424_lockscreen](https://user-images.githubusercontent.com/29512909/27391233-17895276-56ac-11e7-8fde-d03e9646889c.png)

**Comment by burak1987** [comment]
![screenshot_2017-06-21-17-41-14-336_lockscreen](https://user-images.githubusercontent.com/29512909/27391283-36bf44a2-56ac-11e7-92f1-d50ce4284dde.png)

**Comment by burak1987** [comment]
![screenshot_2017-06-21-17-41-23-092_com miui home](https://user-images.githubusercontent.com/29512909/27391316-56ba6d86-56ac-11e7-8667-ab5edf27d56a.png)

**Comment by burak1987** [comment]
![screenshot_2017-06-21-17-42-01-877_com miui powerkeeper](https://user-images.githubusercontent.com/29512909/27391353-7a0ea3ba-56ac-11e7-9a7d-c0f125e539fb.png)

**Comment by burak1987** [comment]
![screenshot_2017-06-21-18-09-02-998_com miui gallery](https://user-images.githubusercontent.com/29512909/27391585-fa7a12c8-56ac-11e7-9857-c748559d958c.png)

**Comment by burak1987** [comment]
Altı Kırmızı çizgi ile çizilen yerler ingilizce inşallah en kısa zamanda düzeltirsiniz teşşekkür ediyorum....

**Comment by raoc999** [comment]
Beyler düzeltmeye başladım fakat alfabetik sıra ile yapıyorum, yeni dosyaları da çevirip ekliyorum. Ama iki üç hafta içinde tam olur. Şimdilik çevirdiklerimi ekliyorum ve şu an resim filan göndermeyin, zaten bende ürünlerde çevrilmemiş yerleri görüyorum... Orhan

**Comment by burak1987** [comment]
Orhan abi kolay gelsin inşallah çevirileri bekliyoruz... Düzenleme bittikten sonra rom dosyasını tekrarmı indirecez.? Nasıl yapıcaz beni bu konuda bilgilendirirsen çok sevinirim....

**Comment by raoc999** [comment]
Değişiklikleri ürün güncellemeleriyle birlikte göreceksiniz. Yani yeni ROM dosyalarına eklenmiş olacaklar. Alt modellerin yazılımı şimdilik çıkmıyor. Ürünler Android 7 sürümüne geçiriliyor. Bu esnada bende günlük çevirileri yapıp, ekliyorum. Gemini (Mi 5) modelini baz alıyorum....

**Comment by burak1987** [comment]
Orhan abi çok teşekkür ediyorum cvplar için.Anladığım Kadarıyla güncellemeler bittiği zaman rom dosyası xaomi eu sitesine eklenecek ve bizde o şekilde indirip kurucaz sıfırdan yani.. güncelleme bitiği zaman bilgilendirirseniz seviniriz.. Çıkan son sürüm 7.6.22 romunu indirecez öyle değilmi abi...Başını ağrıtıyorum kusura bakma konuya yabancıyım...
