### ISSUE TITLE
Türkçe Çeviri Durumu

### ISSUE THREAD

**Issue by raoc999** [ingbrzy/MA-XML-8.0-TURKISH#23]
Arkadaşlar, 29.01.2016 tarihi itibariyle yaptığım çevirileri siteye eklemeye başladım. Bazı dizelerde hata var gibi. Bunların bir kısmı diğer çevirilerde bitince ortaya çıkacak. Mühtelemel yani dosyada bir yer başka bir dosyadan birşey çekiyor ama o olmadığından? Veya bu işi yapanların başka bir bildiği varsa... Çeviri sonunda gerekirse o dizeleri kaldıracağım. Bu arada bundan sonraki çevirilere 6.1.29 üzerinden gideceğim. Hatalı yerleri vb.. lütfen iletin. 
Şu an çevrilen dosya : CMTransfer.apk
Çeviri Dosyası : 6.1.29
recep.ali.orhan

**Comment by sedat27** [comment]
Redmi note 3 kamera galeri hatasi devam ediyor.6.1.29.
İngilizce de sikinti yok

**Comment by raoc999** [comment]
Ama çeviri bitmedi ki, birde github yabancısı olduğumdan bugün sadece hatalrı düzeltmekle geçirdim. Çevirdiğim dosyaların isimlerini yazdım. Kamera dosyasına çok var. Yarın fırsat bulursan önce ona başlayacağım. Bu çeviri zincirleme birbirine bağlı. Belki oraya tıklayınca Ayarlara vb. gidiyorda olabilir. Ama bunu çözeceğiz diye inanıyorum. Yoksa İng ve diğer dillere çevirince neden olmuyor.

**Comment by Tmp341** [comment]
Kameradan galeriye geçiş hatası Türkçe dil ile alakalıydı. İngilizce de öyle bir sorun yoktu. Hala daha çözümü bulunamamış olabilir.

**Comment by raoc999** [comment]
Galeride de sorun olabilir, belki Kamera çekimden sonra galeriye gidiyor ama ilgili yeri bulamıyor. Eski çeviri 778 satır yenisi 1200 satır. Arada uçuk fark var. İki dosya var onları çevirdikten sonra direkt Galeri uygulamasını çevireceğim. KAmerayı çevirip ekledim. Kamera dosyası ise eski çeviriye nazaran satır sayısı azaldı. Ayrıca eski çeviride olmayan yepyeni bir sürü dosya daha var. Dün "Isı Yöneticisi"ni çevirip ekledim. Daha öncede "Pil Yöneticisi"ni eklemiştim. Duruma göre günde 1-2 tane ekliyorum. Daha 70 dizin var.

**Comment by raoc999** [comment]
Kamera ve Galeri çevrildi, hata raporu gelsin düzelteceğim. Aksilik olmazsa bu haftaki sürüme eklerler de bu sorunda çözülmüş olur. E-mail dosyasını çevirmeye başlıyorum. Bu dosyada uzun. Yazı ve ifade eksikliklerini telefonda görüp düzelteceğim. Bazı yerlede çeviriyi yapıyorsun ama ekranda çok alakasız gözüküyor, başka telefonlarla karşılaştırıp daha anlaşılır metne dönüştüreceğim. Mümkün olduğunda kısa ve mantıklı cümleler kurmaya çalışıyorum. "Dosya kopyalama işlemi başarısız" diye olan çeviriyi "Dosya kopyalanamıyor" ....

**Comment by raoc999** [comment]
E-Mail -E-Posta dosyası çevrilip eklendi. File Explorer ve Find Device çevrilip eklenecek. Find Device yeni bir özellik. Çeviride yok. Güncel sürümde olmayanlarda silinecek...

**Comment by sedat27** [comment]
merhaba

ne durumdayız. bu hafta çeviriler eklenmiş olaarak çıkarmı?
kamera ve galeri düzelirse daha bişeye ihtiyaç yok.
Ayrıca yeni uygulamalar veya ayarlar mı ekleniyor?

**Comment by raoc999** [comment]
Biliyorsun Çinde yeni yıl tatilinden dolayı iki haftadır güncelleme yok. Ama bir bakıma iyi oldu bende çeviriyi ne deyse bitirmek üzereyim. 17 klasör kaldı bunlardan Ayarlar olanı çok büyük diğerleri o kadar büyükü değil. Bitirdikçe ekliyorum, Senin gibi bende bekliyorum. Çok hatalı çeviri vardı. Mesela bir yerde Xioamiden başka yerden alırsanız xxx. risk size aittir derken çeviridi Xiaomiden alırsanız sorumluluk size aittir gibi, bazı yerler çok ters... Neyse bakalım bizim çeviri ne olacak, hatalar vb...
