### ISSUE TITLE
Redmi Note 2 V6.2.2 Problemli

### ISSUE THREAD

**Issue by raoc999** [ingbrzy/MA-XML-8.0-TURKISH#24]
Arkadaşlar http://en.miui.com adresteki Redmi Note 2 v6.2.2 sürümü çok problemli: 1: telefon çaldığında gelen arama açılmıyor, Kamera ve Galeri sorunu devam ediyor. ınCallUI dosyasında hata var galiba. Birşey yazarken klavye de takılı kalıyor. Çok detaylı bakmadım. Çeviride 3 arkadşın ismi var. Eğer burayı takip ediyorlarsa düzeltsinler. 6.1.29 sürüme downgrade yaptım.

**Comment by ekilciler** [comment]
Hocam bu sorunlar sadece Türkçe'de mi oldu, diğer dillerde denediniz mi?
Bir de ekran görüntüsü ekleme imkanınız var mı?

**Comment by raoc999** [comment]
Doğrusu diğer dilleri denemedim, InCallUI dosyasını araştırın, hata ordan kaynaklanıyor, kamera ve galeri sorunlu, sorun devam ediyor. Çağrı gelince telefon ekranı açılmıyor, açmak için Power tuşuna basında çağrı arka plana geçiyor, çağrıya döne tıklayınca çalışmıyor. Tam deneyemedim sürekli telefon görüşmesi gelmeye başlayınca bende eski sürüme döndüm. Daha bir kaç şeyde gördüm ama benim çeviri sonraki sürümde sizinki ile karşılaştıracağım. Çevirilerinizde mantık hatası çok. Mesela: "Arama"  demek olumsuz, Ara demek olumlu. Türkçe emir köklü bir dil. Eşleştirme olumsuz, Eşleştir olumlu. Siz Arama derken Aramak fiilini kullanıyorsunuz ama yanlış oluyor. Birde bazı yerlerde adamlar başka şey demek istemişken siz çok ters birşey diyorsunuz. O İng. cümleyi kesip google translate'e atınca sizin dediğiniz cümle çıkıyor, oysa orada farklı şey deniliyor. Mesela: Bundan Xiaomi mesul değil gibi bir yer vardı, siz Xiaomi sorumludur gibi birşey demişsiniz.... 7.1.X sürümünü siz yaptıysanız çok hatalar var. İyi çalışmalar.

**Comment by ekilciler** [comment]
Hocam tavsiyeleriniz için çok teşekkürler. 

Bahsettiğiniz uygulama hatalarını geliştirici ekibe bildiriyorum. En kısa sürede düzeltilecektir.

Arama derken aramak fiilini kullanmıyoruz, aramak filini isim haline getiriyoruz. Fiillerden sonra gelen -ma, -ma ekleri sizin de söylediğiniz gibi mastara olumsuzluk özelliği kazandırabildiği gibi fiillere cümle içerisinde isim görevi de yükleyebilmektedir. Eğer ki gelen -me, -ma eki bahsedilen fiile isim görevi yükleme görevi de görüyor ise isim-fiil olarak adlandırılır. Bizim bahsettiğiniz yerde kullanmış olduğumuz "arama" kelimesi isim-fiildir. Örnek olarak "İlkokulda **okuma**yı öğrenmiştik" cümlesinde de okumak fiiline -ma eki getirilerek isim-fiil olarak kullanılmıştır.

Anlam farklılıkları için ise çeviriyi tekrar kontrol ettim ama maalesef söylediğiniz cümleyi bulamadım. Eğer vaktiniz olur da romu yeniden yüklerseniz, bana tam yerini bildirdiğinizde hemen düzeltebilirim.

**Comment by raoc999** [comment]
Ben zaten sizin çeviriyi esas alarak devam ediyorum. Dünde ayarlarda yanlış bir cümle gördüm. Tam hatırlamadım ama "no longer available" olumsuzken olumlu yazılmıştı. Siz resmi olarak çeviri yapıyorsanız, gördüğüm hataları özel olarak size raporlarım.

**Comment by raoc999** [comment]
Ekilciler... Acaba Galeri ve Kamera dosyalarında "SD Kart" gibi bir çeviri bağlantısı olan Ayarlar vb... başka bir dosyada da aynı şekilde olması gerekirken başka "SD kart" gibi olduğundan mı bu hata hiç düzelmedi. İngilizcede olmuyor. Veya adamlarda almak fiilinin 3-4 şekli varken -receive,take vb, biz herşeye almak diyoruz ordan mı bir terslik oluyor. Bu tamamen Türkçedeki bir hata gibi....

**Comment by raoc999** [comment]
Ayarlarda: Change display settings karşılığı Ekran ölçüsünü değiştir denilmiş?

**Comment by MIUITurkey** [comment]
Hocam bu arada çeviri yapanlarda miuiturkiye.net yazıyordu silmişsiniz?
20 Şub 2016 17:38 tarihinde "recep.ali.orhan.cakmak" <
notifications@github.com> yazdı:

**Comment by raoc999** [comment]
Ekleriz dert değil, ben GitHub'da yeni proje açtım ordan upload yaptığımdan detaylara bakmıyorum.

**Comment by raoc999** [comment]
Ayarlarda: Navigation buttons karşılığı Opsiyonel tuş (yanlış)

**Comment by raoc999** [comment]
Reset to defaults > Varsayılan ayarlara dönülsün mü? (yanlış) soru sormuyor ki

**Comment by raoc999** [comment]
Choose music player > Müzik oynatıcıyı değiştir -yanlış

**Comment by MIUITurkey** [comment]
Eklerseniz sevinirim hocam bir sonra ki güncelleme de, Türkiyede ki tek
platform sonuçta ayrıca forumdan çeviri ekibi desteği bulabilirsiniz.
20 Şub 2016 17:56 tarihinde "recep.ali.orhan.cakmak" <
notifications@github.com> yazdı:

**Comment by raoc999** [comment]
Çeviriyi bitirdim sayılır, büyük 10 dosya kaldı. Şu an Settings çeviriyorum 6.2.18 sürümüne göre, sizin çeviricilerin yaptığı hatalarıda düzeltiyorum. Ama bu kez bende hatalar yapıyorum :) Elden geçirip en iyi hale getireceğim. Sitenizi de eklerim. Yalnız sitenizde günlük haberlere yer verseniz. Pek ilgi çeken birşey yok sitede. Özellikle ROM ve telefonlarla ilgili ince ayarlar vb... Bu ürünlerin çoğu resmi yolla gelmiyor. Alanlar ille bir kaç şey için bir yerlere bakmak istiyor. Ben ilk alınca Akıllı.be gittim. İyi çalışmalar. Çevirileri bittikçe Hub'a atıyorum, oradan takip ve güncelleme yapabilirsiniz.

**Comment by MIUITurkey** [comment]
Hocam imceleme bölümü ve haber bölümümüz mevcut ayrıca ipuçları bölümü
biraz forumda gezmeniz gerekiyor :)

Onun dışında bir çok Xiaomi ürününü resmi şekilde satışını da yapiyoruz.
Akıllı. Be formunda genelde imei vb şeyler için girebilirsiniz bizim
forumda bu maalesef yasak :)
20 Şub 2016 18:17 tarihinde "recep.ali.orhan.cakmak" <
notifications@github.com> yazdı:

**Comment by CenkayKESER** [comment]
Donanım haber üstünde redmi note 3, redmi note 3 pro, redmi 3, mi4 ana konuları bana ait, türkçe miui içeriği üreten sitelere destek vermek istiyorum kendilerine ilgili konularda hit göndermek adına. Zira ana konulardaki link çıkışlarını takip ediyorum gayet tatmin edici düzeydeler.

**Comment by MIUITurkey** [comment]
Cenkay hocam o zaman sitemizi eklemenizi rica edebilirim hatta forum
sitemize üye olarak ana konuları oradan da paylaşabilirsiniz.

**Comment by raoc999** [comment]
Hasan kardeşimin dediğine katılıyorum. Herkes bir platformda bir araya gelse çok iyi olur. Hem faydalı hemde Xiaomi ürün-içerikleri ortalıkta çorba gibi olmaz.

**Comment by MIUITurkey** [comment]
Hocam zaten Türkiye resmi MIUI fan sitesi biziz yanı herkesi elimizden
geldiğince burada toplamaya çalışıyorum
22 Şub 2016 09:27 tarihinde "recep.ali.orhan.cakmak" <
notifications@github.com> yazdı:
