### ISSUE TITLE
6.2.18 Çeviri Hataları

### ISSUE THREAD

**Issue by CenkayKESER** [ingbrzy/MA-XML-8.0-TURKISH#25]
Merhaba,

6.2.16 sürümünün çıkmasını merakla bekliyordum zira 2 haftaya yakın süredir ciddi bir emek harcayarak metinleri çeviriyordunuz. Bu sürümü kurdum ve detaylıca nerelerde hata var belirledim. Bu hatalar şu şekilde;
![1](https://cloud.githubusercontent.com/assets/11776567/13183726/06cf14ac-d741-11e5-805e-a6371aaf9113.png)
![2](https://cloud.githubusercontent.com/assets/11776567/13183727/06cf38f6-d741-11e5-8ef5-583fcacc8831.png)
![3](https://cloud.githubusercontent.com/assets/11776567/13183728/06cf8a86-d741-11e5-8bbd-ac02cf74dadc.png)
![4](https://cloud.githubusercontent.com/assets/11776567/13183730/070849de-d741-11e5-97b2-98436fcd8a60.png)
![5](https://cloud.githubusercontent.com/assets/11776567/13183729/07065246-d741-11e5-8a51-1ae01d5a4ed7.png)
![6](https://cloud.githubusercontent.com/assets/11776567/13183732/072100f0-d741-11e5-91b9-c90ac712debf.png)
![7](https://cloud.githubusercontent.com/assets/11776567/13183731/071f0868-d741-11e5-9ada-0c5414cf3963.png)
![8](https://cloud.githubusercontent.com/assets/11776567/13183733/073c0440-d741-11e5-8f4d-9ed0ee3bb847.png)
![9](https://cloud.githubusercontent.com/assets/11776567/13183734/073dee90-d741-11e5-8e8d-f9db2da302e6.png)
![10](https://cloud.githubusercontent.com/assets/11776567/13183735/075714b0-d741-11e5-9d06-9df1fe883e56.png)
![11](https://cloud.githubusercontent.com/assets/11776567/13183736/0758c288-d741-11e5-9085-270c3ec0d88a.png)
![12](https://cloud.githubusercontent.com/assets/11776567/13183737/075faf8a-d741-11e5-802a-c9b7b698d32a.png)
![13](https://cloud.githubusercontent.com/assets/11776567/13183738/0770a11e-d741-11e5-9f34-53225c51742e.png)
![14](https://cloud.githubusercontent.com/assets/11776567/13183739/07719092-d741-11e5-937c-0eaebeff6686.png)
![15](https://cloud.githubusercontent.com/assets/11776567/13183740/0771c814-d741-11e5-976f-f718ee4511fe.png)
![16](https://cloud.githubusercontent.com/assets/11776567/13183741/077ab9ba-d741-11e5-9f3b-35e4508c5f55.png)
![17](https://cloud.githubusercontent.com/assets/11776567/13183742/079175a6-d741-11e5-870a-162d2f399a65.png)
![18](https://cloud.githubusercontent.com/assets/11776567/13183743/07968316-d741-11e5-8629-4a1e913fd295.png)
![19](https://cloud.githubusercontent.com/assets/11776567/13183744/07a0f292-d741-11e5-9b57-da71e51666cf.png)
![20](https://cloud.githubusercontent.com/assets/11776567/13183745/07a955f4-d741-11e5-8a8f-bc5ed219cfca.png)
![21](https://cloud.githubusercontent.com/assets/11776567/13183746/07ab5c00-d741-11e5-82da-5d51a7d6b416.png)
![22](https://cloud.githubusercontent.com/assets/11776567/13183747/07b12234-d741-11e5-9a2c-7f824962ba66.png)
![23](https://cloud.githubusercontent.com/assets/11776567/13183748/07bc1b62-d741-11e5-9601-01b7f183eec3.png)
![24](https://cloud.githubusercontent.com/assets/11776567/13183749/07c48a7c-d741-11e5-8d3f-eb80b5c76b42.png)
![25](https://cloud.githubusercontent.com/assets/11776567/13183750/07c5f114-d741-11e5-8ed7-bc18d86c5169.png)
![26](https://cloud.githubusercontent.com/assets/11776567/13183751/07cba03c-d741-11e5-97c7-874563746270.png)
![27](https://cloud.githubusercontent.com/assets/11776567/13183752/07d7a530-d741-11e5-9962-7935999574df.png)

**Comment by sedat27** [comment]
Kamera ve galeri sorunuda redmi note3 te devam etmekte

**Comment by raoc999** [comment]
Evet bende şimdi kurdum, Galeri ve Kamera sorunu devam ediyor. Artık bu iki sorun için Settings dosyasını tamamen bitirmeyi ondan sonra çalışmasını umuyorum. Hataları söyleyen arkadaşlara çok teşekkür ederim. Bende farklı yazım hataları gördüm. Daha çevirmediğim 10 klasör var. Bunlardan en önemlisi Settings. Ondan sonra 6.2.18 uyarlaması ve yazım hatalarını düzeltmekle devam edeceğim. Cenkay'a özellikle teşekkür ediyorum. Gördüğü bazı yerlere daha sıra gelmedi, Bazı yerlerde de neyin nerede olduğunu bilmemekten, hele göreyim diye düzeltmemekten hatalar oldu. Tavsiyelerini uygulayacağım.

**Comment by CenkayKESER** [comment]
Hocam ek olarak telefon şarj olurken normalde kilit ekranında tarihin göründüğü kısımda 2-3 saniyeliğine şarj oluyor gibi bir yazı geliyor. Oda tamamen büyük yazılmış. Büyük yazılmış yazılar inanılmaz derecede itici geliyor nedense sizden ricam büyük yazı bırakmayalım romda.

**Comment by sedat27** [comment]
Orhan kardesim. Galerideki sorun. Cihaz kamera ve ekran goruntuleri klasorunu gizli yapiyor kendiliginden. Sorun buradan kaynaklaniyor. Am neden sadece Turkce de yapiyor o ilginc...???

**Comment by sedat27** [comment]
Deneyin. Cekim yaptiktan sonra klasorler gizleniyor. Gizliligi kaldirin. Cekimden sonra geri geliyor. Cozum biraz zor gibi!!!

**Comment by sedat27** [comment]
Ayrica bazi Turkcelestirmeler abarti olmus. Mesela sms ayarlarinda "teslimat durumu" zorlama olmus biraz.kargo gibi:)
Mail ayarlari "gorusmeye bak" ne demek.
Ayni yerde "mesajin devamini sil" alakasi yok.sildikten sonra devamm et olmali.
Ayni yerde "pil tassarufu" alakasiz. Esitleme zamanlamasi olmali.
Not ayarlari."hatirlatici susturmayin" yerine sessizde hatirlat olmali.
Bunun gibi bir cok yer var.
Ceviriyi yaparken turkce yapmak icin zorlamaya bence gerek yok. Onemli olan kullanicinin anlamasini saglamak olmali. Hic mi kullanmamis biri bile hemen anlamali ayarlari falan...

**Comment by raoc999** [comment]
Sizinle benim aaramdaki fark: Siz çevirip neyin nerede olduğunu gördünüz, ben daha yeni görüyorum. Zaten gördükçe bu buraya oladı diyorum bir sonrakinden itibaren düzeltmeye başlayacağım. Bazı yerlerde tabirle kastedilen çok farklı şeyler, bize en uygun olanı yapmak gerekiyor ki zaten sizde aynı şeyi yapmışsınız. Dosya ve  içindeki hataları söyleyin bir sonrakinde düzeltelim. Teşekkürler. Diğer taraftan kamera ve galeri ile ilgili (Ayarlarda gördüm) satırlarda yer alan %xxxds gibi hatalardan kaynaklanıyor olabilirmi. Akşam Ayarları çevirirken İngilizcesinde bir satırda %1s -%2s olan bir satır Türkçede %s %s diye bir hata olmuş. Acaba diğer satırlarda da böyle birşey olmuş mudur. 2000-2500 arasında

**Comment by sedat27** [comment]
ben 3 senedir mi kullanıyorum.başka hiçbir telefon kullanmadım.Mi teraziden home smart,kamera,3 telefon ne ararsan var bende. Artık gözüm kapalı kullanıyorum.
Bu yüzden çevirilerde ne nerede olmalı biliyorum. Haklısın tabi gördükçe düzeltmeler yapılır.
Sakın yanlış anlama ben yardımcı olmak adına yazıyorum. Emeğine büyük saygım var.
Hatta dilersen dosya gönder çevirip göndereyim.ucundan tutmak anlamında.
Kamera olayı ayarlardan gibi duruyor. Klasör gizleme gibi bir ayar görürsen oraya odaklan bence.
Selamlar
@raoc999

**Comment by raoc999** [comment]
Teşekkür ederim Sedat. Bugün işlerimi erken bitirirsem Ayarları upload edeceğim. 3-4 aşamalı olarak Kamera ve Galeri işini çözeceğiz. Önce Ayarları atıp bu haftaki yazılımda çözülüp çözülmediğini göreceğiz. Eğer çözülmezse sonraki hafta Kamera yazılımını Orjinal İng. ile değiştireceğim, Çözülürse demek ki Kamera yazılımında çözülmezse Galeri yazılımını Orj. İng. ile değiştireceğim. Compile etmek için tüm dosyalar bende olsa hızlıca çözerim. Daha önce uydu alıcı yazılımlarını yapıyordum, oradan tercübem var. Tavsiye ve eleştirilerini beklerim, tabii olarak sen telefonla haşır neşirsin... Not olarak resmi çeviriyi yapan arkadaşlar Ayarların sonlarına doğru Wi-Fi Display ile ilgili satırların çoğunu yanlış çevirdiler. Wi-Fi Display  ile Kablosuz Ekranlar kastedilmiş -Intelin yeni teknolojisi- WLAN değil. Resmi çeviriyi düzeltirlerse çok iyi olur, İsterlerse ben akşama aksilik olmazsa upload yapacağım, benimde hatalarımı düzelterek eklesinler.... Herkese teşekkür

**Comment by raoc999** [comment]
Arkadaşlar, söylenilen hataların bir kısmını düzelttim 6.2.18'e uyarlayıp güncelliyorum. Bazı yerlerdeki İngilizce kelimelere daha sıra gelmedi, bazı yerlerde söylenilen hatalarda varolan Türkçe çeviriden kaynaklanıyor. Benim çevirdiğim dosyalarda yoklar. Varolanlar varsa da ben bulamadım. Komple çeviriyi bitireyim o zaman daha rahat bulurum. Hataları "" içinde büyük küçük harfe göre yazın ne olması lazım onuda yazın düzeltirim. Şu an Teleservice dosyasına geçtim. Toplam 9 klasör kaldı. TeleServide dosyasını 6.2.18 olarak çevireceğim. Teşekkürler.

**Comment by CenkayKESER** [comment]
Yarın çıkacak olan 6.2.25 sürümüne yetişirse yeni çeviri dosyaları tekrardan geri bildirimde bulunabilirim. Son olarak sizi uğraştırmaz ise 6.2.18 ile birlikte gelen yeni arama ekranında çince bazı alanlar var onları çevirmeniz mümkün mü? Bildirim alalına ve ana ekrandan aşağıdan yukarı çekince gelen arama özelliğinden bahsediyorum.

**Comment by raoc999** [comment]
O çince alanlar galiba kullandığımız yazılım yazılımın yeniden compile yapılmasından kaynaklanıyor. Elimden geldiğince düzelteceğim. Cenkay kardeşim söylediğin hataların bir kısmını düzeltim. Düzeltmediğim yerler benim yaptığım çeviri değil veya ing. olanlara daha sıra gelmedi. Bugün ve yarın söylediğiniz hatalarla çevirisini bitirdiklerimi 6.2.18 sürümüne göre derliyorum. İyi akşamlar

**Comment by sedat27** [comment]
@raoc999 yazı tipi boyutunda "DK" daha küçük olarak mı düşünüldü?
Türkçeleştirme de abartı olmuş gene. Kıyafet alırken bunu DK boyutu var mı demek gibi bişey olmuş.
XL ve XXL dururken XS olmaması garip.
sıralama -2 ,-1 0,1,2,3 şeklinde yapılabilir.

**Comment by raoc999** [comment]
Aslında artık bilmeyen yoktur diye XL vb... olanları bırakmak istiyordum. Bir bakayım şikayet olacak mı dedim sen şikayet ettin ya geri dönerim. İncelemeye devam edin. Klasör sayısı daha a arttı. Bazı yerlerdeki hataları daha düzeltmeden bugün erkenden 6.2.25 yüklendi. Öğleye kadar eklerim diye düşünüyordum olmadı. Bende düzeltmeler ve derlemeleri yaptım 6.2.25 olarak upload ettim. Yeni bir başlık ekliyorum oradan hataları söyleyin sadece İng. olan yerleri söylemeyin çünkü daha tam olarak çeviri bitmedi.
