### ISSUE TITLE
Sürüm 6.2.25 Hataları, İstek, Eleştiri, Öneriler

### ISSUE THREAD

**Issue by raoc999** [ingbrzy/MA-XML-8.0-TURKISH#26]
Arkadaşlar;
Haftalık olarak böyle konu açalım ve bu konu altında o haftaki sürüme ait Türkçe imla hataları, yanlışlıklar, çeviri hatalarını vb... bir yazalım. Şimdilik İngilizce geçen yerleri yazmayalım. Şu ana kadar -alfabetik- Settings bitti. Daha 10 klasör var. Yazılım güncellendikte artışlarda oluyor. Özellikle Ekran Alıntısı yapabilirseniz çok iyi olur. Kamera ve Galeri çözümleri için; gelecek haftadan itibaren herbirinin orjinal -çevrilmemiş- halini upload edeceğim. Eğer herhangi bir tanesinde düzelirse, Merge yazılımıyla TR-ING arasındaki farkları satır satır kontrol edeceğim. Mutlaka çözmemiz lazım, en çok benim canımı sıkıyor.  Zaten çeviriye bundan dolayı başladım. Bazı yerlerde farklı usuller denedim, beğenilmezse, şikayet gelirse eski haline döneceğim. Mesela X,XL, XXL gibi yerleri B, DB, ÇB -Neden belki bilmeyen vardır diye, Ama artık X, XL standart tâbir oldu. Gerekirse geriye dönerim.

**Comment by raoc999** [comment]
Kilit ekranındaki büyük harfli metni ve diğer yerlerdeki hataları düzeltim sabah upload etmiştim fakat eklenmemiş. Demek ki en geç Perşembe günü teslim etmek lazım :(

**Comment by sedat27** [comment]
@raoc999 XS XL vs olduğu gibi kalsın bence.Onun türkçe kısatlması yok gibi. 

-Ayarlarda 4 madde."Fazlası" kelimesi yerine "**Diğer Bağlantılar**" olabilir.
-Bluetooth ayarları. "Keşfedilebilir" yerine "**Bulunabilir**" olmalı.
-Bildirimlerde "Geçiş Pozisyonu" yerine "**Kısayol Pozisyonları**" olabilir.
-Kilit Ekranı Parmakizi ayarlarında "Cepte Aramayı Önle" anlaşılmıyor. "**Cepteyken Uyanma**" olabilir.
-Rahatsiz Etme ayarlarında. "Her Zaman Bozukluklara izin ver" ve diğer maddeler hiç alakası yok.
-"Mi Taşıyıcı" yerine "**Mi Gönder/Al**" olabilir.
- Sistem uygulaması olan "Güvenlik" yerine "**Araçlar**" daha uygun olacaktır. Çünkü içinde temizleme pil vs var. tam anlamıyla Güvenlik değil.

Bunlar yanlış değil ancak düzeltilse daha profesyonel olacak gibi

**Comment by raoc999** [comment]
Her Zaman Bozukluklara izin ver ne diyeceğimizi ve ne işe yaradığını anlamadım, kelimelerin TR karşılıklarında da başka birşey yok?! Mi Taşıyıcı yerine değin veya orj Mi Mover olarak değiştiririz. Araçlar konusunda ise önceden öyle idi şimdi İng. Security olarak değiştirdi. İng. mana geniş, Koruyucu vb... Bizde net olarak ifadesi nedir bilmiyorum. Çünkü adamlarda Araçlar diye beşka şeylerde var iki şey aynı olmamalı. Hem güvenliği, hem araçları kapsayacak bir kelime bizde de vardır?! Tavsiyelerine uyacağım. Teşekkürler.

**Comment by sedat27** [comment]
![screenshot_2016-02-28-12-01-18_com android settings](https://cloud.githubusercontent.com/assets/9906622/13378570/22f06824-de13-11e5-8d4b-575317d72f42.png)

Sirayla;
1. Rahatsız etme modu kapalı
2.İstisnalara izin ver
3. Rahatsız etme modu açık

Olabilir

**Comment by aykutyenihan** [comment]
slm hocam kilit ekranında sağa kaydırma kısayolu telefon arama uygulamasını açıyor ama kısayola dokunulduğunda yazan mesajda ''Mİ kumanda için sağa kaydırın'' şeklinde. sanırım orjinal dilde kumanda kısayolu var ama xiaomi.eu romda bu kısayol telefon uygulaması olarak değiştirildiği için yanlışlık oluyor. Kolay gelsin teşekkürler.

**Comment by raoc999** [comment]
Tavsiyelerinizi çin teşekkürler, benimde gördüğüm imla hataları dahil olamak üzere hepsini düzeltmeye çalışacağım. Lütfen gördüğünüz hataları, olması gerekenlerle birlikte yazın.

**Comment by CenkayKESER** [comment]
***Ayarlar***
Ayarlar --> Fazlası yerine diğerleri veya daha fazlası şeklinde olmalı.
Ayarlar --> Fazlası --> İnternet Paylaşımı & taşınabilir hotspot >> İnternet paylaşımı şeklinde olmalı.
Ayarlar --> Bluetooth --> Bluetooth kapalı olduğunda kapat yapıyor, kapalı olarak değişmeli.
Ayarlar --> Bildirimler --> Geçiş pozisyonu yerine bildirim alanını düzenle gibi değişmeli.
Ayarlar --> Bildirimler --> En üstteki basın & değiştirmek ile giden bölüm Değiştirmek için basılı tutun şeklinde değişmeli.
Ayarlar --> Temalar --> Telefonda gelen varsayılan tema defoult olarak görünüyor, varsayılan olarak değişmeli.
Ayarlar --> Sistem yazı tipi --> Sistem yazı tipi yerine yazı tipi olmalı.
Ayarlar --> Metin boyutu --> Metin boyutu yerine yazı boluyu olmalı.
Ayarlar --> Ekran --> Okuma Modu --> Okuma Modu kapalı olduğunda kapat yapıyor, kapalı olarak değişmeli.
Ayarlar --> Ses & titreşim --> Ses yerine sesler veya ses düzeyleri şeklinde düzenlenmeli.
Ayarlar --> Ses & titreşim --> Mesaj alındı yerine yeni mesaj şeklinde olmalı.
Ayarlar --> Ses & titreşim --> mesaj teslim edildi yerine mesaj gönderildi şeklinde olmalı.
Ayarlar --> Ses & titreşim --> Tuş takım dokun sesleri yerine tuş sesi veya tuşa dokunma sesi olmalı.
Ayarlar --> Kilit ekranı & parmak izi --> Ekran kilidi yerine kilit ekranı olmalı.
Ayarlar --> Kilit ekranı & parmak izi --> Bluetooth cihazlarıyla kilidi aç yerine Bluetooth ile kilidi aç gibi bir şey olmalı.
Ayarlar --> Kilit ekranı & parmak izi --> Akıllı kapak modu yerine kılıf modu olmalı.
Ayarlar --> Rahatsız etme --> Bu bölüm tamamen elden geçmeli. Bildirimleri her zaman göster, hiçbir bildirim gösterme, istisnaları göster şeklinde olabilir.
Ayarlar --> Dil & giriş --> Şahsi sözlük yerine kişisel sözlük veya kayıtlı kelimeler tarzında bişeyler olmalı.
Ayarlar --> Düğme ayarları --> Burası tuşlar şeklinde düzenlenmeli.
Ayarlarda çoğu yerde ilk kelimeden sonraki kelimede hep büyük harf ile başlanmış, bunun yerine bence küçük harf ile devam edilmeli.

**Comment by CenkayKESER** [comment]
OTG bağlantısı yapınca USB depolam cihazı bağlandı şeklinde uyarı geliyor, usb aygıtı bağlandı şeklinde olursa daha doğru olabilir.

**Comment by raoc999** [comment]
Sedat, Cenkay ve diğer arkadaşlar teşekkür ederim. Belirttiğiniz hataları düzelttim. Bir kaç hatayı bulamadım veya o hatalar benim çevirmediğim eski klasörlerden kaynaklanıyor. Halen çevirmediğim 8 klasör var. Önümüzdeki haftaya Güncelleme, Xiaomi Hesabı ve Hava Durumu ile ilgi dosyaları çevireceğim. Ayrıca bu hafta Kamera yazılımının çevirisini Orj. İng. haline döndürüyorum. Bakalım Kamera çevirisinden mi hata kaynaklanıyor. Ondan değilse gelecek hafta Kamerayı TR olarak Galeriyi İng. olarak değiştirip bu sorunu bulmaya çalışacağız. Halen proje bitmediğinden aralıklarla düzeltmeler yapacağız. Orhan CAKMAK

**Comment by CenkayKESER** [comment]
Ayarlar --> Yüklü uygulamalar --> varsayılan çevir yerine adama olmalı.
Ayarlar --> Sistem uygulamaları --> güvenlik ->> veri kullanımı --> önemli feragat ve içeriği çok enteresan olmuş tekrardan bakılması gerek.
Ayarlar --> Sistem uygulamaları --> mesaj ->> Mi mesajı olmuş mi mesaj olacaktı.
Ayarlar --> Sistem uygulamaları --> telefon ayarları ->> titreşim bölümü içeriğindeki haftalık bildirim vs. garip olmuş tekrardan ele almak gerek.
Ayarlar --> Mi hesabı bölümünde backup and restore gibi İngilizce alanlar mevcut.
Ayarlar --> Mi hesabı bölümünde depolama kısmında İngilizce kısımlar var.
Daha not aldığım bazı hatalar var, cuma günü yeni durum çıksın tekrardan geri bildirimde bulunurum. Yemeklerimiz için çok teşekkürler, çok uğraş vererek bu işi yapıyorsunuz.
Sizden ricam ilk kelimelerden sonra büyük harf ile baslamamaniz. Bazı kalıntıların var ve bu tur şeylere çok takıyorum ;) Çeviri ekibine dahil olursam elimden geldigince sizlere yardımcı olmaya çalirisirim.
