### ISSUE TITLE
Dikkat! 04.03.2016'da Çıkacak Sürümle Alakalı

### ISSUE THREAD

**Issue by raoc999** [ingbrzy/MA-XML-8.0-TURKISH#27]
Arkadaşlar bu hafta çıkacak sürümde Kamera yazılımını İng. -orj- olarak değiştiriyorum. Kamera-Galeri sorununu çözmek için önce Kamera yazılımına bakmamız lazım. Eğer sorun orj. dilde çözülürse demek ki çeviridi bir hata yapmışız. Eğer tekrar devam ederse gelecek hafta Galeri yazılımını orj. çevireceğiz. Bilgilerinize... Tavsiyeleriniz için raocakmak@gmail.com adresime mail atabilirsiniz.

**Comment by sedat27** [comment]
Cok dogru bi hareket..

**Comment by sedat27** [comment]
Orhan Kardeşim birde şu aşağıda doğru çekince arama var ya. orası çince.
Ama ilginç olan mipad var bende onda türkçe

**Comment by raoc999** [comment]
Sedat, bende bir ara Türkçe idi sonra tekrar çince oldu, Çeviri dosyalarında sadece Takvimde Çince var, o da çinlilerin takviminden dolayı, galiba orasını Baidu'dan çekiyor. Bir kaç yerde öyle satırlar gördüm. Bu haftaki güncellemede o satırların adresleri değişti, derleyip görelim. Kameradan ne haber, ben daha kurmadım

**Comment by aykutyenihan** [comment]
mi4c kullanıyorum kamerayla yada galeriye girmeyle ilgili hiçbir sorun yoktu ta ki son güncellemeye kadar. sistem dilini ingilizce yapınca sorun yok ama dili Türkçe yapınca kamera uygulaması hata veriyor ve hicbir şekilde açılmıyor.
