### ISSUE TITLE
Sürüm 6.3.3 Hataları ve Tavsiyeler

### ISSUE THREAD

**Issue by raoc999** [ingbrzy/MA-XML-8.0-TURKISH#28]
Arkadaşlar geçen hafta ki tavsiyeleri ekledim, sonradan yazanları ekleyeceğim, göze çarpan hata, istek ve tavsiyeleri belirtin. İng. olarak gördüğünüz her yer ya yeni eklendi, ya da daha önceki çeviriden kaldı. Sonuçta benim çevirmediğim 8 klasör var. Şu an Kamera + Galeri sorununun çözmemiz lazım. Sırf bunun için çeviriye başladım.  6.3.3 ile ilgili bu başlıkta yazı yazabilirsiniz. Dikkat bu çeviri sadece Hermes - Redmi Note 2 içindir. Diğer ürünlerde fazladan özellikler ve içerikler olabilir, Hermes bittikten sonra öteki ürünler için çeviri yapmaya devam edeceğim.

**Comment by aykutyenihan** [comment]
hocam elinize sağlık gayet iyi yöne gitti çeviri sayenizde. Ama benim tavsiyem bazı şeyleri terimleri değiştirmeye gerek yok daha doğrusu başka bir kelime aramaya gerek yok belli kalıplara. mesela telefon hakkında bölümünde miui sürümü kısmında sabit sürüm yazıyor. Sabit çeviri olarak doğruda olsa orda sabit yazma ya stabil yazar ya kararlı sürüm yazar. bunun gibi ufak ama önemli ayrıntılar var. kolay gelsin zamanla hepsi düzelecektir teşekkürler.

**Comment by sedat27** [comment]
Orhan kardesim malesef kamera galeri sorunu devam ediyor. Gene camera ve screenshot klasorleri gizleniyor kendiliginden. Bu nedenle kayit yapilamiyor ve gostermiyor.

**Comment by sedat27** [comment]
Hem kamera hemde galeriyi ingilizce birakmayi deneyebilirsin. Eger cozulurse sorun galeride demektirki tahminimce oyledir.

**Comment by raoc999** [comment]
Sedat; dediğin gibi galeri ve kamerayı ing. olarak bırakacağım. Şu an Acount dosyalarını TRye çeviriyorum, mail ayarlarında bir kaç hata gördüm, haftaya 6.3.3-e göre derleme yapıp, var olan hataları gidereceğiz....

**Comment by sedat27** [comment]
![screenshot_2016-03-06-09-21-42_com android settings](https://cloud.githubusercontent.com/assets/9906622/13552897/0f10e2e2-e37d-11e5-8d84-79388c1fb3b3.png)
Sifre belirleme ekraninda parmakizi girmek icin sifre istiyor. Orada altta sifreni unuttum kismi boyle kalmis

**Comment by MIUITurkey** [comment]
Sadece u değil ul olması gerek kod çıkmaması için bilgi
6 Mar 2016 09:24 tarihinde "sedat27" <notifications@github.com> yazdı:

**Comment by CenkayKESER** [comment]
Güncelleme güzel olmuş, ayarlar daki çoğu kısım düzelmiş. Dahada güzel olması için bazı önerilerim;
Ayarlar --> Ağ altındaki fazlasi yerine ek ayarlar olmalı.
Ayarlar --> Bildirimler --> Uygulama bildirimleri --> Rozetler yerine simgeler olmalı. Aynı şey bu bölümdeki uygulama içindeki Rozetler içinde geçerli.
Ayarlar --> Yazı Tipi --> Zirvedekiler yerine popüler olmalı.
Ayarlar --> Ses & Titreşim --> Ses yerine ses seviyesi olmalı.
Bildirim ekranındaki Çince yazi o özelliği bir kere kullandıktan sonra geliyor. Verilerini silerseniz geri türkçe oluyor.

**Comment by sedat27** [comment]
@raoc999  Orhan kardeşim şarj azaldığında kilit ekranında "LLütfen şarj cihazı bağlayın" gibi bir şey yazıyor. orada "LLütfen" olmuş. çift L.

**Comment by raoc999** [comment]
Devam edin :) Son iki dosyayı da bitirip, upload ettikten sonra hataları ve 6.3.3 için derlemeleri düzelteceğim. Not olarak ben sadece Hermes olan ürünü çeviriyorum. Diğer ürünlerden ek dosyaları da çevireceğim.

**Comment by raoc999** [comment]
Arkadaşlar 6.3.3 ve 6.3.8 derlemelerini yapıyorum.Telefonda Cihazarım diye bazı hatalar görüyorum fakat elimizdeki dosyalarda böyle birşey yok. Bizde olmayan hangi dosyadan çekiyor bilemiyorum. Kamera ve Galeride çok satır kaldırıldı. ama yinede biz ing. sürünlerini ekleyeceğiz. Bundan sonraki hataları bir sonraki sürüme düzelteceğim. Ama siz buldukça yazın.

**Comment by sedat27** [comment]
Orhan, Kilit ekraninda "... yukarı doğru kaydırın" yerine "... yukarı kaydırın" yeterli gibi. Cok uzun oluyo!!

**Comment by salihkiraz** [comment]
kamera sorunu mi4c cihazımda yaşanmaya başladı ingilizce ama açılmıyor. galeride sorun yok.eski stabil sürümde sorun yoktu. bende bu sürümde ki hatayı gidermek için kamera uygumalasını bulup flasladım program ingilizce ama sorunsuz çalışıyor bu uygulamanın linkini vereyim belki bir fikir verebilir. 
http://en.miui.com/thread-93802-1-1.html

**Comment by MIUITurkey** [comment]
Mi4c kamera için eski romlardan apk dosyasını al değiştir sorun tamamdır
10 Mar 2016 20:54 tarihinde "salihkiraz" <notifications@github.com> yazdı:
