### ISSUE TITLE
(Build 6.3.10) Hatalar- İstek - Öneriler

### ISSUE THREAD

**Issue by raoc999** [ingbrzy/MA-XML-8.0-TURKISH#29]
Arkadaşlar, söylenilen hataları düzelttim, bir kısmını bıraktım, bir kısmıda benim kütüphanede yok, nereden çektiğinide bilmiyorum. Şu ana kadar XRemote Controller dosyası hariç hepsini çevirdim. Bazı unuz cümleleri mantıklı bir şekilde kısaltacağım, bazı yerlere yakışmayan çevirileri ise düzelteceğim. Türkçe kuşa döndüşünden adam bizim sadece "almak" fiilini 5 farklı şekilde kullanmış. Hayat varken Yaşam gibi saçma uydurukçaları kullanarak bizi bu hale getirdiler. Derin mevzu; bir ülkeyi yıkmak için diliyle oynayın yeter. 
 1: Galeri ve Kamera ing. olarak değiştirildi... Hatayı bulmak açısından...
 2: Bende Posta hesabı çalışmıyor, sadece bende mi hata var, deneyip bilgilendirirseniz sevinirim.
 3: Bazı yerlerde Aç-Kapa olan ifadeler Açık-Kapalı olarak değiştirildi.
 4: 6.3.3. derlemesi yapıldı.
 5: Redmi Note 2 hariç hangi cihazı kullanıyorsunuz, ona göre o cihazların kütüphanelerini ekleyeceğim.
 .....

**Comment by CenkayKESER** [comment]
Önceki sürümlerde yer alan çoğu çeviri hatası bu sürümde giderilmiş, ellerine sağlık. Detaya inince bazı hatalar hala mevcut ancak artık finale yaklaşılmış. Kamera konusunda uygulamaları ingilizce yapmakta sorunu gidermemiş gibi görünüyor zira Mi4 üstünde kamera uygulaması hiç çalışmıyor. Açtığım gibi durduruldu hatası veriyor. Gördüğüm hatalar şu şekilde;

-Kurulum ekranında linklerin taglarında sorun var, tüm linkler bu şekilde;
![screenshot_2016-03-11-09-47-12_com xiaomi account](https://cloud.githubusercontent.com/assets/11776567/13696989/0730da56-e773-11e5-9779-fe41d2bb624a.png)

-Burda ise "Varolan hesabınızda oturum açın" yerine Mi hesabında oturum aç, Mi hesabı oluşturun şeklinde olursa bence daha iyi olur. Alttaki Mi bulut, mi tema mağazası gibi sürekli  olarak mi demek yerine Mi bulut, tema mağazası ve diğer hizmetlerde oturum aç şeklinde olabilir.
![screenshot_2016-03-11-09-47-21_com xiaomi account](https://cloud.githubusercontent.com/assets/11776567/13696998/11d49470-e773-11e5-99b6-aa7d979abb3e.png)

-Burada ise Günlüklü kilit ekran yerine "Günlük Kilit Ekranı" olmalı. Açıklama çok garip olmuş, oraya da bir ek atılmalı. Butonlarda ise kabul ediyor ve kabul etmiyorum olması yeterli.
![screenshot_2016-03-11-09-50-06_com mfashiongallery emag](https://cloud.githubusercontent.com/assets/11776567/13697027/530eebe8-e773-11e5-9920-4496365a4321.png)

-Burda ise Her gün kilit ekranı şeklinde giden metin yerine kilit ekranı resimleri veya kilit ekranı albümleri olabilir. Fallower kısmıda takipçi olarak güncellenmeli. Yapılabiliyorsa general vs. kısımları da çevirilmeli ama sanırım oralar direk sunucudan çekiliyor.
![screenshot_2016-03-11-09-50-25_com mfashiongallery emag](https://cloud.githubusercontent.com/assets/11776567/13697064/a91f17ec-e773-11e5-90b3-01745e97cbb8.png)

-Şarj azaltığında gelen ekrandaki Şarj cihazına bağlayın yerine şarj azaldı gibi bir şey olmalı.
![screenshot_2016-03-11-09-51-11_com miui cleanmaster](https://cloud.githubusercontent.com/assets/11776567/13697088/cd928b2c-e773-11e5-9a86-1065671c954d.png)

-Ayarlar --> Telefon hakkında --> Durum kısmında IMEI bilgileri ingilizce kalmış, düzeltilmeli.
![screenshot_2016-03-11-09-54-10_com android settings](https://cloud.githubusercontent.com/assets/11776567/13697123/f55a2f20-e773-11e5-8cfe-a9ad7e4d293e.png)

-Burda ise otomatik güncelleme kontrolü şeklinde olabilir. Wlan'a bağlandığımda güncelleştirmeleri indir veya kontrol et şeklinde açıklamada güncellenebilir.
![screenshot_2016-03-11-09-54-23_com android updater](https://cloud.githubusercontent.com/assets/11776567/13697159/247d1ce0-e774-11e5-82b5-4e06c52c1830.png)

-İnternet paylaşımı bölümünde paypaşma bantları bölümü ingilizce kalmış, Sadece frekans değeri yazsa yeter bance. 2.4 gHz şeklinde.
![screenshot_2016-03-11-09-55-23_com android settings](https://cloud.githubusercontent.com/assets/11776567/13697229/b3e8500c-e774-11e5-8f7e-5f1c8d57464e.png)

-Burda ise taşınabilir hotspot yerine taşınabilir internet olmalı. 
![screenshot_2016-03-11-09-55-35_com android settings](https://cloud.githubusercontent.com/assets/11776567/13697246/d62483c0-e774-11e5-960d-a8d8a86c67ec.png)

-Burdaki ekran kilidi yerine kilit ekranı olmalı. 
![screenshot_2016-03-11-09-56-51_com android settings](https://cloud.githubusercontent.com/assets/11776567/13697256/ef782cfa-e774-11e5-895f-5fffd874536b.png)

-Mağaza, tema marketi, font mağazası alanlarındaki zirvedekiler bence popüler olarak değiştirilmeli.
![screenshot_2016-03-11-09-58-09_com android thememanager](https://cloud.githubusercontent.com/assets/11776567/13697275/0e315b26-e775-11e5-9f28-1cba1aed5906.png)

-Burda ise açıklama biraz garip olmuş, bence uygun parlaklığı seçin olmalı veya bu açıklama komple kaldırılmalı.
![screenshot_2016-03-11-09-58-36_com android settings](https://cloud.githubusercontent.com/assets/11776567/13697293/2d0e3d34-e775-11e5-99ed-f4c76efc4ad2.png)

-Rahatsız etme bölümünde ingilizce kalan yer olmuş.
![screenshot_2016-03-11-10-00-44_com android settings](https://cloud.githubusercontent.com/assets/11776567/13697301/3f40ac26-e775-11e5-9222-79098b9c5d38.png)

-Esas Uygulamalar yerine son kullanılanlar veya sık kullanılanlar olarak değiştirilmeli.
![screenshot_2016-03-11-10-01-49_com android fileexplorer](https://cloud.githubusercontent.com/assets/11776567/13697305/46a5d9fa-e775-11e5-8830-88a630cfab87.png)

-Burdaki şahsi uygulamaları kilitle yerine uygulamaları kilitle olmalı. Kilitlemek için uygulamaları seçin yerine kilitlenecek uygulamalar veya daha farklı bir şey olmalı.
![screenshot_2016-03-11-10-01-57_com android settings](https://cloud.githubusercontent.com/assets/11776567/13697354/8eb3cf68-e775-11e5-9eba-a9ed07903062.png)

-Ayarlar --> Ek alarlar --> Giriş ve dil bölümündeki sözlüğüm kısmında parantezler unutulmuş.
![screenshot_2016-03-11-10-02-47_com android settings](https://cloud.githubusercontent.com/assets/11776567/13697367/a7ef3bf2-e775-11e5-9107-a40baf03bf70.png)

-Tek elle kullanım modundaki inches yerine sadece inç olmalı.
![screenshot_2016-03-11-10-03-07_com android settings](https://cloud.githubusercontent.com/assets/11776567/13697383/cfdf5b42-e775-11e5-832c-bea374c8de5f.png)

-Pil kullanım bölümünde neyin ne kadar pil kullandığı kısımda yer alan Zaman açık kullanım zamanı veya daha doğru bir şey ile güncellenmeli.
![screenshot_2016-03-11-10-03-43_com miui securitycenter](https://cloud.githubusercontent.com/assets/11776567/13697405/f1d6f2d2-e775-11e5-82ce-aa2ebced5b6c.png)

-Burda bence sistem animasyonu yerine animasyonları kapat, performansı arttırır şeklinde olmalı. Benzer şekilde biğer seçenekte güncellenmeli.
![screenshot_2016-03-11-10-04-01_com android settings](https://cloud.githubusercontent.com/assets/11776567/13697431/217d7e7a-e776-11e5-902f-ed5e9fad5b2f.png)

-Led ayarları kısmında da ingilizce bazı alanlar kalmış.
![screenshot_2016-03-11-10-04-22_com android settings](https://cloud.githubusercontent.com/assets/11776567/13697439/32922fda-e776-11e5-843f-cba860b1e658.png)

-Erişilebilir kısmında bazı ingilizce kısımlar var, experimental yerine deneysel olmalı.
![screenshot_2016-03-11-10-04-44_com android settings](https://cloud.githubusercontent.com/assets/11776567/13697473/52d936bc-e776-11e5-87d6-3a4b2fa905a5.png)

-Geliştirici şeçeneklerinde bazı ingilizce kısımlar var.
![screenshot_2016-03-11-10-05-02_com android settings](https://cloud.githubusercontent.com/assets/11776567/13697489/6d32aab6-e776-11e5-9f16-393554831863.png)
![screenshot_2016-03-11-10-05-10_com android settings](https://cloud.githubusercontent.com/assets/11776567/13697490/6d33f9b6-e776-11e5-94eb-14bc9795c393.png)
![screenshot_2016-03-11-10-05-23_com android settings](https://cloud.githubusercontent.com/assets/11776567/13697491/6d345758-e776-11e5-8081-a55a16da9d86.png)
![screenshot_2016-03-11-10-05-30_com android settings](https://cloud.githubusercontent.com/assets/11776567/13697492/6d34c1fc-e776-11e5-93ab-0f310eee0c2f.png)

-Verileri yedekleme bölümünde bazı ingilizce alanlar var.
![screenshot_2016-03-11-10-05-52_com android settings](https://cloud.githubusercontent.com/assets/11776567/13697501/8b3b9db0-e776-11e5-8c7f-91c676a544a8.png)
![screenshot_2016-03-11-10-06-01_com android settings](https://cloud.githubusercontent.com/assets/11776567/13697500/8b3aeab4-e776-11e5-8cab-6dcf87485ca6.png)

-Mi Bulut ayararında ingilizce kısımlar var ve telefon internete bağlı değilken sadece ağ demek yerine ağ ayarları demek daha doğru olur.
![screenshot_2016-03-11-10-07-00_com miui cloudservice](https://cloud.githubusercontent.com/assets/11776567/13697519/a74bf20c-e776-11e5-887b-5909eb82984a.png)
![screenshot_2016-03-11-10-07-07_com miui cloudservice](https://cloud.githubusercontent.com/assets/11776567/13697526/aeae49f0-e776-11e5-8c6d-a0fce8722e58.png)

-Telefonu bilgisayara bağlayınca gelen alanlar ingilizce kalmış.
![screenshot_2016-03-11-10-17-26_com miui home](https://cloud.githubusercontent.com/assets/11776567/13697545/c2533eac-e776-11e5-8ec1-d3cd60360041.png)
![screenshot_2016-03-11-10-17-35_com android settings](https://cloud.githubusercontent.com/assets/11776567/13697546/c25368be-e776-11e5-83a8-9f77c8a3849b.png)

Bir sonraki güncellemede görüşmek üzere :)

**Comment by raoc999** [comment]
Cenkay, Selamlar; 
Detaylı anlatım için teşekkürler fakat bir şeye dikkat etmelisin ben çeviriyi Redmi Note 2 için yaptım. Daha Redmi Note 2 için gerkli 6.3.3 ROM verilmedi. Sen farklı telefonda deniyorsun. İngilizce olan kısımlar belki yeni sürümdeki eklerden kaynaklanıyor, diğer hatalar ise Hermes için geçerli dosyaları ona derlediklerinden, bizim içinde ROM eklensin bir deneyeceğim. Söylediğin hatalar ve düzeltmeleri adapte edeceğim. Teşekkürler... Eğer bizde de Kamera ve Galeri problemi düzelmediyse, sorun başka birşeyden o zaman. Bu durumda detaylı bir yazı yazıp Xiaomi'ye atacağım.

**Comment by raoc999** [comment]
Cenkay'a cevap:
1. Mi Hesapla ilgili yerleri düzelttim, devrik cümle farklı yerlerden çekiyordu, düzgün olacak şekilde yerleri değiştirdim, Umarım sorun olmayacak.
2. Yine Mi hesapla ilgili cümleleri düzelttim.
3.4 Günlük Duvar kağıdı ile ilgili cümleleri düzelttim, İNgilizce gelen yerler sunucudan çekiyor. Dosyada zerre İng. kalmadı :)
5. Şarj ile ilgili resimdeki "cihazina" da zaten yazım hatası var ama bendeki kütüphane de bunlar yok. Senin telefon başka model ve eski çeviriden kaynaklanıyor olabilir.
6. IMEI ile ilgili durum ise bende TR, yine senin telefonun kütüphanesinden - çünkü benim çeviri Redmi Note 2 için
7. Güncelleme ile ilgili resimdeki cümleleri düzelttim
8. Böyle bir metin yok.
9. Hotspot yerine Mobil İnternet / Mobil Net diye kısa birşey diyeceğim ) bildirimlerde de gözüksün ve anlaşılır olsun. ?!
10. Uygulama Bildirimleri düzeltildi.
11. Ben kütüphaneden Zirvedekiler yazısını kaldırmıştım, herhalde öteki çeviricilerin hoşuna gitti, senin telefonda kullanıyorlar :)
12. Parlaklık seviyesini biraz daha mantıklı cümle haline getirdim.
13. Rahatsız etme içeriğini geçen hafta düzenlemiştim, kütüphanemde halen TR, belki 6.3.10 da değiştirdiler, göreceğiz.
14. xxx bundan sonraki ing olan yerler bizden kaynaklanmıyor ya yeni güncelleme ile eklendi, ya da senin telefon trsi ile alakalı çünkü benim kütüphanede böyle birşey yok. 

Uzaktan kumanda çevirisi bitince, en son sürümle benim çevirdiğin dosyaları yeniden karşılaştıracağım. Arada farklar varsa düzelteceğim. Çünkü Güvenlik altında bazı ingilizce cümleler var ama dil dosyalarında bunlar yok...

**Comment by CenkayKESER** [comment]
Anladım hocam. Kütüphane olarak cancro (Mi3 & Mi4) ve hennessy (Resmi Note 3) ellerden ben sürekli olarak geri bildirimde bulunabilirim. Bu arada redmi Note 3 içinde kamera galeri geçiş sorunu düzelmiş. Ama mi4te kamera uygulaması hiç açılmıyor. Sanırım 6.3.11 ile birlikte düzeldi, 6.3.10da hala sorun var.
