### ISSUE TITLE
Sürüm 6.3.11 Hatalar ve İstekler (Kamera+Galeri Sorunu Çözüldü)!!!

### ISSUE THREAD

**Issue by raoc999** [ingbrzy/MA-XML-8.0-TURKISH#30]
Arkadaşlar Redmi Note 2 6.3.11 sürümünde Kamera ve galeri sorunu gitti fakat Galeri ve Kamera yazılımları Orj. İng. oladuğundan gitti galiba. Gelecek hafta Kamera yazılımını TR olarak değiştireceğim ve muhtemel Galeriden kaynaklanan çeviriyi yeniden satır satır kontrol edeceğim. Şu an 6.3.11 olarak derlemeye devam ediyorum . Özellikle File Explorer'da çoğu cümle değişti. Lütfen gördüğünüz hataları yazın... (Sadece Redmi Note 2 için)

**Comment by sedat27** [comment]
Orhan kamera galeri sorunu tamam ancak. Simdi anlamadim galeride bulut falan vardi onlar gitmis.photo ve album var sadece. Mi hesaptan girdim senkronize falan nafile. Ne alakadir sence???

Birde sunuda halledelim.
![screenshot_2016-03-11-23-21-58_com android settings](https://cloud.githubusercontent.com/assets/9906622/13716121/bf846956-e7e1-11e5-81ca-2dc71be0c1e2.png)

**Comment by sedat27** [comment]
@raoc999  PArmak olarak yazilmiş

**Comment by raoc999** [comment]
Sedat galeriyi tamamen değiştirmişler, ne deyse çevirilecek dosya baştan aşağı değişti, nedenini bilmiyorum bende sil başatan temiz olsun diye yeniden çevirmeye başladım. PArmak kelimesini bulup değiştireceğim. Bu çeviriye sırf galeri-kamera ilişkisinden dolayı başlamıştım :)

**Comment by aykutyenihan** [comment]
şarj azalınca kilit ekranında **LLütfen** şarj cihazına bağlayın yazıyor.

**Comment by raoc999** [comment]
Aykut düzelttim, gelecek hafta güncellenir.
