### ISSUE TITLE
Sürüm 6.3.17 Hatalar-İstekler vb...

### ISSUE THREAD

**Issue by raoc999** [ingbrzy/MA-XML-8.0-TURKISH#31]
Arkadaşlar; 
Bulunan hataları düzelttim, bazı dosyaları değiştirdim, Galeri ve Kamera dosyalarını yeniden çevirdim. Uzaktan Kumanda dosyasının yaklaşık 300 satırı kaldı. Gelecek hafta, çevrilmemiş veya hatalı yerleri düzeltip, Uzaktan Kumanda Dosyasını bitireceğim ve 6.3.17 de ilave edilen ve çıkartılan yerleri derleyeceğim. Mi4'te farklı dosyaları çevirmeye başlayıp kütüphaneye ekleyeceğim. Gözden kaçan tüm hata-istek ve önerilerinizi bekliyorum. Not: Çeviri Redmi Note 2 içindir, diğer telefonlarda olabilecek farklılıklar geçerli değildir. Çünkü halihazırda diğer çeviri, diğer modeller için kullanılıyor.

6.3.17 Dosyalarındaki değişiklikler:
1. NetworkAssist2 dosyasını yeniden çevireceğim zira %90 değişti.
2. Güvenlik dosyalarında %70-80 arasında ekleme oldu. Güvenlik dosyaları da tekrar baştan aşağı elden geçecek.
3. Genelde toplam olarak tahminim %50/60 arasında çeviri değişikliği oldu. Uzaktan Kumanda dosyasında da büyük değişiklikler var, tam çevirmemiştim ama tekrar elden geçirmek lazım.

**Comment by Kebuter** [comment]
Çalışmalarını takip ediyorum emeğin için gerçekten çok teşşekkür ederim. Benim aklıma takılan bu çeviriler redmi note 3G içinde geçerli mi yoksa hiç etkisi yok mu ?

**Comment by CenkayKESER** [comment]
Çeviri çok iyi olmuş, göze batan İngilizce veya anlamsız kelime kalmamış. Emeği geçen herkesin ellerine sağlık. Sizden ricam ses azaltma ve arttırma tuşlarına basınca çıkan animasyon daki çeviride biraz sadeleştirme te gidelim. Müzik dinliyorken medya ses düzeyi yerine sadece medya veya müzik demek bence yeterli. Ses düzeyi demeye gerek yok. Zaten üstteki simgeden ne olduğu anlaşılıyor.

**Comment by sedat27** [comment]
Orhan tamamdir. Gayet guzel olmus.eline saglik valla. Ufak tefek seyler gorursem yazarim.

**Comment by aykutyenihan** [comment]
hocam parmağı yukarı kaydırınca çıkan yada bildirim alanındaki arama kutusu hep çinçeye. Verileri silince Türkçe oluyor ama yine çinceye dönüyor nasıl oluyorsa. xiaomi.eu da konuştuğum bir ispanyol arkadaş ispanyolca çeviride çinçe bazı kısımların yada harflerin komple silinmesiyle halledildiğini yazmış varmı acaba böyle bir durum. alttan çıkan bar sorun değilde bildirim alanı sürekli orda kapatılamiyorda meret.

**Comment by mavi06** [comment]
Hocam emeklerin için teşekkürler. Hava durumu uygulamasının saatlik hava durumu bölümündeki saatlerde bir hata var sanırım çok ileri ki bir saati gösteriyor

**Comment by CenkayKESER** [comment]
Hocam benim biraz göz gezdirdikten sonra gördüğüm hatalar şu şekilde. Benim cihaz Redmi Note 3 (hennessey).
![screenshot_2016-03-19-19-08-32_com android thememanager](https://cloud.githubusercontent.com/assets/11776567/13900564/4554fa42-ee12-11e5-87ac-660d0a9a1171.png)
![screenshot_2016-03-19-19-09-33_com android settings](https://cloud.githubusercontent.com/assets/11776567/13900565/4554fce0-ee12-11e5-8104-c52d5a589b6a.png)
![screenshot_2016-03-19-19-10-02_com android settings](https://cloud.githubusercontent.com/assets/11776567/13900563/4554e5fc-ee12-11e5-9ee7-bc279020ccce.png)
![screenshot_2016-03-19-19-11-11_com android settings](https://cloud.githubusercontent.com/assets/11776567/13900566/4555b2d4-ee12-11e5-8c8d-d883bc08a60f.png)
![screenshot_2016-03-19-19-11-35_com android settings](https://cloud.githubusercontent.com/assets/11776567/13900567/455661a2-ee12-11e5-860a-f182fa40052e.png)
![screenshot_2016-03-19-19-12-07_com android settings](https://cloud.githubusercontent.com/assets/11776567/13900569/4571f21e-ee12-11e5-9f14-9da35f995905.png)
![screenshot_2016-03-19-19-12-29_com miui cloudservice](https://cloud.githubusercontent.com/assets/11776567/13900570/45722630-ee12-11e5-9d0c-71fc3781ddbe.png)
![screenshot_2016-03-19-19-12-42_com miui cloudservice](https://cloud.githubusercontent.com/assets/11776567/13900568/4571f9f8-ee12-11e5-8167-8f53e09947b4.png)
![screenshot_2016-03-19-19-12-59_com miui gallery](https://cloud.githubusercontent.com/assets/11776567/13900571/4572b190-ee12-11e5-9ae0-899ee41cbc21.png)
![screenshot_2016-03-19-19-13-14_com miui cloudservice](https://cloud.githubusercontent.com/assets/11776567/13900572/457465e4-ee12-11e5-9d91-dfb844f18ee7.png)
![screenshot_2016-03-19-19-13-26_com miui cloudservice](https://cloud.githubusercontent.com/assets/11776567/13900576/458ffe30-ee12-11e5-91d7-da0da5f73216.png)
![screenshot_2016-03-19-19-14-02_com miui cloudservice](https://cloud.githubusercontent.com/assets/11776567/13900573/458e6fde-ee12-11e5-91ee-3446874c538d.png)
![screenshot_2016-03-19-19-16-02_com android contacts](https://cloud.githubusercontent.com/assets/11776567/13900575/458f8252-ee12-11e5-84b6-33980419f26d.png)
![screenshot_2016-03-19-19-16-14_com android contacts](https://cloud.githubusercontent.com/assets/11776567/13900574/458f2532-ee12-11e5-82f4-cc3f0ca5003e.png)
![screenshot_2016-03-19-19-16-24_com android contacts](https://cloud.githubusercontent.com/assets/11776567/13900577/45958d50-ee12-11e5-828d-0f5b20ad3c5a.png)
![screenshot_2016-03-19-19-16-53_com android contacts](https://cloud.githubusercontent.com/assets/11776567/13900581/45af0028-ee12-11e5-9939-c573c4aeb3ee.png)
![screenshot_2016-03-19-19-18-24_com android mms](https://cloud.githubusercontent.com/assets/11776567/13900580/45ac69b2-ee12-11e5-9d05-956d9c0e57bf.png)
![screenshot_2016-03-19-19-20-22_com miui securitycenter](https://cloud.githubusercontent.com/assets/11776567/13900579/45abfd6a-ee12-11e5-9799-0f0854bf434c.png)
![screenshot_2016-03-19-19-21-32_com miui gallery](https://cloud.githubusercontent.com/assets/11776567/13900578/45abedd4-ee12-11e5-92ba-bf34ba12db75.png)
![screenshot_2016-03-19-19-23-15_com android settings](https://cloud.githubusercontent.com/assets/11776567/13900582/45b3aa6a-ee12-11e5-8ade-cedca96ab32c.png)
![screenshot_2016-03-19-19-23-56_com android settings](https://cloud.githubusercontent.com/assets/11776567/13900583/45c8ad98-ee12-11e5-8f89-0799e25c8996.png)
![screenshot_2016-03-19-19-24-07_com android settings](https://cloud.githubusercontent.com/assets/11776567/13900584/45c8e22c-ee12-11e5-97f6-b5a88af5fe84.png)
![screenshot_2016-03-19-19-26-17_com miui securitycenter](https://cloud.githubusercontent.com/assets/11776567/13900585/45c9467c-ee12-11e5-94f7-47de1a2553bb.png)
![screenshot_2016-03-19-19-26-57_com miui powerkeeper](https://cloud.githubusercontent.com/assets/11776567/13900586/45cb8a22-ee12-11e5-9d84-591aee5e566d.png)
![screenshot_2016-03-19-19-27-34_com android settings](https://cloud.githubusercontent.com/assets/11776567/13900587/45d1450c-ee12-11e5-83a4-7d657b47bf9f.png)
![screenshot_2016-03-19-19-28-44_com android settings](https://cloud.githubusercontent.com/assets/11776567/13900588/45e43ac2-ee12-11e5-8974-6077278103bd.png)

1. Temalar uygulamasında bir temaya girince üst kısım "Temalar detayları" olmuş, "Tema detayları" olmalı.
2. "Bağlantı kurulan cihazlar bu adı görür." şeklinde olabilir.
3. "Çevir" yerine "Arama uygulaması" olursa daha hoş olur. Çevir çok farklı anlamlara giidebiliyor.
4. "Toplam" yerine "Toplam boyut" olabilir.
5. "Uygulama" yerine "Uygulama boyutu" olabilir.
6. "SD Kart" yerine "SD Kart Veri Boyutu" olabilir.
7. "Detaylar" yerine "Uygulama izinleri" olmalı.
8. Açıklama yerine "Uygulama izinlerini ayarla" veya "Uygulama izinlerini yönet" dersek daha güzel olur.
9. Açıklama yerine "Uygulama şu anda çalıştığı için önbelleğe alındı." denebilir.
10. "Yedekle & Geri Yükle" şeklinde düzeltilmeli.
11. Açıklamaya "Telefonun ayarlarını Mi Bulut üstünden geri yükle." denebilir veya daha farklı bir şey ler olabiir.
12. Telefonun konumunu bul denebilir.
13. İngilizce kısımlar düzeltilmeli.
14. İngilizce kısımlar düzeltilmeli.
15. Tüm açıklamalar baştan çevirilmeli. Okuyunca bir şey anlaşılmıyor.
16. N büyük olmalı.
17. Metinler sunucudan çakilmiyorsa çevirilmeli.
18. Sadece "Detaylar" dersek daha güzel olabilir.
19. Sahıs yerine Kişi denirse daha güzel olur. Bazı yerlerde şahıs olarak kullanlıyor.
20. Kişi resmi ata demek daha doğru olur. Tayin eder yerine de resim ekle denebilir.
21. Görüntüleme tercihleri olarak güncellenmeli.
22. Depolamaya aktar veya daha mantıklı bir şey olmalı.
23. İngilizce kısımlar düzeltilmeli.
24. SIM 1'e aktar olmalı.
25. Kişi olmuştur demek yeter.
26. Şahıs yerine kişi olmalı.
27. Mİ Mesaj olmalı.
28. Gönderilme durumu olabilir.
29. Gönderilen mesajların durumu olursa daha iyi olur.
30. Komple çevirilmeli.
31. Slayt süresi veya resim geçiş süresi olabilir.
32. Sıfırla olmalı.
33. Basma durumu olabilir.
34. Son uygulamarı göster olabilir.
35. Google uygulamasını başlat olabilir.
36. CPU'da toplam kullanım olabilir.
37. Mobil veride yükleme olmalı.
38. Mobil veride indirme olmalı.
39. Konum olmalı.
40. Uygulamaları kilitle olmalı.
41. İngilizce kısımlar düzeltilmeli.

**Comment by sedat27** [comment]
Orhan kardesim galeride tumunusec olayina bi cozum bulmak lazim. "T.Seç" yapsak olurmu acaba. Yada sedace "Tümü" yapsakta olur gibi
![screenshot_2016-03-20-11-19-05_com miui gallery](https://cloud.githubusercontent.com/assets/9906622/13903664/bbb53ae6-ee8d-11e5-984d-420b73e5ad2f.png)

**Comment by sedat27** [comment]
Hicbirini seçme yerine de "İptal" yada "Vazgeç" yazilabilir.

**Comment by sedat27** [comment]
Ses acip kisarken cikan yerde de "Medya Sesi" ve "Zil Sesi" olarak degisebilir. Zaten duzeyi oldugu belli. Artik o kadar anlasilir herhal:)

**Comment by raoc999** [comment]
Arkadaşlar, tavsiyeleriniz için teşekkürler, bu hafta yoğunum ama derlemeleri bitirip, önerilerinizi yapmaya çalışacağım. İngilizceye dönen yerler, bazı dosyalara yapılan eklerden kaynaklanıyor. Benim hatalarımdan kaynaklanan yerleri düzeltmeye devam edeceğim. Siz yine gördükçe yazın, ben fırsat buldukça tek tek düzeltiyorum. Sadece mantıklı cümlelerde istenilen uyduruk kelimeleri düzeltmiyorum. Faal-Faaliyet yerine etkinlik kullanıyoruz. Yapılan araştırmaya göre bizim ülke okul kitaplarında en fazla 7000 kelime kullanıyor. Japonlarda 70 bin kelime varken beğenmediğimiz Araplar ise 17500 kelime var. Bizimde uyduruk kelimelerden mümkün oldukça kaçmamız lazım :)

**Comment by sedat27** [comment]
Dogru uyduruk kelimelerden kacinmali tabi. Mumkun oldugunca Turkce olmali. Ancak bu isleride biz bulmadik ki adini biz koyalim. Turkce olacak diye garip terimler koymanin anlami yok. Buna dikkat edelim derim ben. Nacizane fikrimdir. Saygilar
Bu arada Mesajlasma yerine Mesajlar olsa daha iyi olmazmi. Eskilerde oldugu gibi??

**Comment by raoc999** [comment]
Arkadaşlar gerekli yerleri ekledim, bir kısım yerleri ise sonra ekleyeceğim, halen uzaktan kumanda çevirisini bitiremedim. bu hafta çok yoğunum. özellikle ağla ilgili satırları güvenlik dosyasına eklemişler bundan dolayı istediğim hızda gidemedim. umarım gelecek hafta düzeltmeye devam ederiz. Özellikle Kişi yerine Şahıs kullanıyorum düzeltmemi istemeyin :)  İmla hatalarını sonra düzelteceğim....
