### ISSUE TITLE
Sürüm 6.3.24 - Hatalar ve İstekler

### ISSUE THREAD

**Issue by raoc999** [ingbrzy/MA-XML-8.0-TURKISH#32]
Arkadaşlar bir önceki sürümde belirtilen hatalar ve isteklerin çoğunu düzelttim. Bu sürümde kontrol edip, dikkatinizi çeken yerleri belirtebilirsiniz. İngilizce kesimleri söylemeyin, onlar yeni sürümden kaynaklanıyor. Ayrıca Güvenlik altında İngilizce bölümlerin çoğunu nerden çekiyor bilmiyorum. Çünkü dosya tamamen Türkçe olmasına rağmen Derin Temizlikte açıklamalar hep İng. ?

**Comment by sedat27** [comment]
![screenshot_2016-03-26-00-57-29_com miui gallery](https://cloud.githubusercontent.com/assets/9906622/14055846/dbc0b252-f2ed-11e5-825e-c0299fb3767f.png)

Orhan merhaba. Fotograf silerken sacma bir yazi var. Ne dediginide anlamadim. Sanirim buluttaki resmide silicem diyor. 
Kamera galeri tam bir oturamadi.
Galeride ayni albumden 10 larca var. Oda ayri bi olay.

**Comment by sedat27** [comment]
![screenshot_2016-03-26-01-00-57_com miui gallery](https://cloud.githubusercontent.com/assets/9906622/14055916/8bd62992-f2ee-11e5-9cfe-de8e0cccde16.png)
![screenshot_2016-03-26-01-00-42_com miui gallery](https://cloud.githubusercontent.com/assets/9906622/14055923/935a5c7e-f2ee-11e5-8cc7-c4679210a2cb.png)
![screenshot_2016-03-26-01-00-27_com miui gallery](https://cloud.githubusercontent.com/assets/9906622/14055930/9c6682c0-f2ee-11e5-9768-2a34e7a930bf.png)
Enterasan hatalar.

**Comment by sedat27** [comment]
Ancak simdi baktim. İngilizce de ayni. Forumda yazdim bakalim. Sende bildirirsen sevinirim.

**Comment by raoc999** [comment]
O çeviri benimde dikkatimi çekti, Silerken gördüm gerçekten çok saçma olmuş :) Düzelteceğim. Diğer konuya gelirsek. Albumlar aynı değil ki, Whatsup ile alakalı olmasın? Rakam bölümleri farklı diye farklı albüm olarak görmesin.

**Comment by sedat27** [comment]
Evet ama resimler ayni icindeki. Whatsapp ile bi sorunu var. Sadece onun klasorleri boyle oluyo. Bi tek bende mi var?

**Comment by aykutyenihan** [comment]
hocam tam olarak hata sayılmaz aslında çeviriyle mi alakalı onu da bilmiyorum ama bu operatör ismi varya durum çubuğunda o küçük harfle değildi büyük daha iyiydi. Acaba çeviride mümkünmü onu eski haline getirmek.

**Comment by Kebuter** [comment]
Şimdi bu çeviri sadece Redmi note 2 için mi yoksa diğer cihazlarada etki ediyor mu ?

**Comment by paclix** [comment]
Sırf şu çeviri hataları yüzünden üye oldum. Neyse sayıyorum:
Sürüm: 6.3.24
1) İndirme yaparken "3 dakika left" yazıyor. İndirme bitince "Download complete"
2) Wifi ya da Bluetooth gibi açma kapama yerlerinde Açık - Kapat yazıyor. Kapat ne yahu? Kapalı yazması gerek.
3) Dosya Gezgini uygulama ismi öyle değil de "Dosyalar" yazsa daha sade olur.
4) Mesajlaşma olan uygulama ismi "Mesajlar" olmalı. 
5) Mesajlaşma uygulaması içinde ki "Yaz" kısmı "Yeni mesaj" olmalı. 

Birkaç tane daha varsa ekran görüntüsü eklemek gerek. Uygun vakitte eklerim.
Ayrıca 6.1.18 sürümden itibaren çeviri acayip saçma olmaya başladı. Bu yüzden bir ay boyunca o sürümü kullandım. Neden o çeviri dosyalarına dönülmüyor? Celaleddin Madencan yazan çeviriler gayet güzeldi.

**Comment by sedat27** [comment]
Simdi evet cevirilerde birebir cevirilerek anlamsiz olan yerler var. Ancak Orhan gercekten gayret ediyor. Biseyler yapmak icin emek veriyor saygi duymakta lazim. 
Ama bu islerde birebir ingilizceden cevirmek olmuyor tabiki. Ceviri yapilirken insanlari taaa tuslu telefon zamanlarindan kalma turkce terimleri var. Ve aksi kabul edilmiyor dogru. Bu nedenle cevirinin yapildigi yere gore turkce degil Turkceye uygun olani koymak lazim. Yani Turkce degil Turkiye'ye ozgu olmali onrmli olan.
Daha guzel olacagini dusunuyorum Orhan kardesim elinden geleni yapiyor ve burada yazanlari hemen uyguluyor sagolsun.selamlar

**Comment by paclix** [comment]
Ben de emekleri için teşekkür ederim ama sırf bu çeviriler yüzünden miuiden soğudum onu da belirtmek istedim

**Comment by haqanguven** [comment]
Bir sonraki sürümde yeni Türkçe çeviri sizlerle. . .

**Comment by MIUITurkey** [comment]
Yeni güncelleme tamamen MIUI Türkiye tarafından eklenecek arkadaşlar doğru terimler ile uzun süredir kullanılan bir çeviri zaten hatasız olması ümidi ile tabi her zaman ilk başlangıçta küçük sorunlar olabilir bu da zamanla giderilecektir.

**Comment by CenkayKESER** [comment]
Ben çeviriden memnundum, anlamsız kısımlar vardı ama bunu çevirmen arkadaşa iletince düzeltiyordu. Bu zamana kadar ceviriye çok ciddi katkıları oldu, kendisine emeklerinden ötürü teşekkür ediyorum. Yeni cevirilen dosyalardaki dil fazla resmi geldi, cuma gunu yeni sürüm yayınlanında incelemek gerek.

**Comment by raoc999** [comment]
Arkadaşlar, söylenilen hataları düzelttim, MUIU Türkiye sitesi kendi çevirilerini eklemişler. Bu hafta ki derlemede bu yazılımı test edelim. Hatalı ve tavsiye edeceğiniz yerleri açacağımız yeni başlıkta belirtelim. Arkadaşlar düzeltirler, gerekirse onlarla iletişime geçip hep beraber tekrar son bir elden geçiririz. Bu proje hepimizin ortak malı... Şimdiye kadar başta Cenkay, Sedat, Ayhan, Hasan ve diğer arkaşalara yaptıkları katkılardan dolayı teşekkür ediyorum. Ben sadece yazmış siz test ve çeviri yapmıştınız. İşin gerçek tarafı bu :)
