### ISSUE TITLE
6.3.31 & Hatalr ve İstekler

### ISSUE THREAD

**Issue by raoc999** [ingbrzy/MA-XML-8.0-TURKISH#34]
Arkadaşlar; 6.3.31 sürümünde MUIU Türkiye ekibi tarafından çevrilen Türkçe dil dosyaları yüklendi. Test edip, istek ve önerileri yazalım.

**Comment by CenkayKESER** [comment]
1. Bildirim ekranında döndürme sabitleme özelliği sensör olarak görünüyor, bu düzenlenmeli.
2. Bildirim ekranında uçak modu özelliği uçak olarak görünüyor, uçak modu olarak düzenlenmeli.
3. Bildirim ekranında ekran resmi yerine ekran alıntısı olabilir.
4. Bildirim ekranında uyku modu sadece uyku olarak görünüyor, uyku modu olarak düzenlenmeli.
5. Bildirim ekranında gps küçük olarak yazılmış. Bu tür kısaltmalar büyük olarak yazılırsa daha hoş oluyor.
6. Bildirim ekranında tuşları kilitle özelliği tuşları kapat olmuş, tuşları kilitle olarak düzenlenmeli.
İlk olarak gördüğüm dikkat çekici şeyler bunlar. Onun dışında çeviri çok iyi olmuş. Uzun süre resmi çeviri ile Mi4 kullanmış birisi olarak resmi çeviriyi çok beğeniyordum, bu çeviride resmi çeviri kadar kaliteli. Resmi çeviri sizin çeviriniz olduğu için belki resmi çeviriyi direkt olarak bu projeye aktarırsanız daha güzel olabilir.

**Comment by haqanguven** [comment]
Önerileriniz düzeltildi. Ekran resmi hala aynıdır. Ona kişisel bakmayalım

**Comment by MIUITurkey** [comment]
Can hocam sendeki çeviriyi ekler misin hakan onu da alıp margin ile
karşılaştırsın
1 Nis 2016 ÖS 8:15 tarihinde "Hakan" <notifications@github.com> yazdı:

**Comment by CenkayKESER** [comment]
7. Ayarlar --> Wi-fi --> Herhangi bir kayıtlı wi-fi ağının ayarlarına girince Mobile Hotspot diye ingilizce kalan kısım var.
8. Ayarlar --> Sound & vibration şeklinde ingilizce kalan kısımlar mevcut.
9. Ayarlar --> Uyku bölümü tamamen İngilizce kalmış.
10. Ayarlar --> Diğer --> Gizlilik --> Telefonu şifreleme bölümü tamamen ingilizce kalmış.
11. Ayarlar --> Diğer --> Gizlilik --> Notification Acces bölümü ingilizce kalmış.
12. Ayarlar --> Diğer --> Gizlilik --> Advanced kısmı tamamen ingilizce kalmış.
13. Ayarlar --> Diğer --> Dil ve Giriş --> Voice input bölümü tamamen ingilizce kalmış.
14. Ayarlar --> Diğer --> Pil ve Performans --> Pil kullanımı yukarıdaki saat ikonuna tıklayınca gelen ekranda bölümde Mobile network signal şeklinde ingilizce yer kalmış.
15. Ayarlar --> Diğer --> Depolama kısmında USB bellek bölümü İngilizce kalmış.
16. Ayarlar --> Diğer --> Erişilebilirlik bölümünde yer alan display kısmı tamamen ingilizce kalmış.

**Comment by MIUITurkey** [comment]
Pardon can dedim orhan olacaktı
1 Nis 2016 ÖS 9:11 tarihinde "CenkayKESER" <notifications@github.com> yazdı:

**Comment by haqanguven** [comment]
CenkayKESER eğer telefonun mi4c ise onun için özel olarak ayarlar uygulamasını Türkçeleştiriyorum. Bu hafta bana o bölümden bildirme yapmayın ki boşuna yorulmuş olmazsınız, çünkü haftaya mi4c için dil dosyası yenilenecek

**Comment by CenkayKESER** [comment]
Benim cihaz redmi note 3.

**Comment by sedat27** [comment]
![screenshot_2016-04-02-10-40-32_com miui yellowpage](https://cloud.githubusercontent.com/assets/9906622/14225111/8e2319fe-f8bf-11e5-8b3b-9f87fc1b4041.png)
Su kismida bi degistirsek

**Comment by haqanguven** [comment]
Hangi uygulama bu

**Comment by sedat27** [comment]
@haqanguven telefon uygulamasi. Eskiden raporla olarak gecen kelime simdi Spam olmus. Raporla daha iyiydi sanki

**Comment by sedat27** [comment]
![screenshot_2016-04-02-17-21-44_com duokan phone remotecontroller](https://cloud.githubusercontent.com/assets/9906622/14226876/8be3be04-f8f7-11e5-82b5-47793841ab68.png)
Kumandada kumanda kaydettikten sonra menude "Ana ekrana ekle" olmasi gerek. Çince kalmis

**Comment by sedat27** [comment]
@haqanguven bu ekrandaki Spam
![screenshot_2016-04-02-17-24-22_com android contacts](https://cloud.githubusercontent.com/assets/9906622/14226882/cdb31ac8-f8f7-11e5-844b-a1990a0f2dd0.png)

**Comment by haqanguven** [comment]
Düzeltildi

**Comment by sedat27** [comment]
@haqanguven tesekkur. Super hız

**Comment by sedat27** [comment]
Simdi gordum burasida var.
![screenshot_2016-04-02-22-00-29_com android settings](https://cloud.githubusercontent.com/assets/9906622/14228464/60173f90-f91e-11e5-8818-77abb934052d.png)

**Comment by sedat27** [comment]
Ayrica "gelismis" olmamali tum telefonlarda "Gelistirici senecekleri"dir. Turkcr de standart oldu artik
Ayrica icinde de ingilizce yerler var.

**Comment by sedat27** [comment]
![screenshot_2016-04-02-22-03-04_com android settings](https://cloud.githubusercontent.com/assets/9906622/14228488/ee35a8e8-f91e-11e5-8649-f6ba2c6e733a.png)

**Comment by sedat27** [comment]
![screenshot_2016-04-02-22-05-14_com android settings](https://cloud.githubusercontent.com/assets/9906622/14228490/000413fc-f91f-11e5-8ed7-944bf6860a98.png)

**Comment by haqanguven** [comment]
O bölüm bu hafta tam türkçe olacak

**Comment by mavi06** [comment]
Hava durumu uygulamasındaki saatlik hava durumu saatler değişince 1 saat geriden geliyo düzeltebilirmisiniz acaba?

**Comment by sedat27** [comment]
Dosyalarda zip cikartirken klasor secince. Buraya cikart yerine cikartmak istiyor musunuz? Yaziyor.
"Buraya çıkart" yeterli
![screenshot_2016-04-04-01-32-32_com android fileexplorer](https://cloud.githubusercontent.com/assets/9906622/14235386/5d5f0f48-fa05-11e5-8ce5-535cd4a8f780.png)

**Comment by sedat27** [comment]
@raoc999 @haqanguven 
Fotoğraflar ayarlarına girin-Çöp kutusunu seçin. Tamamı çince.

**Comment by haqanguven** [comment]
Dosya yöneticisi düzeltildi. Galerideki dediğin bölüm bende gözükmüyor. telefondan telefona fark olabilir

**Comment by raoc999** [comment]
Hakan kardeşim çeviri ve düzeltmeleri yapıyor. Bende geriden gelip imla vb.
kalan yerleri düzeltiyorum. Bir elin nesi var iki elin sesi var.

recep.ali.orhan.cakmak

2016-04-04 12:49 GMT+03:00 Hakan <notifications@github.com>:

**Comment by haqanguven** [comment]
Ayarlar eksik satırlar eklendi. Çoğu eklenen satırlar çevrildi sadece 200'e yakın çeviri kaldı. onları da hasan hoca ile tamamlayacağız. cuma günü olan güncellemedede ayarlar için ince düzenlemeye gideceğiz. Yalnız anında konuşabileceğimiz ortam olmalı ki bana şurayı şöyle değiştir dediğiniz zaman hemen değiştirebileyim

**Comment by sedat27** [comment]
@haqanguven dedigim bolum burasi. Telefon hennesy. Kodlarda mutlaka vardir. Bu ceviriler tum telefonlar icin degilmi?
![screenshot_2016-04-04-16-49-45_com miui gallery](https://cloud.githubusercontent.com/assets/9906622/14250043/5614cf0e-fa85-11e5-9d68-cd4caf58edf4.png)

**Comment by sedat27** [comment]
![screenshot_2016-04-04-16-52-05_com miui gallery](https://cloud.githubusercontent.com/assets/9906622/14250107/97af6b4a-fa85-11e5-902f-5b53398632f4.png)
Boyle geliyo.resimler sonra aciliyor ama yazilar cince

**Comment by raoc999** [comment]
Evet bu durumda WhatsUp kaçınılmaz oluyor.  Bir de Hakan şöyle bir durum
var. Örnek: name="backup_file_error" diye satırın İng. Yedekleme başarısız
iken "Yedekleme ile ilgili bir sorun oluştu" gibi geniş cümleler var. Diğer
modellerde hep aynı. Burada siz mantıklı cümleler mi oluşturmaya
çalışıyorsunuz veya sizdeki kaynak dosya mı farklı. Yedek dosyasını
düzenlemeye çalışıyorum. Çok karışık- yani Merge ile benim ve önceki çeviri
hiç eşleşmiyor. Siz kanyak olarak neyi kullanıyorsunuz. Ve şu anki
çevirinde 6.3.31 dahil mi?

recep.ali.orhan.cakmak

4 Nisan 2016 16:40 tarihinde Hakan <notifications@github.com> yazdı:

**Comment by haqanguven** [comment]
hmm orayı internet üzerinden alıyor galiba. İngilizce bile değil o bölüm. Bana galerinin apk'sini atar mısın bir kontrol edeyim
Ben kontrolü notepad ile yapıyorum. Daha geniş görmeme yardımcı oluyor. Ayrıca resmi çeviride önceden böyle çevrilmiş, crowdin otomatik olarak gösteriyor bize ve o dosyalara denk gelmediğimiz sürece değiştirmiyoruz. eskiden bir çok kişi çevirmeye kalkmış miui'i

**Comment by CenkayKESER** [comment]
Bir whatsapp grubu kurarsak geri bildirimleri hızlı ve görsel olarak yapabiliriz. Uygun görürseniz telefon numaramı mail atabilirim.

**Comment by haqanguven** [comment]
yada bu konu üzerinden devam edelim. Oradan bana geri bildirim yapılıyor anında

http://forum.miuiturkiye.net/konu/xiaomi-eu-turkce-ceviri.4726/

**Comment by MIUITurkey** [comment]
Bence WhatsApp iyi gibi
4 Nis 2016 17:09 tarihinde "Hakan" <notifications@github.com> yazdı:

**Comment by haqanguven** [comment]
Nasıl isterseniz hocam

**Comment by 4fareis** [comment]
Ayarlar > Sound & Vibration

Ayarlar > Uyku > Do not Disturb > Always allow disturbances - Only allow exceptions - Silent all disturbances

Ayarlar > Diğer > Gizlilik > Apps with usage access

Ayarlar > Diğer > Dil ve Giriş > Voice input

Ayarlar > Diğer > Depolama > Usb Bellek > Mount USB storage

Ayarlar > Diğer > Erişebilirlik > Sistem > High contrast

Ayarlar > Diğer > Erişebilirlik > Display > Colour inversion

Ayarlar > Diğer > Erişebilirlik > Display > Colour correction

ingilizce olan yerleri düzeltebiliriz gözüme çarpan yerleri yazarım çalışmalarınızda başarılar diliyorum

**Comment by haqanguven** [comment]
Onlar bu hafta Türkçe olacak gelecektir

**Comment by sedat27** [comment]
@MIUITurkey @haqanguven
 whatsappa dalıp burada yazılanları unutmayacağınızı umuyorum:) bakarsınız yani..

**Comment by haqanguven** [comment]
Her tarafa bakıyoruz :)

**Comment by sedat27** [comment]
telefon ediliyor. Karşı taraf meşgule verince .LİNE BUSY yazıyor. Bilginize @haqanguven @raoc999

**Comment by haqanguven** [comment]
Bu hafta dil dosyasında çok değişiklik oldu. Bu haftadan sonra geri bildirim yapın, ona göre ne eksik onları da tamamlarız.
