### ISSUE TITLE
Sürüm: 6.4.7 Hatalar ve İstekler

### ISSUE THREAD

**Issue by raoc999** [ingbrzy/MA-XML-8.0-TURKISH#36]
Arkadaşlar Hakan ve Hasan arkadaşımızın güncel çevirisinin yeraldığı 6.4.7 yayınlandı. Hataları, istekleri ve önerileri buraya veya MUIU Türkiye sitesine yazalım ki bir sonraki sürümde düzeltsinler. Emeği geçenlere teşekkürler.

**Comment by MIUITurkey** [comment]
Bu arada redmi de kamera sorunu devam ediyor mu?
8 Nis 2016 09:04 tarihinde "recep.ali.orhan.cakmak" <
notifications@github.com> yazdı:

**Comment by raoc999** [comment]
"Ön ek" kelimesi birleşik olmalı, "Arka plan" birleşik olmalı, "öge" =" "öğe", "Sesli uzakta mesajınız diğer tüm aramalarınızda meşgul sesi olarak da kullanılacak" = Biraz mantıklı hale gelmesi lazım, Smsc  büyük harfli olmalı, İmei büyük harfli ama İ noktasız, Iccıd büyük harfli, Imsı büyük harfli, Kök erişimi yerine Root Erişimi dersek daha iyi olur artık Root deyince herkes biliyor, dilimize yerleşti. Backup dosyasında çevrilmemiş satırlar var. Wifi = Wi-Fi, xiaomi = Xiaomi, Başlantma  yanlış, Senkronize ediliyor = Eşitleniyor, Alan taraf=Alıcı, Gönderen taraf=Gönderici, Gönderme veri boyutu hesaplanıyor=Gönderilen veri boyutu...., Kaynaşmış konum? ne demek!!!

**Comment by raoc999** [comment]
Hasan Kamera sorununu arkadaşlar söylerler ben güncel Romu yüklemedim sadece ilk üç-4 dosyayın başına ortasına sonuna baktım. Hatalar ne durumda diye. Tam oturana kadar bekliyeceğim.Bu hafta baya ekleme olmuş, artık bundan sonra  tüm hataları düzeltirseniz çok güzel olacak. Romu indirip deneyeceğim. Bırazdan söylerim

**Comment by MIUITurkey** [comment]
Tamam hocam
8 Nis 2016 09:22 tarihinde "recep.ali.orhan.cakmak" <
notifications@github.com> yazdı:

**Comment by haqanguven** [comment]
Böyle geri bildirimle ben bir şey bulamam. Ben kullanmıyorum bu yazılımı. Sitede geri bildirimle nasıl geri bildirim yapılacağını belirttim. Aratsam bile zar zor bulurum

Kamera sorunu çeviri kaynaklı değil. İngilizce ve çince dışında çalışmıyor. Kimilerinde çalışıyor. Bunun resmi olarak düzeltilmesi gerek

**Comment by haqanguven** [comment]
Ayrıca merge ile kontrol etmeye gerek yok. Ben hem apk'i toplayıp toplamada hata var mı yok mu diye bakıyorum. hata olsa toplanmazdı. Sadece kullanın ve gördüğünüz çeviri hatalarını belirtmeniz yeterli olacaktır. Bende dil dosyasında düzelteceğim

**Comment by raoc999** [comment]
Hakan notepad+ ta tüm XML dosyaları bir seferde açarsan "" işaretleri içindeki dosyaları aratıp bir anda hepsini değiştirebilirsin. Hataları Backup, AuthManager yerinden söyledim. Birde satırları M. güzelce sıraladı aman değiştirmeyin. Yoksa Merge eşleştirmiyordu. Dediğim hatalar çeviri ile ilgi burdan çıkacak sonuç bir ara dosyaları tek tek elden geçireceksin.

**Comment by raoc999** [comment]
Kamera ile ilgili, Redmi Note 2 için diyeyim, 6.3.24'te çalışıyor. Çalışmayanlar için ise bunun Hakan'la alakası yok, bende çevirdiğimde arada orj. çevrilmemiş dosyaları koymuştum yine düzelmemişti. Daha sonra buradaki yönetici Frame... dosyasında boyutuyla alakalı kaynaklanan bir problemi giderdiğinde düzelmişti.

**Comment by haqanguven** [comment]
Ben zaten tek tek dil dosyasında aramıyorum ama siz dil dosyasında nasılsa öyle belirtmez iseniz arama yaptığım da çıkmayacaktır. Benim istediğim tam yazılışını bana yazmanız

**Comment by raoc999** [comment]
Bende tam yazılışını kopyala-yapıştır yaptım. Bende çıkıyor, sende neden çıkmıyor?! Çıkmıyorsa düzeltmişsindir :)

**Comment by haqanguven** [comment]
Senin yazdıklarını bakmadım henüz. Arka plan Türkçede birleşik değil. ögeleri bende öğe olarak biliyorum ama araştırma yaptığımda öge olarak kullanılmış. Onu tartışmak gerek. Diğerlerine bakıcaz

**Comment by raoc999** [comment]
Birda Hakan Takma ad yerine Rumuz kullanabilirsin, Arka plan teknik çeviridir Arkaplan Duvar Kağıdı gibi bileşik kullanılıyor, siz bilirsiniz. nasıl isterseniz?

**Comment by haqanguven** [comment]
Tamam onu değiştiririm. Diğerlerini tartışarak sonuca varırız. En çok hangisi istenilirse onu yaparız.

**Comment by sedat27** [comment]
![screenshot_2016-04-08-10-14-52_com android settings](https://cloud.githubusercontent.com/assets/9906622/14376542/cbb8367a-fd72-11e5-9872-71260553c09e.png)
Bu duzeltilmisti.Orhan bunu halletmisti. Gene gitmis. Kac kisi ceviri yapiyor. Ve birbirlerinin yaptigini neden bozuyor. Ayni hatalar donup duruyor. Bunun sonu gelmez

**Comment by sedat27** [comment]
orhan çeviriyordu. hakan oldu. hasan oldu.
tamam herkes emek veriyor. Allah razı olsun. ama bir ekip olmalı herkes belli dosyaları çevirmeli. ondan sorumlu olmalı. kim ne çeviriyor ne yapıyor bilinmiyor. böyle kısır döngüye girer aynı şeyler döner durur. orhan çeviri yapıyordu şimdi hataları kendi yazıyor. artık yapmıyormu? kim ne yapıyor ve ne yapacak bir aydınlatalım lütfen.
hazır çevrilmiş dosyalar neden tekrar çeviriliyor?

**Comment by sedat27** [comment]
https://github.com/ingbrzy/MA-XML-7.0-TURKISH/issues/26#issuecomment-189833209

**Comment by haqanguven** [comment]
Ben haftalardır ayarlardan bana geri bildirim yapmayın, baştan çeviriyoruz kaç kez dedim. Sonra o yaptı bu bozdu diyorsunuz. Bu hafta ayarlara ince olarak el atacağız. her şey bir anda olup bitmiyor, bir şeylerin tam olması için zamana ihtiyaç vardır. Geri bildirimini yap düzeltiriz

Baştan çeviriyoruz çünkü ingilizce dosyaları ile satırlar aynı olmalı, karışık değil. Ben her güncellemede tek te dil dosyasını kontrol ediyorum ve hangi satır eksik Türkçe dil dosyasına ekliyorum. siz üst kısıma bakıyorsunuz ama alt kısımda neler dönüyor bunu yapan daha iyi bilir. O yüzden sabırlı olun ve ortaya güzel bir dil dosyası hazırlayalım

**Comment by sedat27** [comment]
@haqanguven hakan haftalardan beri orhanla yazışıyoruz. ve çeviri yapıyor. hiç yazdığını görmedim.yazdıysanda orhanın haberi yok bundan. yazıyoruz düzeltiyor. işte bende bunu diyorum kim ne yapıyor. sorumlu kim belli değil. Orhanda ilk başta baştan başlıyorum hepsini çeviriyorum dedi.
Son olarak kim yapıyor bu işi kimi dinlicez?

**Comment by sedat27** [comment]
bunlarda gördüklerim
Cepte uyandırmayı engelle--  yerine  --Cepte uyanmayı engelle

Daima bozukluklara izin ver-  yerine  -Rahatsız etme modu kapalı
Sadece istisnalar izin ver-  yerine  -İstisnalara izin ver
Tüm bozukluklar sessiz-  yerine   -Rahatsız etme modu açık

Tuşlar-Seçenekler---yerine--Sol tuş işlevi

Gelişmiş---yerine--- Geliştiri Seçenekleri

Galeride üstte çıkan yazı " reduce photo size on internal storage to save 1.71gb---yerine--Fotoğraf kayıt kalitesini düşürerek 1.7gb yer açın.

arama ayarları-Arama kaydedici --yerine-- Ses kaydı.

Kişiler ayarları- Gelişmiş görünüm --yerine-- Detaylı görünüm

Mesaj ayarları-Mesaj durumu--yerine-- İletim raporu.

Mesaj ayarları-gelişmiş ayarlar-İtme mesajlarına izin ver--yerine--Anlık mesajlara izin ver.

Mail-ayarlar-E-posta akışı---yerine--- Sildikten sonra.

Kamera ayarları- Video- Video kalitesi-Tam Hd--yerine-- Full HD (Yok artık:) )

**Comment by haqanguven** [comment]
Geri bildirim için teşekkürler, düzelteceğiz

**Comment by MIUITurkey** [comment]
Orhan hocam WhatsApp dan yazar misin
5547613359
8 Nis 2016 ÖÖ 11:03 tarihinde "Hakan" <notifications@github.com> yazdı:

**Comment by raoc999** [comment]
Arkadaşlar olayı şöyle aydınlatayım. Normalde ben Hermes tabanlı çeviri yapıyordum. Bir sabah yaptıklarımın tamamının silindiğini gördüm. Hakan arkadaşımız kendi çevirisini eklemiş. Onların çevirisinin bir kısımını düzelttim ama GitHub'da yeniden upload yapılınca onlarda gitti. Merge ile eski, benim ve ingilizce ile karşılaştırmak istemiştim fakat satırlar çok karıştı. Bende geri plana çekildim. Arkadaşları sık boğaz yapmak istemiyorum. İşlerinini bitirsinler. Üstelik satırlarda yönetici tarafından düzenlendi. Eğer Hasan ve Hakan arkadaşlar isterlerse Dosyaları düzenleyip, onlara atacağım ve oradan devam etsinler. En azından biz Sedat, Cenkay, Ayhan gibi arkadaşların bildirimleriyle bir yere kadar gelmiştik. Yeniden Amerikayı sürekli keşfetmeye gerek yok. Zaten çeviriyi düzeltmek için yola çıkmıştık. Değişen birşey olmadı. Buna rağmen arkadaşlar tüm Xiaomi ürünlerini çevirdiler ki bu takdire şayan. Burada tek yapılacak şey şu, çeviri Hakan ve Hasan kardeşlerimiz tarafından yapılacak, ben ve -sitedeki MUIU ve buradaki- arkadaşlar tarafından hatalar ve ifadeler düzeltilecek. Yani Hakan kardeşim bir yerde hata yaptı ise üzerinde durmayacak, çeviri yapan oturup şunun bunun dediklerini düzeltmeye çalışırsa çok zaman kaybediyor. İçimizden biri ise sadece derlemeleri ekleyecek.... WhatsApp konusunda şunu diyeyim. Ben yayıncı-dağıtımcı firmasındayım. Eğer Whatsapp açarsam öğretmenler, firmalar, eş dost derken iş yapamam. 3 tane işim var facebook bile kullanmıyorum...

**Comment by sedat27** [comment]
yani çeviriyi yapanlar Hakan ve hasan. ok.
Ancak senin geldiğin nokta gayet iyiydi.neredeyse hiç sıkıntı kalmamıştı.
şimdi başa döndük demekki
Ordan devam etsek olmuyormuydu acaba? sadece meraktan soruyorum. @raoc999

**Comment by MIUITurkey** [comment]
Bence orhan sen geri yükle çeviriyi ordan devam edelim
8 Nis 2016 14:19 tarihinde "sedat27" <notifications@github.com> yazdı:

**Comment by sedat27** [comment]
@MIUITurkey aynen. çünkü aksi durumda son 5-6 haftanın tüm düzeltmeleri ile baştan uğraşacaksınız. oda yorucu olur. sizin için diyorum.yoksa ben tekrar yazarım hataları.
ama aklın yolu bir.

**Comment by MIUITurkey** [comment]
Aklın yolu bir mantıklıdır bence de
Daha sonrada eksik ve hataları yerleri düzeltmeye devam ederiz.
8 Nis 2016 14:21 tarihinde "sedat27" <notifications@github.com> yazdı:

**Comment by raoc999** [comment]
Arkadaşlar ben size daha iyi birşey önereyim. Hakan ve Hasan arkadaşlarımız bu haftaki 6.4.7 sürümüne ait yeni satırları eklesinler, çıkartılan yerleri silsinler ve mail mailine atsınlar. Hatta isterlerse A harfinden olanları atsınlar, bende karşılaştırma yapıp, düzelteyim, geri atayım. Ondan sonra uploda etsinler. Ben 6.3.31 e kadar tüm derlemeleri yaptım. Veya bana telefonunuzu veri sizi arıyayım.

**Comment by sedat27** [comment]
@MIUITurkey @raoc999 Orhan sen dosyalarını gönder ordan devam etsinler. böylece eski hatalarla kimse ugrasmamış olur. boşuna zaman harcanmaz. sonrada yeni düzeltmelere bakarız. devam ederiz.
ama kurban olayım türkçe olacak diyede abartmayalaım. daha önce orhana dedim.TAM HD gibi olmasın:)
KODU DIŞI: zamanında internet ilk geldi. itiraz edenler oldu türkçe değil dilimize yabancı kelime sokuyorlar falan.bir köşe yazarı dediki "interneti sen bulaydında adını Mahmut koyaydın". bu mantıkta ilerleyelim. bazı şeyler orjinal kalmalı.saygılar

**Comment by sedat27** [comment]
**AYRICA:** Bu arada bu kadar yazdık ettik. kendimden bahsedeyim.
39 yaşındayım.İstanbul dayım.ticaret yapıyorum.web tasarımla da uğraşıyorum.
teknoloji ve arabalar en büyük hevesim. apple hastalığımdan sonra, şimdide xiaomi tek oldu.
yarışmacılara başarılar

**Comment by raoc999** [comment]
Sedat biliyorsun ben Türkçe olsun taraftarıyım ama bazı kalıplar Türkçeye yerleşti bunları atamayız. Ama birşeylerde uyduramayız. Şimdi Otomatik yerine saçma Bilkent sözlüğünü kullanamayız. Ama bizde Usul varken metod kullanmakta aşağılık bir duygu. Dikkat edersen İnternet Paylaşımı yerine ben Hotspot kulanıyordum. Bildirim ekranına İnternet Paylaşımı yazında yarısı çıkmıyor. Dosya Gezgini çıkmıyor. Ama ittirme mesajlar ne? Yedekleme yerine Yedekle olmalı, bir emir amcak cümle içinde isme döner. Cümle sonunda isim olmaz, istisna haller olabilir. Yayıncıyız az buçuk biliyoruz ama benide Şahıs diyor diye eleştirebilirsin. Kişi ne? kökü yok. Uyduruk birşey ama kullanıyoruz. 
Ne deyse yaşıt sayılırız. 41'de ben. İstanbul'da İtalyan Hertz'de idim. Şimdi Ankarada yayın işindeyim. Aynı şeyden bende müzdaribim iphone'dan sonra Xiaomi'ye geçtim. Ama bir realite var Kırık Iphone başka idi. Android çok cılız. Sırf yazılımı düzeltmeyi bundan dolayı istiyorum, eğer böyle çorba olacaksa direkt Meizu'ya geçeceğim ki onun yazılımı daha berbat. Gerçi İng. ile sorunum yok. Ama Türkçe olsun...

**Comment by raoc999** [comment]
Bir arkadaş 7.2.3 sürümü kullandığını ve kamera sorunun devam ettiğinden bahsederek sitem ediyor. O arkadaş sorunun stabil sürümde, çözülen kamera sorunun ise developer sürümünde olduğunu, sürüm numaralarının farklı olduğunu dikkate alsın lütfen!?

**Comment by sedat27** [comment]
@raoc999 orhan aynı fikirdeyim.Ancak method yerine usul kullanmak bu nokta da yanlış olur. Bazı kelimeler teknik kullanımlarda değiştirilmemeli. Usul yerine yöntem olabilir ancak
demek istediğim şu. Samsung,htc,lg kullanan biri bu telefonu aldığında genel geçer bazı terimleri tanıyabilmeli. garipsememeli ,gülmemeli.
hotspot  İ.Paylaşım olarak yazılabilir.
yani bilgisayardaki RAM kelimesini "Rasgele erişim belleği" olarak yazarsanız veya
CPU için "Kontrol işlemcisi birimi"
derseniz kimse anlamaz.
bazen telefonu alıp kurcalayan oluyo neymiş diye. böyle bir yazı görünce "Çin malı işte nolcak" diyo. deli oluyorum. bunu bizimkiler çevirdi desem daha kötü

**Comment by sedat27** [comment]
daha Mi5 gelecek birde onla uğraşıcaz:)

**Comment by raoc999** [comment]
(Hakan ve Hasan) Arkadaşlar sizin çevirdiğiniz dosyaları karşılaştırıp yeniden upload edeyim ve siz upload ettiğim dosyalardan devam edin olur mu? Böylece hatalarla sürüekli uğraşmamış olursunuz. Sizin gözünüzden kaçanları düzeltmiş olurum Hemde burada telefonu inceleyip hataları bulan arkadaşların tavsiyeleri de yerine gelmiş olur. Burada tavsiye yazan arkadaşların çoğunda Xiaomi'nin farklı model ürünleri var. Bende Redmi Note 2 var, bazen bir arkadaş bir hatadan bahsediyor, veya bir tavsiyede bulunuyor... Bu çok önemli. Çeviri mutlaka birden fazla üründe denenmeli. Böyle bir imkan ancak bir toplulukta oluyor. Ya Hasan kardeşim MUIU Türkiye sitesinde özel bir bölüm açacak. Bizlerde üyelik isimlerimizi vereceğiz, bize yetki verecek, o bölümü sadece biz kullanacağız. Gerekli yazıları, eleştirileri yapacağız ve tartışacağız. MUIU Türkiye sitesine bir faydamız dokunacak. O bölüme gelip AR-GE ekibine katılacak arkadaşların Xiaomi telefonlarının olmasını istiyeceğiz. Böylece haftalık yazılımı değerlendirmiş olacaklar. Eğer güzel organize olursak 2-3 hafta sonra ben iddia ediyorum ki süper bir iş ortaya çıkar. Sadece kim ne yapacağını bilsin yeter. Birden fazla kişinin katıldığı işlerde mutlaka liderlik lazım. Kimse kabul etmiyorsa ben söyliyeyim bari :) Hakan ve Hasan kardeşim çeviri, Hasan kardeşim MUIU altyapısını hazırlasın ve organizasyonu belirlesin. Ben düzeltmeleri Sedat, Cenkay, Ayhan gibi kardeşlerimle halledeyim. Burada tek sorun var. O da upload kimse etmeyecek, dosyalar ikide bir bozulmamalı. Katkıda bulunanlar kısmında ise MUIU Türkiye ve sitenin adresi yazacak.... Bu iş gönül işi... Katkıda bulunan arkadaşların isimlerini Hasan siteye yazar zaten. Dediğim gibi eğer güzelce herkes üstüne düşeni yaparsa 3 hafta sonra ortada süper bir iş çıkar, sonra FlymeOS'u çeviririz :)) Şimdi top Hasan veHakan'da

**Comment by sedat27** [comment]
@raoc999 
Orhan kardeşime aynen katılıyorum.
Bir ekip olarak özel bir bölümde her cihazdan olacak şekilde birini bulup çevirenler ve test ekibi olarak yazabiliriz. burasıda olur aslında ama foruma katkı olsun.forum sahibi biri olarak severim bu işleri

zamanında Miroslav a aynı şeyi söyledim xiaomi.eu da.test etmiyormusunuz dosyaları diye. oda bana kaç tane telefon var nasıl edelim dedi. dedim elinde yüzlerce insan var forumda onlardan oluştur dedim. kaldı öyle.

**Comment by MIUITurkey** [comment]
Aynen katılıyorum sana orhan sitede zaten böyle bir bölüm var ekip
liderleri yaparsak bir iki kişi organizasyon güzel  olur ve dediğiniz gibi
çeviri çok iyi düzeyde olacaktır.

Orhanın yaptığı çeviriyi yüklemesi karşılaştırma ve düzenleme işi en
mantıklısı şuan için
8 Nis 2016 ÖS 5:20 tarihinde "recep.ali.orhan.cakmak" <
notifications@github.com> yazdı:

**Comment by aykutyenihan** [comment]
ayhan arkadaş benmiyim diyorum ikide bir? bir iki öneri yaptık ama acaba benmiyim :) son sürümü yükledim genel olarak iyi ama açıkçası ben daha büyük beklenti içindeydim heralde. Belirttiğim hataların aynen durması biraz kötü oldu diyelim. ben mi4c kullanıyorum eğer bir görev dağılımı yapılacaksa bu cihazın en ücra yerlerine girer çıkar denerim her hafta ve geri dönüş yaparım.

**Comment by raoc999** [comment]
Arkadaşlar, tüm diğer modellerle karşılaştırma yapıp, düzeltip ekleme yapıyorum. Hasan ve Hakanın çevirleri ,benim ve önceki çevirileri değerlendirerek gidiyorum. 6.4.7'deki eklentileride, bazı eklemememiz gereken satırları da çıkartıyorum. Şimdilik özellikle Hasan ve Hakan kardeşimden kesinlikle herhangi bir dosya upload etmemelerini istirham ediyorum. İnş. yarın MUIU sitesinde nelerin bittiği hakkında ve görev dağılımı hakkında bir çalışma yaparız. Bir satır bile düzelten arkadaşlar, öneri yapanlar önemli, yeterki onlarda da Xiaomi telefon bulunsun. Özellikle Kullanıcı sözleşmeleri farklı satırlardan veri çekip bir araya getiriyor, bu sefer devrik cümle oluyor. Biz kendi telefonumuzda kusur görmüyor olabiliriz ama öteki modellerde farklı olabilir. A harfiyle ilgili tüm dosyaları ekledim. Ayrıca ANT HAL Hizmetini'de ekledim. ANT'ı nasıl kısaltabiliriz veya bilenler var mı? Bu teknoloji yeni çoklu kablosuz sensörlü ağ? Şimdilik ANT olarak kalsın...Herkese selamlar....
---O Ayhan sensin kardeşim. Mi4C olduğu için lazımsın bize. Gelecek hafta hızlıca bir Ar-Ge yapacağız.

**Comment by sedat27** [comment]
@raoc999 
Orhan ANT oyle kalacak. Nfc degismiyor oda yakin oldugu icin degismemeli bence

**Comment by sedat27** [comment]
Burada bi hata yokmu?veri kullanimi uyarisi ile ilgili
![screenshot_2016-04-09-00-55-14_com android settings](https://cloud.githubusercontent.com/assets/9906622/14398563/ceaa7c46-fded-11e5-8c0f-b12b0c3b40ba.png)

**Comment by sedat27** [comment]
![screenshot_2016-04-09-00-57-58_com android settings](https://cloud.githubusercontent.com/assets/9906622/14398615/2dbf9b80-fdee-11e5-9c7a-ff837848b5f1.png)
İkinci secenek biraz garip.
Bu hatalar Orhanin dosyalarinda yoksa dikkate almayin. Ben gene yazayimda siz bakarsiniz

**Comment by sedat27** [comment]
Aliciyim-gondericiyim yeterli bence. @
![screenshot_2016-04-09-01-03-32_com miui backup](https://cloud.githubusercontent.com/assets/9906622/14398710/f751b870-fdee-11e5-8f9f-469e99da101a.png)

**Comment by aykutyenihan** [comment]
![screenshot_2016-04-08-19-10-07_com miui securitycenter](https://cloud.githubusercontent.com/assets/16150035/14402049/0c39d600-fe30-11e5-9648-1030f9d402d8.png)
![screenshot_2016-04-08-18-12-12_com miui securitycenter](https://cloud.githubusercontent.com/as
![screenshot_2016-04-08-18-09-55_com android settings](https://cloud.githubusercontent.com/assets/16150035/14402055/20366a92-fe30-11e5-9a0d-07429c8ae51d.png)
sets/16150035/14402050/12a363f8-fe30-11e5-9045-51c386f59970.png)
![screenshot_2016-04-08-18-11-53_com android phone](https://cloud.githubusercontent.com/assets/16150035/14402052/187f7640-fe30-11e5-9da7-dfe3951247e5.png)

**Comment by aykutyenihan** [comment]
. 
![screenshot_2016-04-08-18-12-12_com miui securitycenter](https://cloud.githubusercontent.com/assets/16150035/14402072/d788b510-fe30-11e5-869e-9310265bb77c.png)

![screenshot_2016-04-08-18-09-55_com android settings](https://cloud.githubusercontent.com/assets/16150035/14402073/e7938084-fe30-11e5-9fa7-f52f0f3271a6.png)

**Comment by aykutyenihan** [comment]
(mi4c için)
**ayarlar uygulamasında** 
Hakkında - Telefon hakkında
Uyku - Uyku modu yada Rahatsız etme
Çocuk kilidi - Ebeveyn kilidi
Wifi - Wi-Fi
Tek el - Tek elle kontrol yada modu
Gelişmiş - Geliştirici seçenekleri
Mi hesap - Mi hesabı
Android güvenlik sürümü - Android güvenlik yama tarihi

**Kamera uygulaması**
Hızlandırılmış - Hızlı çekim
Yavaşlatılmış - Yavaş çekim

**Kilit ekranı uygulaması**
Mi remote için sağa kaydırın - Arama yapmak için sağa kaydırın
telefonu aldığımdan beri hiç düzeltilemediği için ben kendim düzeltmiştim aslında buda dil dosyası
[MiuiKeyguard.zip](https://github.com/ingbrzy/MA-XML-7.0-TURKISH/files/211108/MiuiKeyguard.zip)

şahsi kanaatim cümleler gereksiz uzatılmamalı (Lütfen sarj cihazınızı bağlayın yerine Şarj cihazını takın gibi basit olmalı) farklı kelime bulacağım diye uğraşılmamalı, tamam belki doğrusu bu değil ama Türkçe'yi bir rom dosyasından kurtaramayız. Dil diğer markalı telefonlarda nasılsa ona yakın olmalı. Naçizane fikrim budur. İki çevirininde iyi kötü yanları vardı iyi yanlarla mükemmel ortak çeviri yapılabilir ama yapılırmı bilemem.

**Comment by raoc999** [comment]
Dediklerinizi tek te dikkate alacağız, düzelttikçe sizin fikirlerinizi de ekleyeceğiz. Kismetse bugün B, C,D harfinden olan dosyaları düzeltip ekleyeceğim.

**Comment by raoc999** [comment]
En güncel telefon Redmi Note 3 Pro galiba, peki tüm değişiklikleri ve güncellemeleri içinde barındıran MI5 mi ve kodlarını bilen var mı?

**Comment by raoc999** [comment]
cancro = Mi3/4
mocha = Mi Pad
latte = Mi Pad 2
pisces = Mi3 TD-SCDMA
taurus = Mi2A
aries = Mi2/S
ferrari = Mi4i
virgo = Mi Note
leo = Mi Note Pro
libra = Mi4c
hennessy = Redmi Note 3
hermes = Redmi Note 2/2 Prime  
dior = Redmi Note 4G/LTE Single Sim
gucci = Redmi Note 1S 4G (Dual SIM)
HM2013023 = Redmi (Hongmi) 1 MTK WCDMA
HM2014811 = Redmi 2 WCDMA
HM2014813 = Redmi 2 TD/(2GB)
lcsh92_wet_jb9 = Redmi Note 3g MTK WCDMA
armani = Redmi 1S WCDMA

Bunun haricinde diğerlerinin kodlarını bilen yazabilir mi? Çok önemli

**Comment by aykutyenihan** [comment]
![roms](https://cloud.githubusercontent.com/assets/16150035/14402383/d02b25b2-fe3c-11e5-873f-1bf266ff7a10.png)

**Comment by aykutyenihan** [comment]
çoklu dil olan bütün cihazlar bunlar ama Türkiye'de kullanılan aktif cihazlar toplasan bir elin parmaklarını geçmez.

**Comment by aykutyenihan** [comment]
hocam adım Aykut :) nys kolay gelsin bu hafta sorunsuz çeviri olur inş

**Comment by raoc999** [comment]
Sağol Aykut.. Arkadaş düzenleme yaparken 4.4, 5.0, 5.1, ve 6.0 olan cihazları dikkate alıyorum. 6.4.7'deki değişiklikleri de entegre edip ekliyorum. Biraz zor ama, bir kez zor olacak... Kaynak olarak: armani, cancro, hennessy,hermes,kenzo,latte,virgo yu baz alacağım. Diğerleride aynı zaten.

**Comment by salihkiraz** [comment]
arkadaşlar bildirim çubugunda yukarıdaki arama kısmı çince bende sizdede öyle bir sorun varmı. cihaz:mi4c

**Comment by sedat27** [comment]
@raoc999 Orhan tüm baidu yönlendirmelerini google a çevirebilirmisin?
birde geçen 155 aradım ihbar için. ekran MTS Customer Care yazdı.Neyse artık o!
Bilinmeyen numaralar aktif .
bunuda tr de çalıştırabilsek güzel olur aslında. Saf androidte bu güzel çalışmakta oradaki kodların içinden bunu TR için bulabilir miyiz?
