### ISSUE TITLE
6.4.7 Sürümündeki Kamera Problemleri

### ISSUE THREAD

**Issue by raoc999** [ingbrzy/MA-XML-8.0-TURKISH#37]
Arkadaşlar 6.4.7 sürümünü kurupta Kamera+Galeri de sorunu olanlar kullandığı modeli yazabilir mi? 
Dikkat 6.4.7 sürümüne göre. Stabil sürümü baz almıyoruz. Sorunsuz çalışanlarda model belirtebilir.

**Comment by MIUITurkey** [comment]
Mi4c sorunsuz
8 Nis 2016 ÖS 10:31 tarihinde "recep.ali.orhan.cakmak" <
notifications@github.com> yazdı:

**Comment by sedat27** [comment]
Eski galeri sorunu yok ama. Kamera ilk acildiginda son resim onizleme yok. Resim cekince geliyo ama kapatip acinca gene yok.
![screenshot_2016-04-08-22-39-26_com android camera](https://cloud.githubusercontent.com/assets/9906622/14395527/e0ff1e50-fdda-11e5-89e8-10f1bb0d4cf4.png)

**Comment by sedat27** [comment]
Redmi note 3 mtk

**Comment by aykutyenihan** [comment]
mi4c hiç sorun yoktu olmadı olamaz :)

**Comment by sedat27** [comment]
Mi4 serisinde ben hic sorun yasamadim. Ozlemiyo degilim. Mi5 beklemesem hemen tekrar alirdim

**Comment by raoc999** [comment]
Redmi Note 2 de de sorun yok,Sedat'ın belittiği Kamera açıldığında önceki resmin onizlemesi bende de yok ama bunu sorun olarak değerlendirmemiştim. Muhtemel programcılarda çektikten sonra çıkmasına göre ayarladı.
