### ISSUE TITLE
Durum Bilgisi (6.4.7) (6.4.8)

### ISSUE THREAD

**Issue by raoc999** [ingbrzy/MA-XML-8.0-TURKISH#38]
Çevirinin A harfinden olan dosyalarını dün bitirmiştim. Backup dosyalarını, Barcode, Battery,Bluetooth dosyalarını yeniden gözden geçirdim. Bluetooh biraz karışmıştı, diğer ürünlerinde değişik satırlarını ekledim. BasicDaydreams dosyasını upload ettim.

**Comment by raoc999** [comment]
Bazı Çinli sitelere verilen linkleri MUIU Türkiye sitesine yönlendiriyorum. MUIU Türkiye Xioami için bayağı çaba harcıyor, Hem Xiaomi ürünlerini tanıtıyor hemde faydalı bilgiler içeriyor. Elin Çinli sitesinden de birşey anlamıyoruz. (Tarayıcı)

**Comment by MIUITurkey** [comment]
Çok iyi olur hocam.
9 Nis 2016 ÖS 2:59 tarihinde "recep.ali.orhan.cakmak" <
notifications@github.com> yazdı:

**Comment by raoc999** [comment]
Hasan direkt http://www.miuiturkiye.net/ linki veriyorum. Alişveriş ve forum içinde sizin linkleri ekleyeceğim. Siz şimdilik sadece upload etmeyin yeter. Beni ikide bir uğraştırmayın, küsüp gideceğim sonra :)

**Comment by MIUITurkey** [comment]
Yok hocam şuan komple sende.
Bu arada forumda bir çeviri ekibi kurulu sizin de kullanıcı adınız varsa
sizi de ekleyelim ekip lideri olarak arkadaşlar oradan da hata bildirimi
yapabilir.
9 Nis 2016 ÖS 3:03 tarihinde "recep.ali.orhan.cakmak" <
notifications@github.com> yazdı:

**Comment by MIUITurkey** [comment]
Eğer istersen sana da yaptığımız orijinal resmi çeviri dosyasını da
gönderebilirim.
9 Nis 2016 ÖS 3:04 tarihinde "Hasan ÖZKAN" <hasan.ozkan.35@gmail.com> yazdı:

**Comment by raoc999** [comment]
Valla varsa gönder, biraz kağı gibi devam ediyorum ama Çince hiçbir yer kalmayacak, Çince linkleri google.tr adresine, alışveriş, forum vb ne kadar çinli salak adres varsa sizin sitenin ilgili yerlerine çeviriyorum. Benim zamanım olmadığından sitenizin forumuna dolaşamıyorum. Sabah biraz baktım faydalı bir yeriniz var. Dosyayı mail adresime gönderebilirsin.

**Comment by raoc999** [comment]
Oyun ve uygulama indirilecek bir dost arkadaş sitesi varsa yaz lütfen

**Comment by MIUITurkey** [comment]
Yok hocam.
9 Nis 2016 ÖS 3:08 tarihinde "recep.ali.orhan.cakmak" <
notifications@github.com> yazdı:

**Comment by raoc999** [comment]
Güncelleme sayfanızıda ekledim artık  o sayfayıda daha güncel yapın.

**Comment by raoc999** [comment]
Hasan Youtube sayfanıda ekliyorum. Ürünlerin tanıtımını filan yaparsın

**Comment by MIUITurkey** [comment]
YouTube sayfasında video ipuçları ekliyoruz hocam zaman zaman
9 Nis 2016 ÖS 3:15 tarihinde hasan.ozkan.35@gmail.com yazdı:

Hocam bunda kalıp farklıdır biraz ama kod kısmından yararlanabilirsin.
Birde bunu dağıtmazsak sevinirim.
9 Nis 2016 ÖS 3:10 tarihinde "recep.ali.orhan.cakmak" <
notifications@github.com> yazdı:

Güncelleme sayfanızıda ekledim artık o sayfayıda daha güncel yapın.

—
You are receiving this because you commented.

Reply to this email directly or view it on GitHub
<https://github.com/ingbrzy/MA-XML-7.0-TURKISH/issues/38#issuecomment-207781297>

**Comment by raoc999** [comment]
Yok dağıtmam, kendiminkini bile vermiyorum görüyorsun :)

**Comment by MIUITurkey** [comment]
Tamamdır sıkıntı yok
9 Nis 2016 ÖS 3:23 tarihinde "recep.ali.orhan.cakmak" <
notifications@github.com> yazdı:

**Comment by raoc999** [comment]
raocakmak@gmail.com adresime mail at lütfen

**Comment by raoc999** [comment]
Beyler Bing sayfasına giden linkleri de kaldırıyorum Bing çökmüş zaten. Google'a yönlendiriyorum

**Comment by raoc999** [comment]
Hasan bana acilen sitenin ico dosyasının linkini verebilirmisin. Yoksa http://www.miuiturkiye.net/wp-content/uploads/2016/02/muiutr.ico adresine birtane ico dosyası yap. Tarayıcıda gelen simgelere siteni ekliyorum

**Comment by MIUITurkey** [comment]
http://www.miuiturkiye.net/favicon.ico

Adresinde mevcut hocam.
9 Nis 2016 ÖS 3:38 tarihinde "recep.ali.orhan.cakmak" <
notifications@github.com> yazdı:

**Comment by raoc999** [comment]
Tamamdır

**Comment by MIUITurkey** [comment]
Tarayıcıyı full baştan yaptın sanırım :)
9 Nis 2016 ÖS 3:43 tarihinde "recep.ali.orhan.cakmak" <
notifications@github.com> yazdı:

**Comment by paclix** [comment]
Celaleddin Madencan'a ne oldu? Gerçekten merak ediyorum bir anda çeviri işleri karıştı o adam gidince.

**Comment by raoc999** [comment]
Aslında karışmadı, ben Celalleddin'le konuşmuştum, hastaydı ben devam ettim, sonra birden Hakan yeniden upload yapınca, orada işler patladı. Yoksa ben Hermes'i en iyi şekilde bitirip diğer ürünleride ekleyecektim. Biraz karışıklık oldu ama eğer diğer arkadaşlar upload yapmazlarsa 2-3 hafta sonra en iyi şekilde çıkacak merak etmeyin. Arkadaşların çevirdiği diğer modelleride dikkate alarak en iyi hale getiriyorum. Tüm çince yazıları kaldırıp, linkleri de google, muiu türkiye vb...ye çeviriyorum.

**Comment by aykutyenihan** [comment]
bütün cevirmenler iyi ama koordinasyon eksikliği oldu şimdi planli gidiliyor sorun olmaz. eskiden tek kişi yaptığı için standart gidiyordu. emegi gecen herkese kolay gelsin.

**Comment by raoc999** [comment]
Hesap Makinesi, Takvim, Sertifikalar, Şebeke Yayını ile ilgili dosyalar bitti. Ayrıca C harfi ile ilgili iki yeni dosya ekledim. Diğer telefonlardaki ek satırları ve 6.4.7 güncellemesini bitirdiklerime eklemiş oldum. Devam ediyor....

**Comment by aykutyenihan** [comment]
hocam WLAN terimini çok kullanma lütfen kısaltma olarak wifi ana menü baslığındada kablosuz yada kablosuz ağ yerinde olur.

**Comment by raoc999** [comment]
Aykut, adamlar Wi-Fi ve WLAN diye iki terim kullanıyor. Sadece kablosuz internet gibi bağlantıda Wi-Fi, hem kablosuz internet  hem de ağ bağlantılarında WLAN kullanıyorlar. Bende aynı mantıkla hareket ediyorum. Birde kısaltmaları mecburen kullanıyorum zira Cep Telefonu kullanıyoruz, PC olsa cümleleri uzatabilirsin ama elimizde hem ekranı küçük bir cihaz var hemde oturup saatlerce ne nedir diyemiyeceğin hızlı kullanacağın ürün var. Bundan dolayı açıklamalar hariç, başlıkları kısa anlaşılır hale getirmeye çalışıyorum. 3 hafta istiyorum, inş. ortaya çok güzel bir sonuç çıkacak.

**Comment by aykutyenihan** [comment]
nexus ta kullandim hocam onun en doğru şekli wi-fi dir. wlan daha genis anlama hitap eder bilgisayardaki gibi. ev ağı ortak ag vs

**Comment by aykutyenihan** [comment]
kısaltmalarda sorun yok olmasi gereken o zaten. kolay gelsin hocam istediğin vakit olsun

**Comment by raoc999** [comment]
Cleanmaster düzeltilip eklendi. 6.4.7 eklemeleri yapıldı.

**Comment by sedat27** [comment]
@MIUITurkey hasan forumda bulamadim yeni konuyu. Eger bi destegimiz olacaksa ekibe bende talibim. Forumda da aynı kullanici adim.

**Comment by sedat27** [comment]
Wi-fi = wireless fidelity. Kablosuz baglanti alani. İnternet demek
Wlan= kablosuz ag. İnternet olmasada olur. Aletlerde kendi aralarinda kurabilir.
Wifi kuramazsiniz. Ama wlan kurabilirsiniz

**Comment by aykutyenihan** [comment]
yani sonuç oalrak doğrusu nedir wifi mi wlan mı? :) bizim için hangi ifade kullanılmalı.

**Comment by MIUITurkey** [comment]
Sedat hocam yarın ayarlayacam inşallah sen bana üye adını at forum adını
11 Nis 2016 ÖÖ 12:23 tarihinde "aykutyenihan" <notifications@github.com>
yazdı:

**Comment by raoc999** [comment]
CloudBackup düzenenip eklendi. Wi-Fi ve WLAN hakkında. Xiaomi WLAN olması gerekn yere WLAN Wi-Fi olması gereken yere Wi-Fi yazmış zaten. Çeviri yaparken biz işgüzarlık yapıp değiştirmezsek sorun yok zaten

**Comment by aykutyenihan** [comment]
hocam sizin çeviride ayarlar ana menusunde wlan yazıyordu ondan bu kadar uzattım, orası wi-fi olduktan sonrası önemli değil.

**Comment by raoc999** [comment]
Sorun yok Aykut, Orjinal dosyada ne yazıyor ona bakar öyle çeviririz. Düzenlemede orjinal dosyalara da bakıyorum.

**Comment by raoc999** [comment]
ColudService düzenlenip 6.4.7 eklentileri yapıldı.

**Comment by raoc999** [comment]
CloudAppBackup düzenlenip eklendi. Yeni dosya!

**Comment by raoc999** [comment]
CMTransfer dosyası düzenlenip eklendi.

**Comment by raoc999** [comment]
Colorservice dosyası eklendi.

**Comment by raoc999** [comment]
Yorumsuz: Not enough space => Sim kartınız dolu yeni kişiler eklenemiyor. Lütfen Sim kartınızda yer açtıktan sonra tekrar deneyin 
Yorum: ???!!!!! :()

**Comment by raoc999** [comment]
Contacts dosyaları düzenlendi ve eklendi.

**Comment by raoc999** [comment]
ContactsProvider +

**Comment by raoc999** [comment]
DeskClock, DocumentsUI ++

**Comment by raoc999** [comment]
Bu arada çok komik satırlar olmuş kimin marifeti acaba? Ben Rizeliyim ama beni bile geçmişsiniz! :)
Temel fıkrası gibi. Misal: Orjinal: Xunlei download accelerator is on --> Çeviri: "Sevgili Thunder vip. Yüksek hızlı kanal açıldı"
Çok güldüm. Dalgınlığa geldi herhalde... Birde takvimde adam faldan bahsediyor. Yani Kismet'ten o da Servet diye çevrilmiş. :+1:

**Comment by MIUITurkey** [comment]
:):)))
11 Nis 2016 19:46 tarihinde "recep.ali.orhan.cakmak" <
notifications@github.com> yazdı:

**Comment by raoc999** [comment]
DownloadProviderUi + düzenlendi ve eklendi.

**Comment by raoc999** [comment]
Dosya Gezgini 6.4.7 sürüme göre düzenlenip eklendi.

**Comment by raoc999** [comment]
Telefonu Bul dosyaları 6.4.7 sürümüne göre düzenlenip yüklendi

**Comment by MIUITurkey** [comment]
En zoru swttings olacaktır sanırım :)
12 Nis 2016 17:49 tarihinde "recep.ali.orhan.cakmak" <
notifications@github.com> yazdı:

**Comment by raoc999** [comment]
Aynen ama benim çalışma stilim farklı, aynı anda birden fazla dosya yapıyorum. Öteki dosyalar bir bakıma otomatik oluyor.

**Comment by raoc999** [comment]
Radyo yazılımı düzenlendi

**Comment by raoc999** [comment]
framework-ext +

**Comment by raoc999** [comment]
Framework dosyası çok bozuldu, satır, çeviri vb... herşey birbirine girmiş. Bu dosya çok kritik ve öenmli olduğundan baştan aşağı en güncel 6.4.12 ile baştan aşağı düzeltiyorum. Zaman zaman zaman....

**Comment by raoc999** [comment]
Framework dosyası 6.4.7 olarak düzeltilip atıldı. Bu dosya en az 5 saatimi aldı. En büyük dosya bu, halen düzeltilmesi gereken 5-10 büyük satır var. Onu sonra hallederiz. Göreceğiniz birşey değil :)

**Comment by raoc999** [comment]
Fonksiyonel Hesap makinesiyle alakalı yeni dosya çevrilip eklendi

**Comment by raoc999** [comment]
Yeni Güncelleme dosyası çevrilip eklendi.

**Comment by raoc999** [comment]
Beyler Çağrı -InCallUI- dosyasını baştan aşağı düzenlemek biraz uzun sürüyor. Nedeni ise bu dosya arama yapmak için çok önemli birbirine geçmiş durumda. Düzenlemesini bitirdim ama yeniden derliyorum ayrıca içinde olması gereken pekçok satırı çevirip ekliyorum. Biraz geç oluyor ama temiz olsun, ikide bir baştan başlanılmasın. Çeviriyi yapan  Hakan / Hasan FDN'yi neden San diye çevirdiniz? Manası nedir? Hata mı oldu?

**Comment by raoc999** [comment]
InCallUI dosyası çok zor olmakla bitti. Çoğu yerini yeniden çevirmek zorunda kaldım. Çünkü çok karışmıştı, sırası bozulmuştu. Ayrıca görüntülü çağrı ile çok fazla satır vardı onlarıda çevirip ekledim. Satırların bir kısmı sıralanacak. Önemli değil. Sadece tam olarak karşılığını bulamadığım bazı satırlar var, yazılım çıkınca neyin nerede olduğunu görüp, tavsiyeleriniz doğrultusunda düzeltmeler yapacağız.  En önemli ikinci dosya bu idi. Umarım bu dosyada hiç aksilik çıkmaz, tüm arama işleri bunda...

**Comment by raoc999** [comment]
Mediatek dosyasını çeviren yoksa ben çevireyim zira M harfine kadar olan tüm dosyalar bitti. Birde Mi Pop dosyasının kaynağı lazım. Mail atabilir misiniz. Ayrıca Miband, Mikey bunları çeviren var mı? Acil dönüş yapsın. Yarın Kamera ve Galeriyi bitirmem lazım... Onları da araya sıkıştıralım.

**Comment by MIUITurkey** [comment]
Hocam miband ve nikey için hakan hocam size mail atmış olması gerek
14 Nis 2016 00:23 tarihinde "recep.ali.orhan.cakmak" <
notifications@github.com> yazdı:

**Comment by raoc999** [comment]
Mipay dosyasını çevirine arkadaş!!! Arkadaşlar eğer bizde çeviri yapacağız ama google translate kullanacağız diye düşünen varsa lütfen bize yaklaşmasın. Bazı dosyaları yeniden çevirmekten başka çare yok. İngilizcesini anlıyorum, Türkçesini anlamıyorum. Kopy paste yöntemiyle çeviri olmaz, kimse kendini kandırmasın. Çevrilen cümlenin ingilizcesini Google Translate-e atıyorum tam çevrilen karşılık çıkıyor. Oysa cümlede başka birşey söyleniyor. Aynı dosya içinde bir kelime aynı manada ise nasıl oluyorda üç farklı manada oluyor. Amount ödemede miktar değildir Tutar'dır.... Mipay dosyasını atlıyorum daha önemli işler var. Mipay dosyasını ben çeviririm. Bir kısmını düzelttim zaten. Lütfen çeviri yapan arkadaşlar Google Translate'ten önce kendileri cümleye bir baksınlar. Cümleleri en azından aynı manaya gelecek şekilde çevirsinler. Gerekirse eklesinler amayolunmuş tavuğa çevirmesinler. Ödeme, çağrı, mesaj gönderme gibi kullanıcıyı sıkıntıya sokacak çeviri yapmasınlar. Anamıza sövdürmeyelim.

**Comment by raoc999** [comment]
MiTag dosyası çevrilip eklendi, MiPay dosyası silindi çevirisi net olunca eklenecek, Günlük duvar kağıdı gibi kısa dosyalardan bazıları derlenip-düzenlenip eklendi

**Comment by raoc999** [comment]
muiu dosyası düzeltilip eklendi, kısaltmalardaki hatalar giderildi, çine ait resmi günler çine göre düzeltildi.

**Comment by raoc999** [comment]
MuiCamera dosyası elden geçirilip geri yüklendi. Not: Çeviri ekibi Full HD gibi dağdaki çobanın bile artık bildiği kelimeyi Tam HD gibi çevirmesin. Yine en cahilin bile bildiği Hayat kilimesinin yerine Yaş-am gibi köksüz uyduruk şeyler kullanmasın. Bir milletin millet olması için en önemli şeyi dilidir. Orta Asyadan beri zenginleşen bir dilimiz varken yerleşke, yöntem, olabirite saçmalıkları kullanmamak lazım. Danıştay, Yargıtay.... bir sürü.... Bu hep aşağılık duygusu. Genelde hergün bir okuldayım ve gençlerin çoğusu derdini anlatacak kadar Türkçe bilmiyor. Çünkü kelime hazinesi sıfır...

**Comment by raoc999** [comment]
Yeni Framework dosyası eklendi, ana ekranda düzenlenip eklendi
