### ISSUE TITLE
Durum Bilgisi (6.4.11 ve üstü)

### ISSUE THREAD

**Issue by raoc999** [ingbrzy/MA-XML-8.0-TURKISH#39]
Arkadaşlar 6.4.11 sürümü ve üstü değişiklikleri buraya yazıyorum altındakileri bir önceki konuya....

Kişiler (Contacts) dosyasının 6.4.11 sürüm güncellemelerini yapıp ekledim.

**Comment by raoc999** [comment]
E-Posta dosyaları 6.4.11 sürümüne göre düzenlendi. Hayırlı olsun bu gün bu kadar yeter.

**Comment by raoc999** [comment]
Browser -Tarayıcı dosyası 6.4.12 sürümüne göre derlendi.

**Comment by raoc999** [comment]
Galeri dosyası 6.4.11 sürümüne göre derlendi yeni satırlar çevrildi.

**Comment by raoc999** [comment]
Galeri dosyasındaki bazı ifadeler bayağı değişmiş, yeni satırları ekledim, çevirleri düzelttim. 6.4.14 sürümü

**Comment by raoc999** [comment]
Ekran Kilidi Duvar Kağıdı 6.4.14 sürümüne göre güncelledim. Uygulamanın ismi değişti. Tam Türkçesi Ekran Kilidi Atlıkarıncası oldu. "Carousel" kelimesi için güzel bir önerisi olan yazsın.

**Comment by aykutyenihan** [comment]
Günlük duvar kağıdı yaz geç hocam. :) mi4c için sağa kaydırma işini unutma hocam her seferinde kendim apk değişmekten gına geldi

**Comment by aykutyenihan** [comment]
gördüğüm kadarıyla değişmemiş yine apk değişeceğiz bundan kurtuluş yok sanırım. biraz göz attım çokçada hata var bu haftada beklentiye girmeye gerek yok kendi açımdan.

**Comment by raoc999** [comment]
Aykut hangi dosyada dediğin, ben bitirdiğim dosyaların sürüm numarasını yazıyorum. Arkadaşların upload ettiklerini silmiyorum. En azından birşey olsun. Gerekirse benim önceki 6.3.24 sürümün yüklerim ama o sürümde Redmi Note 2 içindi, diğer telefonların içeriğinde ingilizce cümleler çıkıyordu. Ayrıca çokça gördüğün hatalı dosyayı lütfen yaz.

**Comment by raoc999** [comment]
Müzik dosyası 6.4.7 olarak güncellendi, bayağı bir satır geldi, acaba itunes gibi oluyor :) Yeni satırlar eklendi ve çevrildi.

**Comment by raoc999** [comment]
Diğer dosyaların hepsini 6.3.24 sürümüne çevirdim. Gelecek hafta güncellemeleri yapıp devam edeceğiz.

**Comment by aykutyenihan** [comment]
miuikeyguard hocam daha öncede söylemiştim. kilit ekranında sağa kaydırın mi remote yi açmıyor arama uygulamasını açıyor, en azınsan mi4c de bu böyle diğerleini bilmiyorum. dil dosyasında mi remote ama romda yaptığı işlev farklı çevirmenlerde dil dosyasını baz aldıkları için telefonu aldım alalı hatalı. bikaç yerde MUIU gördüm hocam takdir edersin ki öyle birşey yok :)

**Comment by raoc999** [comment]
Peki senin bana gönderdiğin dosyada düzeltilmiş mi idi? Düzeltilmiş dosyanı eklesek acaba bu kezde diğer telefonlar mı gider? Nasıl yapalım önerin ne?

**Comment by aykutyenihan** [comment]
hocam ben çeviri işini bilmiyorum daha doğrusu tek bir dosyamı var yoksa her telefonun çeviri dosyası ayrımı? yada her cihazda sağa kaydırma telefon uygulamasınımı açıyor yada remotemi? sadece mi4c mi sorunlu olan? bunları bilmiyorum ki. Eğer mi4c özelinde bir dosya varsa bu işi çözecekse iş basit sağa kaydırın kısmına; arama yapmak için sağa kaydırın yazılacak bitti gitti. Dosyanın geri kalanında sıkıntı yok çünkü.
