### ISSUE TITLE
bildirim çubuğu arama kısmı çince

### ISSUE THREAD

**Issue by salihkiraz** [ingbrzy/MA-XML-8.0-TURKISH#42]
arkadaşlar bildirim çubugunda yukarıdaki arama kısmı çince bende sizdede öyle bir sorun varmı. cihaz:mi4c

**Comment by MIUITurkey** [comment]
Çözüm.

Veri kısıtlardan ara uygulamasının veri kullanımını kapat.
Sonra uygulamalardan ara uygulamasının verişini temizle yeniden başlar
cihazı tamamdır
13 Nis 2016 ÖS 12:15 tarihinde "salihkiraz" <notifications@github.com>
yazdı:

**Comment by salihkiraz** [comment]
kalıcı bir çözüm yokmu acaba uygulamada kullanılan webservisi değiştirsek flan

**Comment by MIUITurkey** [comment]
Bu çözümde kalıcı oluyor
13 Nis 2016 12:27 tarihinde "salihkiraz" <notifications@github.com> yazdı:

**Comment by salihkiraz** [comment]
kalıcı olmadı malesef  :( aramayı açınca internete izin vermesi gerektiğini söylüyor bende yoksa arama yaptırmıyor.
