### ISSUE TITLE
(Sürüm 6.4.14) Tavsiye ve Öneriler

### ISSUE THREAD

**Issue by raoc999** [ingbrzy/MA-XML-8.0-TURKISH#43]
Arkadaşlar dosyaların büyük bir kısmını elden geçirdim  (A-M Harfleri). Gelecek Hafta aksilik olmazsa tüm dosyaları elden geçireceğim. Bu esnada 4-5 kadar yeni dosya çevirip ekledim. Özellikle ricam İngilizce gözüken yerleri belirtin. 6.4.14 sürümüyle ilgili yaptığım güncellemeler yönetici tarafından silindi. Belki erken gitmemem gerekiyor, önemli değil. Gelecek hafta yapacağım güncellemeden sonra ürünleri tamamen bir teste tabi tutacağız. Ayrıca Hakan'ın çevirdiği Mi Key, Mi Band ve kimin çevirdiğini bilmediğim Mi Pay adlı çok kötü çevrilmiş dosyayısisteme ekleyeceğim.
Eklenecek Dosyalar:
1. Mi Key
2. Mi Band
3: Mi Pay
4: SuperMarket
5: Voice Asistant 
6: XMPass ve yaklaşık 4 kadar yeni özellik...
Tüm ürünlerle ilgili bilgi, öneri, eleştiri vbye MUIU Türkiye sitemiz üzerinden erişebilirsiniz.

Herkese keyifli ve sıkıntı yaşamayacağı deneyimler dilerim. Orhan. 00.10

**Comment by raoc999** [comment]
Redmi Note 2: Arkadaşlar kurulum sonrası notlarım:

1: Geliştirici Seçeneklerinide bazı hatalarım var düzelteceğim.
2: Kamerada Hızlı Çekim yerini kaydırdım veya yanlış yazdım düzelteceğim.
3.: Mobile Veri Dolaşımı altında İngilizce satırlar var düzelecek
4: Günlük kilit ekranına ait bazı uzun satırları kısaltacağım
5: inches ---- Bunu nerden çektiğini halen bulamadım ama çözeceğim. Diğer Almanca gibi dile bakacağım onlar ne yapmışlar
6: Pille ilgili anlam bozukluğu var düzelteceğim
7: SD Kartı sil bölümünün açıklaması bozuk düzeltilecek
8:Ekolayzir açıklaması düzeltilecek
9: Erişebilirlik altındaki ing. çevrilecek
10: Mi Bulut altında bazı ing. yerler var düzeltilecek
11: Güvenlikteki bazı ing. yerlerde düzeltilecek
12: Uzaktan Kumanda ismini Kumanda olarak değiştireceğim çok uzun yarısı gözükmuyor
13: Hızlı arama ekranıda gelen çince yazıların nerden kaynaklandığını buldum ve değiştirdim fakat yönetici test için yazdığım satırı sildi. Satır direkt Xiaominin sitesinden ipuçlarını çekiyor. Bu hafta onu google vb Türkçe olan bir yere yönlendireceğim. 
Redmi Note hariç diğer ürünlerle ilgili bulduğunuz hataları gerekirse ekran görüntüsü alarak gönderin. Arkadaşların çevirisinin düzenlenmesi çok zaman aldığından önceden çevirdiğim 6.3.24 sürümüne indim. O çevirinin üstüne diğer telefon ve güncellemeleri ekliyorum. Hakan'ın çevirisiyle karşılaştırıyorum.

**Comment by haqanguven** [comment]
Mi Key, Mi Band ve mi pay benim çevirilerim. Madem bu kadar kötüler çeviriler. Ben neden yapıyorun çeviri işini ben onu anlamıyorum. Kusura bakma ama ben bu işe el attıysam senin çevirilerin yüzünden gelen şikayetler yüzünden başladım. Miro'nun yaptığı saçma sapan şey yüzünden de bıraktım. Kimse benim çevirimi kötü demedi sadece eksikleri vardı...

**Comment by sedat27** [comment]
![screenshot_2016-04-15-13-30-07_com android quicksearchbox](https://cloud.githubusercontent.com/assets/9906622/14558949/3b3adc82-030e-11e6-80c9-72d8db50c20f.png)
Sanirim aramada google adresinde bir hata var.

**Comment by raoc999** [comment]
Hakan cümleyi düzgün oku lütfen Mi Key ve Mi Band kötüçevrilmiş demedim. SadeceMi Payda kötü yerler var veya Mi Pay dosyası ile Kaynak dosya arasında satırların yerleri değişti . Benim çeviri sadece Hermes içindi, diğer telefonlar için değildi. Diğer taraftan benim çeviride birsürü imla hataları var. Senin çeviri ile benim çeviri karşılaştırarak düzeltiyorum. Ama birşey var o da ben bir yere Armut dediysem sırf muhalefet olsun diye mi elma dediniz anlamadım. Çoğru yerde ve cümle içinde sürekli basit değişiklikler yapıldı. Bilek Taşı'nın karşılığı ne zaman Özendirme oldu.... Sorun yok Mi Key, Mi Band, Mi Pay'ı çeviririm. Zaten Mi Payın yarısını yeniden çevirdim. Eğer iki hafta zarar etmese idik tüm ürünleri baştan aşağı bitirmiştim... Kolay gelsin.

**Comment by aykutyenihan** [comment]
hakanın çeviriside gayet güzeldi, vardı illaki hatalar ama şimdide var yine de olacak. Kalp kırmaya gerek yok arkadaşlar.

**Comment by raoc999** [comment]
Kimseyi kırmak gibi bir derdim yok. Bir kaç şeye hiç memnun olmadım. 
1. Ben nasıl önce Cellaleddin ile yazışıp ondan izin alıp site yöneticisine başvurdum ve devam ettim.
2. Hiç sormadan bir gecede tüm içeriği silmeleri hoş değildi.
3. Bir cümlenin anlamı %100 Ali iken, illa biraz değişiklik olsun diye. Misal: Yönlendir > İlet gibi basit değişiklikler yapmak çeviri değil. Düzeltme.
4. Keşke yaptığım hataları düzeltip; 2 hafta ileri taşınsaydı çok iyi olurdu. Zaman kaybı yaşadık ki bu hoş olmadı.
5. Şikayet merci MUIU Turkiye değil, site FAN sitesi, şikayetler oraya da yapılabilir ama bu şikayet geldiğinden biz müdahale yapıyoruz  fikrini gerçekçi kılmaz. Sadece Xiaomi gelir der kaldırın tüm dosyaları ki Xiaomi'ye de yazdım, bundan memnun olacaklarını sonuçta insanların ne kadar ilgisini çekerse taleplerin de artacağını, Türkiye'nin onlar için önemli olduğunu yazdılar. 
6. Benim de hata yaptığım çok yer var, Kötü çeviri derken herşeyi kastetmiyorum ama bazı yerler var yanlış manada. Bunu telefon üzerinde kimse göremez. Ben telefonda "Bugün eve gitmiyorum" yazsam gören sadece imlâ hatasına bakar ama belkide İng. "Birgün eve gitmeyeceğim" ise nereden bileceksiniz. Ayrıca başka bir dosya da Armut olan çeviri bir sonraki dosyada Elma olursa tutarsızlık var. Allahı var Hakan aslında büyük bir iş yaptı, ama o da insandır ve hata yapabilir. Burada benim hatam ise mailde ona özel olarak yazmam gerekirdi... Kırıldıysa özür dilerim, kalp kırmaya değmez. Bu tür şeyleri bir daha yazmıyacağım... İşimize bakalım.

**Comment by raoc999** [comment]
Mİ4C için keyguard yazılımını düzeltelim. Bizde soldan sağa çekince çağrı ekranı çıkıyor. Fakat orada Kumanda ile Mi Remote ile açmaktan bahsediyor ki ki onuda gelecek hafta düzelteceğiz. Dediğim gibi Mi4C için özel bir dosya yapalım, orjinal Mi4C dosyasını çevirerek, böylece sorun gitmiş olur. Gitmezse telefon başka biryeden çekiyor.... Aslında benim fikrim her telefonun dosyasını ayrı ayrı yapmak ama buna izin yok. Sonuçta her telefonun farklı özelliği var.  Toplu dosya daima sorunludur.

**Comment by aykutyenihan** [comment]
eski defteri kapattığımıza göre son sürüm hakkında bir iki yazalım.

sanırım çoğu modelde soldan sağa çekme arama uygulamasını açıyor (çağrı uygulaması) bende de öyle sanırım ben yanlış ifade ettim hocam. Şuan senin telefonda da mi remo ise aynı dosya kurtaracaktır tabi gerçekten mi remoteyi açan model varsa bilemem. apknın string dosyasında mi remote yazıyor ordan direk karşılık yapıldığı için sorun gözükmüyor çeviri yapılırken ama o komut cihazlarda farklı yada xiaomi.eu bunu değiştiriyor çinde mi remote bilmiyorum. umarın bu sefer ifade edebildim.

6.4.14 sürümüne gelecek olursak yükledim gördüğüm hemen heryere girdim çıktım mükemmele yakın bir çeviri olmuş eksik yok denecek gibi, şuanki haliyle kalsa bile kabulumdur çünkü bulabildiğim hatalar devede kulak şeyler. Gerçekten emeğiniz için çok teşekkür ederim.

Adettendir, bulduğum hatalar
**kamera uygulamasında**
Zaman Aralığı - Yavaş çekim
Geniş çekim - Panaroma modu(hata değil sanki bu kelime daha doğru gibi)
**Günlük kilit ekranı**
Kilit ekranında sürekli değişen duvar kağıtları olsun - hata yok ama cümle biraz sadeleştirilmeli çünkü yazı açma kapama buttonunun üstüne biniyor.
**Ayarlarda**
Erişebilirlik ayarlarında Yüksek kontraslı yazılar alt metni (Experimental) olarak kalmış
yazdır menüsünde Cloud Print kalmış
Tek elle kullanım modunda
4.0 inches
3.5 inches

bukadar bulabildim dediğim gibi devede kulak hatalar normal kullanımda karşımıza bile çıkacağı şüpheli.

**Comment by aykutyenihan** [comment]
bide son olarak hata falan değil ama ben bu WLAN olayına ayar oluyorum Wİ-Fi olunca kanım ısınıyor :)

**Comment by sener05** [comment]
Merhabalar. Redmi note 2 kullanıyorum yeni surumu yukledim ve 3g. 4g geçiş seçeneği komple silinmis yani geçiş yapmak için mobil bağlantı seçenek bölümü yok.. Teşekkürler.

**Comment by raoc999** [comment]
Ayukt'a Cevap: Aykut ilk mesajıma bakarsan dediğin özellikleri ve daha fazlasını gördüm. Düzelteceğim. Cloud Print'i değiştiremiyorum o Google'un kurduğu yazıcısından kaynaklanıyor. Şu ana kadar sadece  sadece M harfine kadar olan yerleri derledik. %45 bitti. Gelecek hafta Ayarlar vb... gibi önemli yerleri tamamen elden geçireceğim. Şu an Antifake gibi önemli dosyalar var, Almanca ve  İtalyanca'da varlar.  Onları eklemek lazım.

Sener05: Sürümde 6.3.24'e indik. Gelecek hafta 6.4.14 sürümüne tümüne döndürünce hepsi düzelecek. İsterseniz bir alt sürüme inin. Bunun haricinde gördüğünüz terslikleri lütfen belirtin.
Teşekkürler...

**Comment by sedat27** [comment]
@raoc999 @haqanguven 
Aman diyeyim burda yapmayin. İnsanlarin guvenini kirarsiniz. Saygi duyulan bi is yapiyorsunuz gonullu olarak. Meselelerinizi ozelden tartisin bi sekilde.
 Bu iste kotu iyi diye bisey olmaz pek zaten. Bunun yuzlerce ornegi var. Xiaomi ye ozel bikac yer var. Gerisi tum markalarda al onlardan cevir. Cokta farkli yapmanin manasi yok. Zaten olmamalida.genel gecer bazi kelimeler cumleler var. Fantaziye girmez kimse zaten. 
Geriye dusmemiz guzel olmadi ama napalim oldu artik bosverin.
Hersey daha guzel olacak eminim.
Selamlar saygilar

**Comment by sedat27** [comment]
![screenshot_2016-04-16-01-39-31_com android thememanager](https://cloud.githubusercontent.com/assets/9906622/14576673/253b2386-0374-11e6-86e4-cb57300135fb.png)
Ufak bir ayrinti ama temada "Gelişlet" olmus.
Bu arada bu temayi tavsiye ederim

**Comment by Zenex61** [comment]
İyi günler hocam. Mi4c kullanıcısıyım üstte yazdığınız soldan sağa çekme hakkındaki konuşmayı gördüm bizde de soldan dağa çekince arama uygulaması açılıyor. Bu günden itibaren sizlere yardım etmekten mutluluk duyarım.

**Comment by aykutyenihan** [comment]
telefonu aldığım günden beri hatalı sağa çekme, telefonu da Türkiye'de ilk alanlardanım düşün. :) 
sola çekme de hatalı bu sürümde, cümle düşüklüğü var

**Comment by aykutyenihan** [comment]
hocam bide rica etsem şu saat widgetindeki tarihi biraz kısaltmak mümkünmüdür eski hali daha iyiydi cok uzun olduğu için simetriyi bozmuş çok gözüme battı. 
![screenshot_2016-04-16-18-06-33_com miui home_1460819255690](https://cloud.githubusercontent.com/assets/16150035/14581801/856e2462-03fe-11e6-9795-eff13e1a524b.jpg)

**Comment by raoc999** [comment]
Söylenilen hatalar bu haftaki sürümde düzeltilecek, düzelttiği dosyaları ekliyorum, ayrıca en az 5 yeni dosya daha ekliyorum ki bunlar genelde yeni telefonlar için. İngilizce kalan yer olmaması lazım. Ama imlâ hatası olabilir bunları bana yazın. Okudukça düzeltiyorum. Ayarlar dahil 45 dosyayı yeniden düzelttim. Perşembe gününe kadar bitirmeyi düşünüyorum. Ayrıca yeni dosyalar eklemeye devam edeceğim.

**Comment by ertanx** [comment]
![screenshot_2016-04-19-17-36-15_com miui yellowpage](https://cloud.githubusercontent.com/assets/18513609/14649554/5190197e-0670-11e6-8f30-2410b8648525.png) Digiturk reklamını duyunca hemen kapattım, İngilizce SS aldım

**Comment by sener05** [comment]
Birde android 6.0 gelecek mi bize. Gelecekse ne zaman acaba? Resmi note 2

**Comment by sener05** [comment]
Birde android 6.0 gelecek mi bize. Gelecekse ne zaman acaba? Redmi note 2

**Comment by raoc999** [comment]
ertanx: Görüntüde yazan kelimeler varsa çevirilecek dosyalarda değiştiririm ama zannedersem onları online çekiyor...
sener05: Evet bizim telefonlarda 6.0 alacak. Şu an bazı telefonların 6.0 beta denemesi başladı yakında gelir. General Mobile gibi anında vermesin zaten. Adamlar 6.0.1 vermişler ürüne fakat kullağa yaklaştırınca ekran kapanıyor çekince açılmıyor. Servisi aradık adamın haberi bile yok. Yazılım konusunda MIUI ve FlyMe güzel bir yol izliyorlar. Bekleyelim bakalım

**Comment by aykutyenihan** [comment]
github'dan mikeyguard dosyasına baktımda hala sağa kaydırma yanlış

**Comment by raoc999** [comment]
daha upload etmedim, ama iyiki hatırlattın. Acaba aynı satırdan mı bahsediyoruz.  "Çağrıyı açmak için sağa kaydırın" diye çevirdim ama sen başka birşeyi mi diyorsun...?

**Comment by aykutyenihan** [comment]
çağrı arama hocam farketmez ama gelen çağrıyı açmak değilde arama uygulamasını açtığı için arama yapmak için kaydırın daha mantıklı

**Comment by raoc999** [comment]
Tamam düzelttim, hatırlatman için teşekkürler, zira ben düzeltmeleri çoktan yaptım ama dosyaları tek tek elden geçirip upload ediyordum, belkide yarın ona sıra gelmeyecekti....

**Comment by aykutyenihan** [comment]
teşekkürler hocam

**Comment by MIUITurkey** [comment]
Faydalı şeylere ekle
Faydalı şeylere eklendi

Bunları

Sık kullanılanlara ekle
Sık kullanılanlara ekli

Olarak düzeltebiliriz
21 Nis 2016 18:36 tarihinde "aykutyenihan" <notifications@github.com> yazdı:
