### ISSUE TITLE
(6.4.14) Durum Bilgisi

### ISSUE THREAD

**Issue by raoc999** [ingbrzy/MA-XML-8.0-TURKISH#46]
Uygulamaların yaptığı işleri, erişimleri vb... belirten dosya son haline getirildi ve yüklendi. Anti-Spam dosyası da en son hale getirildi. Hem Stabil hemde Geliştirme sürümüne göre gözden geçirldi ve yüklendi. Redmi 3 için yeni bir dosya çevrilip eklendi

**Comment by raoc999** [comment]
Barkod Tarama güncellendi, yeni satırlar eklendi, Güvenlik yazılımı güncellendi (6.4.11) bazı değişen satırlar yeniden çevrilip eklendi. Tarayıcı yeniden düzenlenip en güncel hale getirildi. Bluetooth ile ilgili düzenlemeler yapıldı.

**Comment by raoc999** [comment]
Ayarlar dosyası 6.4.14 sürümüne göre güncellendi. Stabil ve Beta sürümlere ve Nexus telefona ait tüm tüm satırları ekledim. 3 kez kontrol ettim ama imlâ hataları olabilir. Gördükçe düzelteceğiz. 3800 satırı geçti. inç > satırını ekledim, inş. çevrilmemesi gerekir diye silinmez

**Comment by raoc999** [comment]
Uzaktan Kumanda güncellenip eklendi, Qualcomm işlemcilerin konumu hızlı bulmasıyla ilgili dosya çevrilip eklendi ve takvim güncellenip eklendi

**Comment by sedat27** [comment]
Orhan bu yeni dosya dedigin seyler yeni ozelliklermi? Cunku tum guncellemelerde yeni dosyalar oluyor ama sonucta eklenen bisey yok

**Comment by raoc999** [comment]
sedat27: Evet, fakat dediğin gibi o özellikleri bende görmüyorum çünkü bizim kullandığımız telefonlar için değiller galiba. Mesela geçen gün Qualcomm işlemcilerinin GPS'i hızlı bulması ile ilgili küçük bir çeviri ekledim, bende MediaTek var, göremem zaten. Şimdi tüm modelleri çevirmeye başladığımdan yeni yeni dosyaları ekliyorum. Stabil sürümdeki farklı dosya ve satırlarıda ekliyorum. Ayrıca sedat27 kardeşim Ad soyadını yazabilir misin, çok desteğin oldu, katkıda bulunanlara seninde ismini yazacağım.

**Comment by sedat27** [comment]
@raoc999 sagol orhan kardesim.
 Sedat Babaoğlu.
Cok buyuk incelik. ÇOK Tesekkur ederim.
Elimden daha fazlasi gelirse seve seve yaparim

**Comment by raoc999** [comment]
Rica ederim, diğer katkıda bulunan arkadaşları da yazacağım. Önemli olan çeviriyi yapmak değil hataları bulmaktır. Yoksa çeviriyi yaptım dersin meğer yarısı hatalı ise bir anlam ifade etmez. 1000 göze batan iki yanlış satır tüm yapılanı berbat ediyor....Tema, güncelleme ve bir kaç basit dosya eklendi. TeleService dosyasını baştan aşağı ele alıyorum zira 3g,4g,lte vb... ve her telefonun dosyası farklı bunları birleştirmek lazım. Bir modelin VFX dosyası far onu da çevirip ekleyeceğim..

**Comment by raoc999** [comment]
Teleservice....: Arkadaşlar iki gündür bu dosya ile uğraşıyorum. Satır sayısı 1500ü geçti. Ne deyse her modelde bir sürü farklı satır var hepsini birleştirip, çeviriyoru ve ekliyorum. Şu anda eklenmesi gereken görüntülü çağrı ile ilgili bir sürü dosya var. Şimdilik çevirip düzenlediklerimi ekledim. Öteki dosyalara geçiyorum. Ön düzeltmeleri bitirip, sonra geri döneceğim. Bu hafta benim en yoğun olduğu hafta olduğundan biraz yavaş ilerliyorum ama gelecek hafta telafi ederim.

**Comment by raoc999** [comment]
NFC ile ilgili yeni bir dosya eklendi, bir tane daha var, yaklaşık 20 dosya elden geçirildi ve yeni ufak bir kaç dosya eklendi.
