### ISSUE TITLE
( 6.4.21 ) Hatalar, Öneriler, Tavsiyeler ve Durum

### ISSUE THREAD

**Issue by raoc999** [ingbrzy/MA-XML-8.0-TURKISH#48]
Xiaomi Kullanıcıları;
Gördüğünüz imlâ hatalarını, olması gerekenleri ve tavsiyelerinizi bundan böyle kullandığınız telefonun modelini yazarak söylemenizi rica ediyorum. Çevirinin çok az bölümü kaldı, bunlarda Mi Pay, Mi Key, NFC Hizmetleri, VFX Ses Düzeni gibi ek özellikler ve Teleservice, InCallUI gibi 5-6 dosyayı yeniden elden geçirip tüm modellerin içeriklerini ekleyeceğim... Beta ve Stabil sürümlerde olan farklı satırları birleştiriyorum, böylece her iki sürümde de ifadeler ve içerikler aynı olacak. Beta sürümden Stabil sürüme geçen aynı telefonda yabancılık çekmeyecek. :) Katkısı olan herkese teşekkür ediyorum. Özellikle ekran alıntısı yaparak yardımcı olanlara... Orhan ÇAKMAK

**Comment by raoc999** [comment]
Notlar: Hızlı arama çubuğunu düzeltildi -hermes, eğer düzelmemiş olan varsa modelini söylesin, gelecek hafta onun üzerine yoğunlaşalım. İngilizce gördüğünüz kısımlar bu haftaki derlemeden olabilir, şimdi onları çevirip ekliyorum ama görürseniz yinede hatırlatın.

**Comment by MIUITurkey** [comment]
Hocam çıkmadan önce sor desek daha iyi olacak gibi?
22 Nis 2016 09:57 tarihinde "recep.ali.orhan.cakmak" <
notifications@github.com> yazdı:

**Comment by MIUITurkey** [comment]
Sekmeler arası geçiş kısmı için de

Sekmeler arası kaydır tarzı kısa bir şey olabilir
22 Nis 2016 09:59 tarihinde hasan.ozkan.35@gmail.com yazdı:

Hocam çıkmadan önce sor desek daha iyi olacak gibi?
22 Nis 2016 09:57 tarihinde "recep.ali.orhan.cakmak" <
notifications@github.com> yazdı:

Notlar: Hızlı arama çubuğunu düzeltildi -hermes, eğer düzelmemiş olan varsa
modelini söylesin, gelecek hafta onun üzerine yoğunlaşalım. İngilizce
gördüğünüz kısımlar bu haftaki derlemeden olabilir, şimdi onları çevirip
ekliyorum ama görürseniz yinede hatırlatın.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub
<https://github.com/ingbrzy/MA-XML-7.0-TURKISH/issues/48#issuecomment-213292749>

**Comment by raoc999** [comment]
Hangi bölümden bahsediyoruz, mesela Taratıcıdaki şu satır şöyle olsun derseniz daha iyi olur aksi halde neyi aradığımı???!

**Comment by MIUITurkey** [comment]
Hocam ss attım zaten.
22 Nis 2016 10:58 tarihinde "recep.ali.orhan.cakmak" <
notifications@github.com> yazdı:

**Comment by raoc999** [comment]
Tamam sağol...

**Comment by raoc999** [comment]
Mi5 içinde dil içeriği geldi, elinde olan varsa lütfen sorunları yazsın

**Comment by aykutyenihan** [comment]
hocam ufak bişeyler buldum ama hatamı yoksa değilmi tam anlamadım 

![screenshot_2016-04-22-11-37-57_com android camera](https://cloud.githubusercontent.com/assets/16150035/14736316/113f9366-087f-11e6-8227-d4dd91d2a1b0.png)
![screenshot_2016-04-22-11-34-28_com android settings_1461314182215](https://cloud.githubusercontent.com/assets/16150035/14736324/20701fa4-087f-11e6-87aa-70ec5e525e0e.jpg)

**Comment by raoc999** [comment]
Hata değil o Dirac'in türkçe karşılığı yok, önceden onu yazmadan çeviri yapmıştım. Sonra silmeye gerek yok dedim ama kamera için hızlı çekimi düzeltmiştim ama dosyaları yeniden elden geçirmeden upload etmiyeceğim dedim. O dosyalara sıra gelmediğinden upload etmedim. Dünda Ayhan söylemese sağ-sol kaydırma dosyasını ne deyse yüklemiyordum. Sisteme ait 20 klasör kaldı gelecek hafta sorunsuz gelir inş. Diğer yerlere de bakın. Dediklerinizi anında düzeltiyorum, sadece upload bu hafta sorun yaşadım.

**Comment by ertanx** [comment]
![screenshot_2016-04-22-20-40-31_com miui home](https://cloud.githubusercontent.com/assets/18513609/14751149/2aff99e8-08d1-11e6-9702-01ee4050153f.png)
![screenshot_2016-04-22-20-41-39_com miui cleanmaster](https://cloud.githubusercontent.com/assets/18513609/14751150/2b037c5c-08d1-11e6-9777-bab70b0476c9.png)
![screenshot_2016-04-22-20-43-08_com android phone](https://cloud.githubusercontent.com/assets/18513609/14751151/2b0604a4-08d1-11e6-8e0a-c7a1af677374.png)
![screenshot_2016-04-22-20-45-39_com android settings](https://cloud.githubusercontent.com/assets/18513609/14751152/2b0b14bc-08d1-11e6-9c61-02ad285370b4.png)
Seçili yerler hocam. Bazıları yeni özellik olduğu için normal. Uygulama! yerine İptal et olabilir.

**Comment by raoc999** [comment]
Bu ingilizce yerler 6.4.21 sürümünde eklendiğinden öyle. Yeni sürümde bunlar TR olacak. Hatta ekleyip upload ettim. :)

**Comment by aykutyenihan** [comment]
yukardaki ingilizce yerlerin çoğu bende Türkçe. 
Uygula Uygulama! yerine evet hayır bence daha mantıklı ve basit, kafam karışıyor o kısımda benim hep :)

**Comment by raoc999** [comment]
Tamam Aykut haklısın, Çevirirken nereye geleceğini bilmiyorsun. Bende ünlem işereti koydum ki bu olumsuzdur ve değiştirmeye kalkarsan rahat bulayım. Bazı çevirdiğim yerlere ?! koydum ki ya cümle manasız, ya da nerede kullanıyor,,, terslik var diye... Uyarın için teşekkürler, hallediyorum,
Tüm düzeltmeleri Çarşamba, Perşembe upload edeceğim, şimdilik 2 yeni büyük dosya çeviriyorum.

**Comment by sener05** [comment]
Hocam bu 2G 3G ve LTE seçenekleri yine yok benim telefonun da. Resmi note2 prime. İyi calismalar

**Comment by raoc999** [comment]
@sener05 
Tamam Şener, Note 2 Prime'a ait Hizmet dosyalarınınıda inceliyorum, farklılık varsa ekleyeceğim, bilgilendiririm. Bu arada Mi5 ve Note 3 dosyalarını birleştirdim.

**Comment by aykutyenihan** [comment]
eline sağlık hocam arama çubuğundaki çince yazılar kaç gündür çıkmadı. baidu simgesi var ama google üstünde arıyor o kadarda olacak.

**Comment by raoc999** [comment]
Aykut sonuçta çeviri yapıyoruz müdahale şansımız yok. Birşeyler eklesen siliniyor, silsen telefon sapıtıyor. Çeviri yaparak telefon yeni birşeyler katamıyorsun.

**Comment by raoc999** [comment]
Beyler, 33 değişik bağlantı seçeneği ekledim, artık bunlara rağmen halen 4,5 veya edge ile bağlantı seçeneği çıkmıyorsa ne derseniz deyin artık.

**Comment by raoc999** [comment]
Redmi Note 2 Prime dosyası yok, Note 2 dosyalarını ekledim, umarım Note 2 Prime için ek özel satır yoktur. Tüm bağlantı şekillerini -33- dosyaya ekledim.

**Comment by aykutyenihan** [comment]
![screenshot_2016-04-27-00-05-57_com miui securitycenter_1461705732810](https://cloud.githubusercontent.com/assets/16150035/14834661/38ea8f14-0c0e-11e6-82a7-eb085a4ca63e.jpg)
