### ISSUE TITLE
-6.4.21- Çeviri Durumu

### ISSUE THREAD

**Issue by raoc999** [ingbrzy/MA-XML-8.0-TURKISH#49]
Arkadaşlar, geçen haftadan kalan bir kaç basit hatayı düzeltmiş fakat o dosyaları upload etmemiştim. Kalan 20 klasörü bu hafta elden geçirip yükleyeceğim. Bunlar kamera, drop, galeri, video vb... Ayrıca 10'a yakın küçük-büyük çevrilecek ve elden geçecek dosya var onlarında büyük kısmını ekleyeceğim. 
 Şu an itibari ile 6.4.21 sürümünde gelen yeni satırları çevirip ekledim ve siteye yükledim. Yapılan değişiklikleri buradan yazacağım. 
Orhan ÇAKMAK

**Comment by raoc999** [comment]
Kamera, Video, Sistem dosyaların tamamı bitti ve eklendi. Geriye 5-6 dosya kaldı. Mi Key, Mi Band ve 2-3 dosya yeniden çevrilip düzenlecek ve eklenecek. Ayrıca Çince olan ve Çine özgü günlerde tüm dosyalarda bütünlük olsun diye elden geçirilecek. Bir dosyada başka başka yerde başka olsun istemiyorum. Her yerde aynı olmalı. Gerçi bizi ilgilendirmiyor ama olsun. Sa-Sol-Yukarı-Aşağı yönlendirmelerde yön işaretleri ekledim. Umarım beğenmemezlik etmezsiniz. Göze hoş gözüksün diye ana başlıklar ile alt başlıklar arasında yazıları belli bir düzene getirdim ve getireceğim. Bundan sonra makyaj ağırlıklı çalışmalar olacak. Tarayıcı daki bazı sitelerin yerine Türkiyeden linkler eklemeyi düşünüyorum. MIUI Türkiye, Donanım Haber vb..

**Comment by sedat27** [comment]
Orhan
Su bilinmeyen numaralari yapamiyoruz dimi. Ornegin aramada pizza yazinca hindistandaki pizzacilar cikiyor. Bu tr olsa efsane olur

**Comment by sedat27** [comment]
![screenshot_2016-04-23-13-15-57_com android contacts](https://cloud.githubusercontent.com/assets/9906622/14760800/8b787ebe-0955-11e6-83d6-426be9c49d98.png)

**Comment by sedat27** [comment]
Telefon ayarlarinda en alt. Sesli mesaj
Mesaj ile cevapta hazir gelen mesajlar
![screenshot_2016-04-23-14-40-04_com android phone](https://cloud.githubusercontent.com/assets/9906622/14761186/6bf45746-0961-11e6-824a-72412b82648e.png)
![screenshot_2016-04-23-14-38-42_com android phone](https://cloud.githubusercontent.com/assets/9906622/14761191/7354d196-0961-11e6-9a13-a68c682b34c8.png)

**Comment by raoc999** [comment]
Sağol Sedat elden geçiriyorum, bunlar TeleService dosyasında o dosyayı tam olarak bitirmedim, birde incallui dosyası. Çünkü o dosyalara daha eklenecek çok şey var. Uyarıların için teşekkürler.

**Comment by raoc999** [comment]
Bu arada Sedat senin telefonun hangi model bende hızlı cevaplar Türkçe, diğer tüm modellere de baktım, acaba problem nerden? Bende Redmi Note 2 var. Modeli belirtirsen o modelde satırlar mı farklı ona bakmak istiyorum

**Comment by sedat27** [comment]
@raoc999 
Orhan. telefon redmi note 3. Hennessy

**Comment by raoc999** [comment]
Tamamdır kardeşim, senin telefonun satırları farklı ise ekliyorum.

**Comment by demirkayahalil** [comment]
merhabalar bende de redmi note 3 var hennessy fakat 4.5 g problemim var nasıl çözülebilir acaba?

**Comment by raoc999** [comment]
@demirkayahalil
Şöyle yapalım. Dili ingilizceye çevirelim, sorun olmuy ama Türkçe dile çevirince oluyorsa o zaman dil dosyasına ekleme yapmak lazım geliyor demektir. Lütfen bunu yapıp bana acilen dönün. Normalde diğer modellerinde tüm satırlarını ekledim. Ama atladığım yerler olabilir.

**Comment by demirkayahalil** [comment]
ingilizceye çevirdiğimde problem ortadan kalkıyor. sanırım problem bu yüzden olabilir.

**Comment by raoc999** [comment]
Tamamdır, çok teşekkürler, başka sorun sörürsen lütfen söyle, artık son işlemlerdeyiz.

**Comment by raoc999** [comment]
Benim hep savunduğum her telefonun çeviri dosyası ayrı ayrı olacak, sorun çıkınca hangi model nokta atışıyla çözeceksin. Şimdi tüm dosyaları ortak hale getirince böyle sorunlar çıkıyor. Ne deyse her telefonun şebeke dosyası bayağı bayağı farklı. Birleştirince de o satırlar eklenmemeli diye hata geliyor. Silince aksilik çıkıyor, silmeyince aksilik. biyik, sakal meselesi. Bakalım italyanlar ve almanlar nasıl düzeltmiş

**Comment by demirkayahalil** [comment]
şöyle ki ben tıklıyorum sayfaya edge hızından yavaş açılıyor sayfalar ama yukarda H+ yazmaya devam ediyor. dil değişikliği ile şimdi çözülmiş gibi ama akşam eve geçince yine bildiririm durumu.

**Comment by demirkayahalil** [comment]
bir de 6.1.14 deyim 7 güncellemesi alabilir miyim nasıl yükleyebilirm teşekkür ederim.

**Comment by raoc999** [comment]
Ürünlerle ilgi detayları çözümleri MIUI Türkiye Fan Sitesi var oradan araştırabilirsin.  H+ konusuna gelirsek sende benim gibi Avea mı kullanıyorsun. Bende Avea var bezen H+ bazen 3G bazen Edge bazen hiçbirşey yazıyor, ben sürekli Ankara içinde dolaşıyorum, öyle yerler var ki direkt Avea yazıyoruz. Doğrusu beni deli ediyor. Sürümünü güncelleyebilirsin. Birde 6.1.4 sürümünü kullanırken mi sorun yaşıyorsun. Eğer öyle ise birde 6.4.21 sürümüne terfi et.

**Comment by sedat27** [comment]
Bende de ayni telefon var 4.5g veya 3g sorunu yok. Tekrar update edip wipe deneyin olmadi. Sebekedendir avea ise. Bende turkcell var

**Comment by demirkayahalil** [comment]
Yok vodafone kullaniyorum. Is yerinde 3g ve h+ cekiyor. Ve hangisi oldugu fark etmeksizin cok hizli. Fakat eve gecince ve bazi zamanlar acayip kotu oluyor insani cileden cikariyor. Haftalik guncelkemeyi nasil indirecegimi bilmiyorum birde tesekkurler :))

**Comment by sedat27** [comment]
@raoc999 orhan arama yaptigimda kisi ismi yerinde "üç yollu çağrı" yaziyor nedendir.

**Comment by sedat27** [comment]
Bir de telefon ayarlarinda bu kisim kalmis.
"Numaramı Göster" olabilir.
![screenshot_2016-04-24-23-28-42_com android phone](https://cloud.githubusercontent.com/assets/9906622/14770214/a3babee0-0a74-11e6-916d-4d26c8108e74.png)

**Comment by sedat27** [comment]
@demirkayahalil bulunduğunuz bölgede şebeke sorunu vardır.
telefon yazılım olarak bir yerde hata verip bir yerde vermemezlik etmez.
aşağıdaki sayfayı takip edin.her cuma güncelleme var.
like tıklayın en üstteki konu en yeni olandır. girin download linkine tıklayın. telefonunuzu seçin.indirim güncelleyin

http://xiaomi.eu/community/forums/miui-weekly-rom-releases.103/

**Comment by raoc999** [comment]
@sedat27 

Dediklerini -imla hatası vb- Düzelteyim, cümle de devrik olmuş, biraz daha mantıklı hale getireyim.  Teşekkürler

**Comment by raoc999** [comment]
Arkadaşlar çeviriye rağmen şebeke türü değişiklik yapamayanlar şu yöntemi denesin: Telefon Hakkında altındaki Dahili Hafızaya 4 kez tıkladıklarında karşılarına Telefon Bilgileri gelecek, hangi hattı kullanıyorlarsa 1-2 seçim yapıp, gelen test ekranında tercih edilen şebeke bölümünü değiştirsinler ve test etsinler... Telefonun testiyle ilgili yerlerin çoğu acil değil diyerek çevrilmedi. Artık esas işler bittiğinden bu bölümleri çevireceğim. Transfer dosyasını çevirip ekledim. Bir kaç model için gerekli dosya her telefon için önemli değil ama, hedef tümünü çevirmek.

**Comment by aykutyenihan** [comment]
Tam çeviri bitecek derken mayısta miui 8 çıkıyor,  yakında dosyaların çoğu değişecek malesef

**Comment by raoc999** [comment]
çok birşey değişmez, çeviride evrim teorisine kadar herşeyi doldurmuşlar zaten. Ama satırların yerleri değişirse işte o zaman gör, işin içinden çıkılmıyor. Uğraşmamak için yeniden çevirmek zorunda kalıyorsun.

**Comment by raoc999** [comment]
MiKey yeniden çevrilip eklendi. Bundan sonra MiBand, MiPay ve VFX ile bir kaç ufak dosya var...Bu hafta gelen hataların düzeltilmiş hallerini ve yeniden elden geçirdiğim dosyaları eklemeye başlıyorum. Herhalde eskisi kadar hata filan yok ki pek geri dönüş yapan yok. Elden geçirdiğim dosyalarda genelde daha mantıklı cümleler kurmaya, imlâ hataları düzeltmeye, bulunduğu alanı taşmıyacak hale getirmeye çalıştım. Telefon Test yazılımını tam çevirmemiştim, ona da el atıyorum. Önemsiz gibi gözükse de herşeyi yazın. Teşekkürler, Orhan

**Comment by sedat27** [comment]
@raoc999 

orhan bununla ilgili bişey demedin.
 arama yaptigimda bir süre sonra kişi ismi yerinde "**üç yollu çağrı**" yaziyor nedendir.

**Comment by oguzhan5200** [comment]
Orhan hocam,
Bu sürümde herşey güzel gözüküyor. Ellerine sağlık son dönemde baya bi bozulmuştu çeviri hataları yüzünden stabilde çalışmıyordu. Daha iyi olacağına eminim. Tekrardan ellerine sağlık.

**Comment by raoc999** [comment]
@sedat27 
Sedat bu şundan kaynaklanıyor olabilir. eğer telefon GSM, LTE, WCDMA veya TD-SCDMA gibi şebeke özelliklerini aynı anda kullanıyorsa ekrana böyle bir yazı geliyordur. Bu benim tahminin, nedeni ise şebeke ile ilgili dosyada aynı anda 3 özelliği ing karşılığı olarak Üçlü Mod, esas dosyasında gösterilmesi gereken kartvizit karşılığı olarak ta Üç yollu çağrı demiş. Kartvizit ismi aradığım kişi olsun sakin deme :) çünkü o programcının yapması geren birşey. Daha mantıklı birşey ise ???? nedir bilmiyorum (card_title_threeway_call)

**Comment by raoc999** [comment]
Ufak tefek 6.4.26 ve 6.4.27 ekleri geldi, onları çevirip ekledim...Aslında çeviri yapanlara yazılım dosyaları bir hafta erken verilmesi lazım. Daha önceden ürün tasarım ve yazılımı işinde çalışıyordum. Çıkacak ürünün çevirisini biz bir ay öndecen yapıyordum fakat gerçekçi olmak lazım burası Xiaomi sitesi değil ve bizde Xiaomi çevirmeni değiliz :(( İkinci realite ise Xiaominin çevirmenleride yeni eklentileri sürümden sonra görüyor :))

**Comment by raoc999** [comment]
Non-saving account funds are displayed in Online Checking => "Sigara tasarruf hesabı kredilerdiri çevrimiçi kontrol edilirken görüntülenir" mi yoksa " Çevrimiçi denetimde tasarruf fonları da görüntülenir" mi? İşte Google ile çeviri yaparsan böyle saçma çeviri yaparsın. Sonra çeviri yapıyorum dersin. İddiali değilim ama en azından insan bu buraya saçma olmuş demeli insan. Veya Non-saving klimesin deki "Non" u "None" diye düzeltse belki anlar ama Google'a kopy-past yapan orda da çuvallar. "Hesap para tasarrufu Yok Çevrimiçi Kontrollu görüntülenir" olur..... :(:) () Neler neler.....

**Comment by raoc999** [comment]
Benden sonra kim bu projeye veya herhangi bir telefonun çevirisini yaparsa lütfen şunlara dikkat etsin:
1. Top-up = Kontör demektir, doldur demek değildir, yerine göre Kontör yükleme anlamı da içerir yani cümle içindeyken
2. Pay - Öde demektir, emir olarak, Oynat demek değildir...
3: Mi Band, aynı şeydir Mi Bant asla değildir!
4: Banka ile ilgili çevirilerde Transfer aynıdır, aktarım değildir, Withdrawn bir yerdeki parayı veya kendi parasını çekmektir
5: Band management ise Bileklik Yönetimi'dir, Bant yönetimi nerden çıktı? Ama başında Mi Band olsa o zaman isim oluyor, Bileklik demiyoruz.
6: Re-input Password kalıbı sürekli yanlış yazılıyor. Doğrusu: Şifreyi yeniden girin olmalı "Yeniden giriş şifresi" yeni çıktı herhalde
7: Tail Num. da Google çevirisiyle yapılırsa adamı çuvallatır. Telefon Numarası denilir. Tail Num: Sıra veya Kuyruk Numarasıdır. Eğer banka işlerinde kullanacaksanız Sıra Numarası dersiniz yok yazıcı gibi işlerde kullanacaksanız Kuyruk Sırası dersiniz. 
8. Bir ülkenin parasının işareti %90 paranın önünde, açıklaması ise sonunda olur. €130, 130 Euro gibi...
Benimde yaptığım hatalar varsa yazılsın lütfen, doğru bildiklerimin yanlış olması beni gocundurmaz beni daha iyiye çıkartır...

**Comment by sener05** [comment]
Hocam bu arama yapıldığında karşı taraf teli açınca üc yollu çağrı yazıyor isim yerinde.

**Comment by raoc999** [comment]
@sener05 @sedat27 
Tamam Sener; fakat ona benim yapacağım birşey yok. Benden programlama yapmamı istiyorsunuz biz sadece çeviri yapıyoruz. Üste de açıklamasını yaptım. İlgili satırın Türkçesi  Üç Yollu Çağrı, o satırı çevirmesem bu kez ingilizcesi çıkacak. yok ismi çıksın diyorsan bunu Xiaomi sitesinden yetkililere bildirmek lazım. Benim anladığım 3G, LTE, GSM aynı anda faal iken bu yazı çıksın demişler ve bu yazı çıkıyor. Onun yerine isim çıksın deselermiş sorun olmazdı... Çeviride yapılacak birşey yok, bende, sizde Xiaomi'ye yazalım, ilgili satır yerine kişi ismini gösterek bir formül bulsunlar. Çok kişi yazarsa değiştirirler...

**Comment by raoc999** [comment]
MiPay çevrilip eklendi. Sırada MiBand var...

**Comment by sedat27** [comment]
@raoc999 Orhan bu konudaki şikayeti sende yazdan daha etkili olur. Bana çok şikâyet geliyor gibilerinden.
Bende yazicam

**Comment by raoc999** [comment]
@sedat27 

Tamam...
