### ISSUE TITLE
(V6.4.28) Hata, İstek, Öneriler

### ISSUE THREAD

**Issue by raoc999** [ingbrzy/MA-XML-8.0-TURKISH#50]
Arkadaşlar;
   6.4.28 Sürümünde gördüğünüz hataları, olması gerekneler ve önerilerinizi bu başlık altında iletebilirsiniz. Xiaomi hakkında bilgi almak, ürünleri incelemek, diğer Xiaomi kullanıcıları ile irtibata geçmek için veya ürünlerin satışyla ilgili bilgilere de miuiturkiye.net sitesinden erişebilirisiniz.
   Katkılarından dolayı herkese teşekkür ederim. Orhan ÇAKMAK

**Comment by raoc999** [comment]
Evet, özellikle 3G, LTE sorunu olanlar için yeni bir dosya daha eklendi. Daha yazılımı kuramadım, site aşırı yoğun ama 2070 satırlık yeni bir dosya var MTK işlemcileri için. 1100 satırlıkta ek dosyası var. İçerisi şebeke ve işlemcilerle alakalı verilerle dolu... Yeni sürümü kurunca ne işe yaradığını göreceğiz...

**Comment by raoc999** [comment]
Dostlar bazı yerlerde İng. kalmış. Mesela Voicemail settings.... ve bir kaç yerde yaptığım değişiklikleri meğer yedek tuttuğum dosyada yapmışım. Aynı şey Hasan Kardeşimin dediği Faydalı Şeyler Ekle ile içinde geçerli

**Comment by aykutyenihan** [comment]
ayarlardan pil & performans ayarlarina girildiğinde zorla kapatma hatasi veriyor ingilizce dilde bu sorun yok.

**Comment by raoc999** [comment]
Arkadaşlar AutManager dosyası yerine AntiSpam dosyasını uplaod etmişim, o. b. hata var diyen ........... bu hatamı görmemiş maalesef. Özür dilerim. Uygulama kurarken farkettim. Buraları çevirmiştim diye... Gelecek hafta artık. Nazar değdi ve aptallığım. Kusura bakmayın.

**Comment by sener05** [comment]
Hocam bizim sorun devam ediyor 2G/3G/LTE seçenek şıkkı yine yok. Redmi note 2. Teşekkürler.

**Comment by sedat27** [comment]
#raoc999 Orhan simdi indiriyorum.
Eline saglik guzel olmustur mutlaka. 
Ama aptallik falan deme. Asla olmaz oyle sey. Ozurde dileme. Sen kimsenin parali elemani degilsin. Burda gonullu yapiyorsub. Hatalar olacak elbet. Olmasa buradanda olsa tanisamazdik:) harika isler basariyorsun.ve ozenerek yapiyorsun kardesim. Tekrar eline saglik.tesekkurler

**Comment by sedat27** [comment]
![screenshot_2016-04-30-02-05-40_com android updater](https://cloud.githubusercontent.com/assets/9906622/14931896/1648b3e8-0e78-11e6-9014-39578e35287f.png)
Yuklerken farkettim simdi. Bu ceviri hatasimi. 15 olmamalimi acaba? Yoksa yazilimsalmi?

**Comment by raoc999** [comment]
@sedat27 
O satıra ben birşey yazamıyorum çünkü orası %1s artık programda ne tanımanmışsa o geliyor. Bu haftaki hatamdan dolayı bazı şeyler eskisi gibi değil. Antispam dosyasını Authmanager yazılımına eklemişim. Alarm bile çalınca ekran uyanmıyor. Sisteme etki eden uygulama yükleyince yetki alamadığından terslikler çıkıyor. Daha önceden de böyle hatalar yapmıştım ama sistem dosyanın hatalı olduğunu söylüyordu düzeltiyordum. Birde bazı değişiklikleri yedek tuttuğum dosyada yapmışım. Geçen 2 hafta çok yoğundu, elemanlar izinde idi, hem müşterilerle ilgileniyordum hem çeviri filan yaparken bayağı karıştırmışım demek ki. Gelecek hafta şehir dışına gideceğimden bu en iyi şekilde bitsin istiyordum. Ufak  tefek şeyleri de bu hafta halledecektim.

@sener05 
Şener arkadaş, daha önce Sedat kardeşimde yazmıştı fakat bende iki telefon var ikisin de problem yok. Acaba hangi sürümü kullanıyorsun? 6.4.21 sürümüne çıktın mı? Çıkmadıysan lütfen güncelleme yap. Güncelleme yaptıysan ve sorun devam ediyorsa farklı konumlarda cihazı test edebilir misin? İngilizceye çevirince sorun gidiyor mu? Sadece Türkçe'mi sorun var?

**Comment by oguzhan5200** [comment]
güvenlik - izinler bölümü komple ingilizce kalmış

http://i.hizliresim.com/Rk2p06.png

**Comment by raoc999** [comment]
Yukarda yazmıştım, olması gerken dosya yerine başka bir dosya yüklememden kaynaklanıyor. :) Nazar değdi :)

**Comment by sener05** [comment]
Hocam 6.4.21 geçen hafta yuklemistim şimdi dün de 6.4.28 yukledim her ikisinde de maalesef yok.. Cihazim redmi note 2 32gb lik model

**Comment by oguzhan5200** [comment]
Olur o kadar. karşılıksız emek veriyorsun kimsenin yaptıgın işe laf etme hakkı yok :)

**Comment by raoc999** [comment]
@sener05 
Seninkisi Prime sürümü idi galiba, Miroslav'a bir yazayım bakalım nedendir. Sonuçta olanı çeviriyoruz, belki bir yerde eklememiz gereken yer vardır vb... En azından onda veri tabanı vardır. Bizde Prime'a ait veriler yok.

**Comment by sener05** [comment]
Çok teşekkürler hocam emeklerinize sağlık.

**Comment by aykutyenihan** [comment]
Bu haftaki sürüm çok sıkıntılı telefon hemen hemen her yerde hata vermeye başladı eski sürüme geri döndüm. Keşke yeni sürüm çıkmadan önce test etme şansı olsaydı, gerçi güncel repodan dil eklenebiliyordu eski sürümlerde ama son versiyonlarda o işte sıkıntılı.

**Comment by raoc999** [comment]
Aynen, düşün kü bende önceki sürüme döndüm, daha dikkatli olmalıyım, bir dosya neleri heba etti. Üzgünüm.

**Comment by 4fareis** [comment]
Google Keep kullanıyorum bu sürümde hata verip kapanıyor. Redmi Note 2 kullanıyorum.

**Comment by sedat27** [comment]
Bu hafta olan olmus. İdare edin yada eski surume donun. Cumaya duzelir. Ama şu 3 yollu çağrı olayi cok komik buna bir çözüm bulsalar iyi olur

**Comment by sedat27** [comment]
@raoc999  orhan bu kisim cevirilebilirmi?numara raporlama kismi.
![screenshot_2016-05-02-10-22-33_com miui yellowpage](https://cloud.githubusercontent.com/assets/9906622/14949140/16d6f728-1050-11e6-8fb2-ea6a86ed8dbb.png)

**Comment by raoc999** [comment]
@sedat27 
Bu raporlama bölümünün içeriğinide ekliyorum. Arkadaşlar bazı telefonlarda MiuiFramework dosyası da iptal edilmiş, miuisystem dosyasına geçilmiş hatalar benim yanlış dosya upload etmem ve bu değişiklikten kaynaklanıyor. Lütfen önceki sürüme dönün ve bu hafytayı bekleyin. 3 gün kaldı :)

**Comment by raoc999** [comment]
@sedat27 
Senin telefon hennessy ti galiba, Geçen haftaki hızlı cevaplar ve bu hata raporlarına baktım şimdi ikiside dosyada ekle ama neden senin telefonda ingilizce? Hızlı cevaplar bende türkçe, raporlama da türkçe sende ingilizce olmasının sebebi neden acaba?

**Comment by sedat27** [comment]
Olabilir ben bi wipe cache ile deneyeyim sonucu yazarim

**Comment by sedat27** [comment]
Wipe ise yaramadi hala ingilizce. Evet hennessy.

**Comment by raoc999** [comment]
İşler dönüp dolaşıp sonunda her telefonun verilerinin ayrı ayrı olacağı hiyerarşik düzene gidecek yoksa böyle olmuyor olamaz zaten. Normalde yapılan sistem tüm ortak satırları tek dosyadan çekiyor. Bir satırda hata varsa tüm modeller bozuluyor. Oysa her telefonunu içeriği ayrı olsa sadece bir model bozulur veya bir modelde sorun varsa sadece onu düzeltmeye çalışırsın. Evet bu zor birşey fakat birkez zor olurdu. Sonrasında haftalık çokta fazla birşey değişmediğinden gerisi kolay olurdu. Sedat'ta ki modelin satırlarınını ilgili yerlere ekledim zaten onun kullandığı telefon oldukça güncel olduğundan genel olarak onun dosyalarını baz alıyorum. Araxis Merge ile de onun orj. ing. dosyaları ile çevirinin dosyalarını tek teb bakıyorum. Tüm satırlar aynı fakat işın sonunda onun telefonununda ingilizce yerler kalıyor? Diğer taraftan bu sitede bazı veriler yok gibi? Çünkü aslında telefonun içeriğinde bizim görmediğimiz daha bir sürü apk var. Evet biz bunları kullanıyoruz, sisteme ait şeyler fakat, biz bunların doğurduğu ingilizce mesajlarla karşılaşıyoruz. Aslında MIUI geliştiricileri öyle bir yazılım yapmaları lazım ki. Sadece bir dosya genel soru, cevap vb... bir yerde toplamalılar. Mesela: Her dosyanın içinde Aç, Açık, Kapalı diye çevirmek yerine sadece bir yerde Aç diye çevireceksin, sistemin neresi ona ihtiyaç duyarsa onu ordan almalı. Böylece bütünlük olur. Hem dosyalar kısalır, hemde bir soruyu veya cevabı her yerde aynı görürsün. Kalite artar. Doğru orantı olarak, yanlışta aynı ama ne deyse 10000 satırdan fazla şeyle uğraşmamış olursun. 950 MB şimdi 650 MB kadar düştüler, işlevden birşey kaybetmedi telefonlar. Esas olarak dil dosyalarına el atarlarsa daha güzel daha stabil, ve mantıklı bir sistem kurarlarsa işler daha iyi olur. Sistem geçen hafta Authmanager dosyasına attığım AntiSpam dosyasını fark etmedi ama biryerde string bitişini farkedip tüm dosyayı siliyor ?

**Comment by sedat27** [comment]
Orhan aynen kardesim. Sistem arayuzunde bir dosyadan cekse bazi yerleri. Geri kalanlar kod ile cagirsa kelime veya cumleleri. Orayi cevirdinmi hepsi cevrilmis olur. Ornek mailde bir linke tikliyorsun "acik" yaziyor. Sistemin komple elden gecmesi lazim gelistiriciler icin.kullanici farketmez.aslinda eder dosya boyutlari cok duser.
Bakalim miui8 de neler olacak. Simdi de o geliyor.

![screenshot_2016-05-04-00-10-58_com android email](https://cloud.githubusercontent.com/assets/9906622/14998474/c1c1db66-118c-11e6-8f6e-59eea3a21fc0.png)

**Comment by sedat27** [comment]
Bunuda " Linki Aç" seklinde yapalim.
@raoc999

**Comment by raoc999** [comment]
@sedat27 
Düzelttim, teşekkürler.
Arkadaşlar 6.5.3 sürümünün gelecek satırlarını çevirip ekledim ve upload ettim. Şu yazılım kurunca nelere eriştiğine dair dosya var paragraflar ve içerikler hep küçük harfle başlamış, cümlelerde nereye gideceklerini görmediğimizden devrik, saçma filan olmuş. Şimdi baktım da bu dosyayı elden geçirmek lazım. Daha güzel, cümleler büyük harfle başlamalı, yapılan işler emirle açıklamaları ise anlaşılır olmalı, bun tekrar el atacağım. Mi Band'ın 600 kadar satırını çevirdim. 1380 satır. Çevirdiğin kadarını yükleyeceğim. Gerisini ara ara çeviririm. Bu hafta Engineer Mode adıyla gelen dosya çok fazla ve üstelik bu hafta şehir dışına gideceğimden bir sürü işim var. Engineer modda da çeviriler yaptım ama çok fazla üzerinde durmuyorum çünkü MIUI 8 deneler olacak, çeviriler boşa mı gidecek bakalım.

**Comment by raoc999** [comment]
Beyler 6.5.3 eklentilerim siliniyor :)( Hep geriden gelmek lazım galiba, ayrıca Metok dosyasına yeni ekler gelmiş. Gelen numaralar 867 ile başlıyor bunlar imei numarası ve 867 numarası TR için ??? Bilmiyorum ama ya bunlar kaçak IMEI kullananların bloklanacağı gibi birşey ya da??? Bir kaç tane yazayım
<item>868030020005342</item>
+        <item>868869020009782</item>
+        <item>866376020009020</item>
+        <item>868029020004339</item>
+        <item>868029020004396</item>
+        <item>867830020014413</item>
+        <item>865931021610910</item>
+        <item>865630021588965</item>
+        <item>867463028559179</item>
+        <item>99000763000610</item>
+        <item>869270020009378</item>
+        <item>869644020006297</item>
+        <item>869644020006305</item>
+        <item>866500024569792</item>
+        <item>865630020080659</item>
+        <item>868030020436208</item>
+        <item>868030020436216</item>
+        <item>867831027715176</item>
+        <item>867068020002977</item>
+        <item>867826020839049</item>
+        <item>865982020754357</item>
+        <item>866152023907639</item>
+        <item>868029020010229</item>
+        <item>865931029631116</item>
+        <item>867831027718758</item>
+        <item>867830020014686</item>
+        <item>869334023036307</item>
+        <item>863360029907437</item>
+        <item>869545029317827</item>
+        <item>867831027718774</item>
+        <item>867831027718816</item>
+        <item>867831027718790</item>
+        <item>865931029629250</item>
+        <item>865931029631108</item>
olan varsa baksın...

**Comment by raoc999** [comment]
Mi Band'i çevirip ekledim, bir kaç yerinde tam karşılık bulamadığımdan düzegün çeviri olmadı. Kullananlar şurası şöyle olsun diye belirtsinler. Mesela Nudge karşılığı dürtmek ama Arkadaşını dürt dersek bizim lastık Türkçede acayip mana oluyor. İleride mantıklı hale getiririz. Authmanager dosyasına el atmam lazım. ?!

**Comment by aykutyenihan** [comment]
hocam çoğu dosya sistem dosyası hiç göremeyebiliriz bile. bence çeviri bittikten sonra vakit bulundukça çevrilse kafi.
