### ISSUE TITLE
MIUI 8 Hakkında

### ISSUE THREAD

**Issue by raoc999** [ingbrzy/MA-XML-8.0-TURKISH#53]
Arkadaşlar; 

Gelecek hafta MIUI 8 geliyor, bu hafta 6.5.5 ile bu sürüm bitiyor mu? Zannedersem bitmiyecek nedeni ise bazı ürünler MIUI 8 sürümünü almayacak. Ne olmamakla benim bazı sitelerden edindiğim bilgilere göre 1S, Redmi 2, Note 4G, Redmi Prime sürümleri MIUI 8'i göremeyecek, diğer cihazlara destek devam edecek. 

MIUI hakkında edindiğiniz bilgileri yazabilirsiniz.

**Comment by aykutyenihan** [comment]
10 mayısta tanıtılır bir kaç gün içinde son çıkan birkaç modele beta versiyonları çıkar, daha sonraki haftalarda diğer modellere yayılır. Ama kullanılacak hale gelmesi yayılması vs bikaç ay. bu sürede miui7 güncellenmeye devam eder bizde kullanmaya.
