### ISSUE TITLE
Sürüm 6.5.5 için Hatalar, Öneriler ve Tavsiyeler...

### ISSUE THREAD

**Issue by raoc999** [ingbrzy/MA-XML-8.0-TURKISH#54]
Arkadaşlar bu sürümü kurup hatalarla karşılaşan veya şurası şöyle olsa daha iyi olur diye tavsiyede bulunanlar lütfen bu başlığı kullansın.Daha denemedim ama inş. bu sürümde hiç sıkıntı yaşanmaz. Benim içinde sağlam çekirdek olur. 6.5.4'e kadar olan tüm güncellemeleri ekledim. Atladığım yerler olabilir, gördükçe ve tatırlattığınızda düzeltiyorum. Bazı cümleler çok uzun, gözükmediğinden kısaltmak zorunda kalıyorum. Şimdilik Engineer Mode, VFX ve Cit adlı 3 dosya var. Bu hafta şehir dışına gidiyorum uploadları biraz geç yapacağım. Umarim gittiğim yerde en azından 3G vardır. Bu haftaki güncellemede Email uygulamasında İngilizce bölümler görebilirsiniz ki bu yeni eklenenlerden kaynaklanıyor. Çevirip ekleyeceğim.

**Comment by 4fareis** [comment]
Günlük kilit ekranı sürekli kilitleniyor

**Comment by raoc999** [comment]
Hangi model ve sürüm ne? Redmi Note 2 de sorun yok!?

**Comment by 4fareis** [comment]
Redmi Note 2 evet data/cache sıfırladım düzeldi şimdilik herhangi bir sorun yok geçtiğimiz sürümde google play keep vs çok hata veriyordu sanırım onlar düzelmiş teşekkürler.

**Comment by raoc999** [comment]
Arkadaşlar halen birkaç yerde imlâ hatası var. Bir kaç yerde Sabit yazacak yere Sabir yazmışım. Kusura bakmayın, artık onlar ve 6.5.5 güncellemelerini haftaya. Katkısı olan herşese teşşekkür ederim. Artık bu kadar sık yazmayacağım. Diğer işlere odaklanmak lazım. Aralıklı güncellemeye devam edeceğim.

**Comment by aykutyenihan** [comment]
albüm içinde Other albums diye bir yazı var muhtemelen yeni güncellemeyle gelen dosya olduğu için öyle oldu sorun değil. kalan ram miktarını gösteren kısımda G B harflari ayrı çok garip olmuş eski hal daha iyiydi ve bikaç ufak tefek yer var. Genel olarak süper bir çeviri oldu hocam eline sağlık.

![2016_05_06_16 58 14](https://cloud.githubusercontent.com/assets/16150035/15075755/b7de02e0-13ae-11e6-8512-84876bf4dd81.png)
![screenshot_2016-05-06-17-12-18_com miui securitycenter](https://cloud.githubusercontent.com/assets/16150035/15075758/bda63e5e-13ae-11e6-92ef-ff9cf50255ec.png)
![2016_05_06_17 00 20](https://cloud.githubusercontent.com/assets/16150035/15075764/c3e0bc54-13ae-11e6-95d7-410997ea83e0.png)

**Comment by raoc999** [comment]
@aykutyenihan 

Aykut dediklerini hemen düzelttip ekliyorum. Teşekkür ederim. Çeviri sizin sayenizde iyi hale heliyor, ben sadece yazıları yazıyorum..

**Comment by Tmp341** [comment]
Tahminen normal "B" ayrı 1.2G ise ayrı hesaplanıyor olabilir. Yani B byte temsil ediyor, kalan hesabını ise 1.2G veya 235M olarak hesaplıyor olabilir.

**Comment by aykutyenihan** [comment]
teveccüğü bırak hocam süper iş yapıyorsun karşılıksız. Senin gibi donanımlı bi insanın xiaomi telefon alması kullanması bizim için piyango oldu resmen, uzun süre ara arada olsa desteklersin inş.
gb olayı eski sürümlerde gb şeklindeydi geçen hafta oldu ne olduysa.

**Comment by raoc999** [comment]
O zaman bendendir, çünkü geçen hafta rakamla birleşikti 12GB iken ben GB ve Bayt yazılarını ayırdım. Tamamdır iş bende... Sadece şu Wireless Display olayına takıldım. İng. içerikleri inceliyorum. Şu MIUI 8 çıksın, tüm dosyaları elden geçireceğim. Bence dil dosyaları sürümden bir hafta önce gelmeli :) İşte... Other Albüms yeni geldi çevirip ekledim...

**Comment by raoc999** [comment]
@aykutyenihan 

Tamam aykut çözdük, %1$s B yapmışım, orada Bayt ve Giga veriden alıyor, B harfını birleştirmek lazım. Düzeltip ekledim

**Comment by aykutyenihan** [comment]
hocam bunlar beta sürümler o yüzden ingilizce olması dilin sonradan gelmesi gayet doğaldır zaten son kullanıcıya kullanması tavsiye edilmez. Sen illa güncel olayım hatasız olayın dersen stabil sürümleri kendine baz alsan yeterli, adı üstünde beta sürüm bunlar dili süper bile olsa her hafta abuk subuk hataları oluyor romdan kaynaklı. mesela ben batarya performansı yüzünden sürekli deneyip stabile dönüyorum mecbur.

bu arada yukarıda görüntü verdiğim ingilizce kalan kablosuz ekran bildirimi WfdService dosyasında muhtemelen biliyorsundur ama arama hocam.

**Comment by aykutyenihan** [comment]
senin derlemelere baktım bende göremedim o kısmı ben en iyisi sana benim cihaz için olan dosyayı atayım hocam.

**Comment by raoc999** [comment]
raocakmak@gmail.com adresimi kullan çünkü baktım göremedim. Hangi model senindi?

**Comment by aykutyenihan** [comment]
bende göremedim telefondaki dosyayı parçaladım yine yok hocam nerden çekiyor ki o metni.

**Comment by raoc999** [comment]
Ekranı tersine çevir diye altta açıklaması bile var. Aykut tlf modelin yazar mısın? Acaba bağlanan cihaz mı telefona böyle bir veri yolluyor.

**Comment by aykutyenihan** [comment]
telefon mi4c hocam. ekran yansıtma açık diyor tvye kablosuz ekranla bağlandığında sadece bildirim panelinde çıkıyor. bildirim panelinin apk sı falanmı var acaba.

**Comment by aykutyenihan** [comment]
teveccüh yazdım sonra farkedip sildim senden de bişey kaçmıyor be hocam :)

**Comment by raoc999** [comment]
Sorun yok kardeşim bende ne çanaklar var üstelik laz olduğumuzdan, Libra'da öyle bir satır yok, demek ki bağlanılan cihaz böyle bir mesaj gönderiyor....

**Comment by aykutyenihan** [comment]
nexus 4 le denedim ekran yansıtılıyor diyor hocam, tvnin göndermesi biraz düşük olasılık.

**Comment by aykutyenihan** [comment]
xperia z3 ile denedim ekran yansıtma açık yazıyor hocam her telefonda farklı yazıyor tv ile alakası yok gibi.

**Comment by raoc999** [comment]
@aykutyenihan 
Evet Aykut dediğin gibi bağlanan cihazdan kaynaklanmıyor. Gördüğüm kadarıyla öyle satırlar varkı mesela: (android.comminication.activity) rastgele yazdım. Galiba bunlar sistemin içinden birşeyler çekiyor.

**Comment by sedat27** [comment]
@raoc999 orhan kardesim. Hava durumu uygulamasini mipad gibi yapsak. Dun bugun yarin...
Tarihle cok iyi olmuyor.
![img_20160509_004213_hdr](https://cloud.githubusercontent.com/assets/9906622/15100605/1182fbda-157f-11e6-9f8a-086d608c82e2.jpg)

**Comment by raoc999** [comment]
@sedat27 
Kardeşim buradaki sorun adamlar dün, bugün, yarın yerine %s gibi bir değer koymuşlar ve o değere neyi tanımamışlarsa o geliyor
