### ISSUE TITLE
6.5.12 Hata ve Öneriler

### ISSUE THREAD

**Issue by sedat27** [ingbrzy/MA-XML-8.0-TURKISH#55]
6.5.12 sürümü içim hata ve önerilerinizi buraya yazabilirsiniz.

**Comment by aykutyenihan** [comment]
geçen hafta eksik kalan yer dışında pek hata yok aslında. 
![screenshot_2016-05-16-09-45-16_com miui home_1463381148221](https://cloud.githubusercontent.com/assets/16150035/15282319/2d3fcf70-1b4b-11e6-924f-30985ba6f33b.jpg)

**Comment by oguzhan5200** [comment]
kilit ekranında ''kilidi açmak için yukarı kaydırın'' yazısının yanında gereksiz bir işaret var.
http://i.hizliresim.com/golZpR.png

**Comment by aykutyenihan** [comment]
ok işaretlerini bilerek koymuş her yönde var

**Comment by oguzhan5200** [comment]
olmasa daha iyi olur bence çirkin duruyor. zaten yazılmıs  ''kilidi açmak için yukarı kaydırın''  diye yinede siz bilirsiniz.

**Comment by aykutyenihan** [comment]
olmasada olur tabide çok sıkıntı değil benim açımdan

**Comment by aykutyenihan** [comment]
çevirmen arkadaşa ulaşın onun bileceği iş

**Comment by Tmp341** [comment]
Kilit ekranına bağlı değişiyor o galiba. Bende mesela, önce ok çıkıyor. O ok kaybolup "kilidi açmak için yukarı kaydırın" diyor sonra.

**Comment by kesn19** [comment]
Cihazım redmi note 3 hava durumunda detaylara tıkladığımda accuweather in ingilizce sayfasına yönlendiriyor adresin linkini Türkçe olacak şekilde düzeltebilirmiyiz?

**Comment by felixamor** [comment]
Evet kilit ekranı açmak için yukarı kaydırın yazısının sonundaki ünlem işaretine benzeyen ok sanki bilinçli yapılmış gibi değil bir kod hatası gibi duruyor. 
Orjinal global romlarda bu kısımda sadece "kilidi açmak için kaydırın" gibi kısa bir ifade yer alıyor. bence böyle olması daha iyi olur...
Ayrıca Posta uygulaması yerine "E-Posta" daha doğru olur bence. 

Telefon ayarlarında sabit arama numarası yerine "Sabir Arama Numarsı" yazıyor..

Yazı boyutundaki tablo ingilizce kalmış (M-X-XL vs. gibi), birde en küçük boyuta küçüçük diye yazılmış orjinal romda "Çok küçük" diye geçiyor bu bölümde..



Tabi bunlar ufak ayrıntılar, geneli itibariyle çeviri oranı ve doğruluğu çok iyi..

**Comment by Tmp341** [comment]
Geliştirici niye böyle bir şey yapsın ki? Bakın bu resim benim kilit ekranımdan:

![screenshot](https://cloud.githubusercontent.com/assets/1683388/15347688/9e66cf32-1ccc-11e6-8572-05dcf61a4c59.gif)

Kilit ekranını yapan kişi, önce ok sonra yazı olacak şekilde yapmış.

Miui Temalar uygulamasında, ios kilit ekranlarına bakın, o okun olmadığını göreceksiniz. Kısaca bunu tema tasarlayıcı ekliyor.

**Comment by felixamor** [comment]
Bizim bahsettiğimiz ok o değil.

**Comment by Tmp341** [comment]
`<string name="status_bar_recent_guide_all">"Kapatmak için yukarı kaydırın ▲
Kilitlemek için aşağı kaydırın ▼"</string>
  <string name="status_bar_recent_guide_bottom">Kilitlemek için aşağı kaydırın ▼</string>
<string name="status_bar_recent_guide_top">Kapatmak için yukarı kaydırın ▲</string>`

Buradaki kodlarda, evet tercüme eden arkadaş elle koymuş. İspanyolca olanda yok:

`<string name="status_bar_recent_guide_all">"Desliza hacia arriba para cerrar
Desliza hacia abajo para bloquear"</string>
     <string name="status_bar_recent_guide_bottom">Deslizar abajo bloquea</string>
<string name="status_bar_recent_guide_top">Deslizar arriba cierra</string>`

**Comment by 4fareis** [comment]
Basit şeylerde takılıp kalmayın çeviri yapan arkadaşlara ve destek verenlere teşekkür ederiz eliniz kolunuz dert görmesin

**Comment by aykutyenihan** [comment]
arkadaşlar gördüğünüz hataları ekran görüntüsü şeklinde yada ayrıntılı belirterek raocakmak@gmail.com adresine mail olarak belirtin. çevirmen arkadaş yoğun olacağım bir süre demişti yani buraya bakamaz bir süre. bence çeviri eksiksiz miui 8 çıksın sonra bakacaz neler değişecek.

**Comment by sedat27** [comment]
Evet ok sonradan kondu. Dekoratif amaçlıydı. Ama kaldırılabilir. Orhan bu aralar meşgul bir daha ki guncellemede düzeltilir. Başka hata yoksa bu olsun sadece ...

**Comment by sedat27** [comment]
Evet hava durumu doğru. Ufak bi kod hatası. Linkte en yazan yeri tr yapılması ile bu sorun çözülür. Bi dahaki hafta

**Comment by raoc999** [comment]
@sedat27 

Arkadaşlar bu aralar çok yoğunum mailleri okuyorum fakat internet öyle adi bir durumda ki cevap yazarken ikide bir kesiliyor. Hat bile düzgün çekmiyor. "Çay topluyorum vb". Bir iki hafta sonra tüm değişiklikleri ve eksikleri gidereceğim. Basit mevzulara takılmayın. Özellikle yön simgelerine... Bir tane imla hatasını söylemeniz bulmanız çok daha önemli. Şimdiki zamanımda  iki haftalık değişiklikleri ekleyim güncellemeye çalışacağım. Ama eskisine nazaran daha iyi bir duruman geldiğimizi kabul edelim.  Çok yorulduğumdan akşamları bilgisayarı açamıyorum. Açsam başından uykuya kalıyorum. Özellikle Sedat kardeşimden haftalık başlıklar açmasını istiyorum. O başlıklar altında eksin ve önerileri görürüm. Herkese teşekkür ediyorum, ister eleştirsin, ister öneri yapsın. Bunlar bir adım daha ileri gitmemizi sağlıyor.
Orhan ÇAKMAK, Rize
