### ISSUE TITLE
Sürüm 6.5.19 İstek, Öneri ve Eleştiriler

### ISSUE THREAD

**Issue by raoc999** [ingbrzy/MA-XML-8.0-TURKISH#56]
Değerli Dostlar;
İşler yüzünden biraz ara verdim, Söz verdiğim gibi aralıklarla bakıyorum. Önceki güncllemeleri şimdi ekleyip upload etmeye çalışacağım. Siz de bu haftaki problemleri yazarsanız sevinirim. Öneri, tavsiye yazanlar lütfen altta tam ad soyadını yazarlarsa katkıda bulunanlara da onları eklerim ama bendeki asgari limiti geçmeleri lazım :)

**Comment by sedat27** [comment]
@raoc999
Orhan tamamdır. Sen açmamış olursan ben açarım.
Bu arada redmi note3 gitti mi5 pro beyaz geldi.hele şükür alabildim. Efsane cihaz tavsiye ederim. Ancak stabil surum var gecemedim daha developer versiyona. Gecicem. Bu nedenle son haftaya dair yorum yapamıyorum. Haftaya halletmiş olurum.

**Comment by sedat27** [comment]
![screenshot_2016-05-22-18-39-34_com miui touchassistant](https://cloud.githubusercontent.com/assets/9906622/15454876/f0501f14-204c-11e6-8e34-bfea0d81df2a.png)
![screenshot_2016-05-22-18-39-30_com android settings](https://cloud.githubusercontent.com/assets/9906622/15454877/f586c2ee-204c-11e6-9fc0-337468aec53a.png)
![screenshot_2016-05-22-18-39-16_com android settings](https://cloud.githubusercontent.com/assets/9906622/15454880/fb7bb7f4-204c-11e6-8fc5-e93530283be7.png)
![screenshot_2016-05-22-18-39-07_com android settings](https://cloud.githubusercontent.com/assets/9906622/15454881/01d6e5f6-204d-11e6-8eb0-7a1acfa3125c.png)
![screenshot_2016-05-22-01-29-42_com android settings](https://cloud.githubusercontent.com/assets/9906622/15454883/0692b9bc-204d-11e6-9596-d67dd3499e2f.png)

Mi5te kalan bazi ingilizceler.(gemini)

**Comment by sedat27** [comment]
Son resim yanlis olmus

**Comment by CenkayKESER** [comment]
Touch assistant bu hafta eklendi, haftayaki sürüme çevirirler.

**Comment by afmelektro** [comment]
Selam,

Çeviri yapıldıktan sonra nerde ne olduğu sanırım kontrol edilmiyor, çok yerde anlamsız ifadeler var.
Galeri : Cihazlar 5 fotoğraf silinsinmi? !!
3 seçildi!!
güvenlik: 5 izni!!
turuncu alanı örtmeyin!!
WLAN vs gibi bir çok garip-saçma çeviriler var. 
Ayrıca hala çok yerde açık-kapalı yazacağına aç-kapat yazıyor..
Celaleddin Madencanın üstadın yaptığı çeviriler (son zamanlarda eksik olsa bile)çok doğru, güzel ve kibardı. 
misal:
1 cevapsız çağrınız var
5 öğe seçtiniz
Temanız uygulanıyor.. vs gibi.
Ayrıca dil güncellemesinin 1 hafta geriden gelmesi hatalara neden oluyor.
Cihazlar MI2 ve MI3..

**Comment by sedat27** [comment]
@raoc999 
@CenkayKESER 

evet.ben genede yazayım dedim.
Nacizane katkım olsun.Belki kolaylık sağlar


touch asistant=  "Ekran Düğmesi" olarak çevirilebilir.
Enable Touch Assistant" = "Ekran Düğmesi Açık"
Customize Function"=  "Kişiselleştirme"
Auto Hide Touch Assistant=  "Ekran Düğmesi Otomatik Gizle"
Hide Touch Assistant some apps = "Bazı Uygulamalarda Otomatik Gizle"
Restore Default= Varsayalına Dön


Gizlilikte ki encrypt .... ise.
"Kilit ekranı şifresi ile cihazı şifrele" olabilir ama bu yanlışta anlaşılabilir.Sanki ekran kilidi gibi oluyo. "cihazı kodla" falan yapılsa saçma olur. tam bilemedim.

"BUTTONS POSITION" = " Düğme YERLEŞİMİ"
"Navigation Buttons" =  "Dokunmatik Düğmeler"
"Sol menü ve sağ geri tuşu"
"Sağ menü ve sol geri tuşu"

**Comment by sedat27** [comment]
Galeri : Cihazlar 5 fotoğraf silinsinmi? !!  =  "**Cihazlar**" kelimesi kaldıralabilir.

turuncu alanı örtmeyin!! ==  **Turuncu alanı kapatmayın!**

WLAN == **Kablosuz Ağ**

Arama geçmişinin detayları = **Arama geçmişi**

**Comment by sedat27** [comment]
Gallery apk içinde aşağıda ki düzeltilse olur.
Şurdan olmamış pek:) onu **Buradan da** yapsak olur

 <string name="delete_in_album">Albümde fotoğrafı veya videoyu sildiğinizde, **şurdan da** silinir:</string>
  <string name="delete_in_home_page">Albümde fotoğrafı veya videoyu sildiğinizde, **şurdan da** silinir:</string>

**Comment by sedat27** [comment]
Galeri apk da silme mesajlarında **%2$s** kodu kaldırsak yeterli bence.
tabi hata vermezse.
aslında orada cihazlar değilde. bu hesapla girilmiş cihazların adı yazmalı mantıken.ama yazmıyor. bende mipad de var.o da yazmalı ama yok

**Comment by sedat27** [comment]
![screenshot_2016-05-23-23-55-46_com android camera](https://cloud.githubusercontent.com/assets/9906622/15484277/f2da335a-2141-11e6-9180-bd75f24d633b.png)
Burada da ufak bu hata var. Kamera ayarlari Mi5

**Comment by Tmp341** [comment]
`Ekran kapalı olduğunda, Video kaydını başlatmak için Ses Seviyesini Azalt düğmesini basılı tutun. Durdurmak için bırakın.
Ekran kapalı olduğunda, Seri Fotoğraf Çekimini başlatmak için Ses Seviyesini Azalt düğmesine basılı tutun. Durdurmak için bırakın.`

Böyle olsa daha iyi gibi @sedat27

**Comment by sedat27** [comment]
@Tmp341 
Ekrana hiçbir türlü sığmaz öyle.Ancak böyle olur.

**Hızlı video kaydı için ses kısmaya basılı tut**
**Seri fotoğraf için ses kısmaya basılı tut**

**Comment by aykutyenihan** [comment]
Son MIUI 7 bu haftaki sürüm olacak yani 6.5.26. MIUI 8 sürümü ise büyük ihtimal 6.6.17 sürümü ile başlayacak o da ilk partide her telefona gelir mi gelmez mi bilinmez. Yani lafın özü bu hafta çeviri hatalarıyla sevaplarıyla kalıcı olacak miui 7 de.
