### ISSUE TITLE
Sürüm 6.5.26 Hatalar ve İstekler

### ISSUE THREAD

**Issue by raoc999** [ingbrzy/MA-XML-8.0-TURKISH#57]
Daha önceden de belirttiğim gibi işlerin yoğunluğundan yaklaşık 3 hafta çok az güncelleme yapabildim. Arkadaşların belirttiği tüm istek, öneri ve eklentileri düzeltip bu haftaki sürümüne yetiştireceğim... Bu zaman zarfında arkadaşların belirttiği hataların ve çeviri yanlışlarının bir kısmını gördüm ve düzenledim. Perşembe günkü son upload'ı yapana kadar esas dosyaların üzerinden geçeceğim. Destekleriniz için teşekkürler. Birde Celalleddin kardeşimizin çevirisi güzelde katılıyorum. O arkadaşın mesleği bu işlere çok yakın ve bu işe ilk el atmasından dolayı da onun ismini katkıda bulunanlardan hiç silmedim. Bu hafta Hermes için yazılım daha gelmedi, üstelik köklü değişiklikler yok. MIUI 8 gelmeden tüm güncellemeleri bitirmek istiyorum. Geçen hafta dil dosyalarını indirip eve gittim fakat, dosya bozuk indi. Bir daha şehir merkezine inmedim, artık bir ay işler hafiflediğinden haftalık güncellemeleri takip edeceğim... Anlayışınız için teşekkürler.

**Comment by sedat27** [comment]
Orhan, sıkinti yok kardes. O kadar acil bi durum yok. Gecen hafta yazilanlara baksan yeter. Hata degil sadece anlam ve icerik duzenlemeleri zaten. Bu hafta yaparsan miui7 kapanir herhal..

**Comment by aykutyenihan** [comment]
bencede acil bi durum yok çeviri gayet güzel seviyede eksikler genelde son değişiklikler. Zaten bu haftaki miui7 son sürümdü,  15-20 gün sonra miui8 başlayacak. miui7 bu şekilde kaldi artik. stabil sürümler biraz geride kaldı o kötü oldu son çeviriyle derlenseydide öyle kalsaydi ama sağlık olsun. 
emeğin için teşekkürler

**Comment by Tmp341** [comment]
Miui 8 tüm resmi sürümler için Haziran ayının sonunu bulur diyorlar.

**Comment by aykutyenihan** [comment]
17 haziranda ilk beta gelecek bi aksilik olmassa.

**Comment by CenkayKESER** [comment]
Miui 8 için ilk xiaomi.eu sürümü yayınlandı. Sanırım çevirideki farklılardan dolayı sınırlı sayıda dil dosyası eklenmiş. Türkçe dilin nasıl ekleneceği hakkında bilginiz var mı? MIUI 8 için ayrı github repoları açmaları gerekecek. Denemek isterseniz ilgili sürümler;
https://xiaomi.eu/community/threads/miuiv8-alpha.31903/
http://en.miui.com/thread-288025-1-1.html
Ben concro için sızın ilk alpha romları denemiştim, günlük kullanım için gayet yeterli düzeyde bir sürüm. Alpha olduğuna takılmayın yani.

**Comment by Tmp341** [comment]
> cant include more languages yet due to issues in initial setup layout..

Şimdilik daha fazla dil eklenememesinin sebebi düzende bulunan sorunlarmış.

**Comment by aykutyenihan** [comment]
Belli sayida cihaz için alpha sürüm çıktı çıkmasıda iyi oldu aslinda dil dosyaları erken çıkarsa beta öncesi çevirmek için zaman olur çıktığında hazır olur.

**Comment by sener05** [comment]
Orhan hocam ben redmi note2 den note 3 e gectim. Bu cihazda kararli surum yuklu simdi neler yapmam lazim acaba.

**Comment by raoc999** [comment]
Arkadaşlar bazı güncellemeleri yaptım. MIUI 8 de bu güncellemelerden devam edecek zannedersem. sener05 rumuzlu arkadaşımızda miuitürkiye veya akilli.be sitelerine bakabilir. Şu sıralar limitli ve avea sayesinde çok adi internet kullanıyorum. İnternetide çeviriye devam edebilmek için harcıyorum. 3 haftada özelliklle ayarlarda çok şey değişmiş. Onu tamamlamak istiyorum.

**Comment by sedat27** [comment]
Miui8 yukledim.cok basarili. Eger wipe yapmazsaniz app leri turkce devam edebiliyosunuz. Ama cok ceviri isi olacak gibi.:(

**Comment by ibrdd** [comment]
Merhaba, eski sürümlerde de aynı sorun vardı ama yazmaya fırsat bulamadım; miui8 ile düzelmiştir belki ama henüz tam denemedi. Kurup kaldırdım hemen. Sıkıntı şu hocam; wifi ayarlarında gizli ağa bağlanırken ağ şifresi türlerinde tüm türler görünmüyor Türkçe'de. İngilizce yapıp bağlandıktan sonra tekrar Türkçe yapınca ağı hafızada tutup tekrar bağlanıyor. Çok büyük bir problem değil ve çözümü basit ama görebildiğim tek hata o görünüyor. Emekleriniz için teşekkür ederiz.
![screenshot_2016-06-07-18-23-09_com android settings](https://cloud.githubusercontent.com/assets/19801818/15863874/6331cebe-2cdd-11e6-90ac-aa41b32afb81.png)
![screenshot_2016-06-07-18-23-47_com android settings](https://cloud.githubusercontent.com/assets/19801818/15863875/6350e862-2cdd-11e6-87c8-ba111ba9c30d.png)
