### ISSUE TITLE
6.6.2 Miui8 hatalar ve oneriler

### ISSUE THREAD

**Issue by sedat27** [ingbrzy/MA-XML-8.0-TURKISH#58]
6.6.2-3-4 Miui 8 ilk turkce surumde gordugunuz hata ve önerileri buradan iletebilirsiniz.

**Comment by sedat27** [comment]
Ayarlar:
Personel hotspot: Kişisel Ağ Paylaşımı
Second Space: İkincil Alan
Cloned App: Uygulama Klonlama
App Lock: Uygulama Kilidi

**Comment by sedat27** [comment]
![screenshot_2016-06-04-01-02-21-731_com miui securitycore](https://cloud.githubusercontent.com/assets/9906622/15793980/1d1b1146-29f0-11e6-8dda-1287758cc808.png)
![screenshot_2016-06-04-01-02-41-073_com miui securitycore](https://cloud.githubusercontent.com/assets/9906622/15793982/230ccdba-29f0-11e6-92f2-3614bb15595a.png)

![screenshot_2016-06-04-01-02-48-737_com miui securitycenter](https://cloud.githubusercontent.com/assets/9906622/15793985/297a7666-29f0-11e6-843a-bb68c5bcef06.png)

**Comment by felixamor** [comment]
Bildirim çubuğundaki hava durumu İngilizce. 
Güvenlik/Pil bölümünün yeni arayüzü İngilizce.

**Comment by raoc999** [comment]
Arkadaşlar, 6.6.7 sürümüne göre yeniden derlemeye başladım. MIUI 7 sürümünü o haliyle bırakıyor ve yeni sürümü çevirip eklemeleri gelecek haftadan itibaren yapacağım. Gerekirse tüm dosyaları sileceğim fakat silmemek daha iyi gibi... Ben Note 2 kulanıyorum. Bize daha MIUI 8 gelmediğinden, olan arkadaşlar test edip söylerler. Alfabetik sıra ile çeviriye başlayacağım. Şu sıralar İnternetin köyde çekmemesinden dolayı hızlı ilerleme yapamıyorum. Sahile 15 dk uzağız, Of'un köylerinde H+ var, Rize'de yok... :(
