### ISSUE TITLE
6.6.7/6.6.8  Sürümü

### ISSUE THREAD

**Issue by raoc999** [ingbrzy/MA-XML-8.0-TURKISH#59]
Arkadaşlar, 6.6.7 sürümüne göre yeniden derlemeye başladım. MIUI 7 sürümünü o haliyle bırakıyor ve yeni sürümü çevirip eklemeleri gelecek haftadan itibaren yapacağım. Gerekirse tüm dosyaları sileceğim fakat silmemek daha iyi gibi... Ben Note 2 kulanıyorum. Bize daha MIUI 8 gelmediğinden, olan arkadaşlar test edip söylerler. Alfabetik sıra ile çeviriye başlayacağım. Şu sıralar İnternetin köyde çekmemesinden dolayı hızlı ilerleme yapamıyorum. Sahile 15 dk uzağız, Of'un köylerinde H+ var, Rize'de yok... :(

**Comment by sedat27** [comment]
Orhan merhaba. Tamamdir sen başla. Geri donusleri yaparim. Kolay gelsin.

**Comment by raoc999** [comment]
Arkadaşlar ilk 3 dosyayı upload yaptım. Daha sıklıkla upload edeceğim. Yeni sürümde olmayan dosyaları sileceğim. Şu yapılan değişikliklerden dolayı 6.6.8 olarak devam ediyorum.

**Comment by afmelektro** [comment]
çevirilerde yığınla anlamsız-çok komik ifadeler var ve bir türlü düzeltilmiyor.

kara liste:
5 çağrılar
çağrı kara listesi
0 anahtar kelimeler

galeri:
cihazlar 5 fotoğraf silinsin mi?

silme ve seçme işlemleri genel:
3 seçildi
2 silindi

hava durumu:
diğer zamanları görüntüle

kamera 
zaman damgası ekle

Ayarlar:
ortam sesi
yeni mesaj gelince
uygulamanın ikon simgeleri 
faaliyetleri saklama

**Comment by raoc999** [comment]
Komik ifadeler farklı farklı kelimelerin bir araya gelmesinden kaynaklaniyor, bir kısmını ise 8. Arayüzü düzeltirken halledeceğim. Bazı yerlere ise şöyle olsa diye tavsiye edin. Adam "deleted" demiş bunu silindi diye çeviriyordu. Ne demek lazım? Başına sistem sayı kadar rakam ekliyor?!  Ama haklı olduğunuz yerleri tekrar üstünden gidince düzelteceğim.

**Comment by CenkayKESER** [comment]
Hocam miui 8 üzerinde yer alan İngilizce kısımları belirtmemiz istermisiniz? Mi 4 üstünde miui 8 kullanıyorum İngilizce olan bolca kısım var bizimde çorbaya katkımız olsun.

**Comment by afmelektro** [comment]
bir kelime ya da cümle tercüme edilirken birebir tercüme bazen etmek çok yanlış sonuçlar doğurabiliyor. 
misal:
<item quantity="other">%d calls</item>
bunu %d çağrılar diye çevirirseniz sonuç komik oluyor.

 çeviri yapılırken  birşeyler eklemek-çıkarmak  gerekebilir.. gereksiz uzun cümleler birkaç kelime ile ifade edilebilir.

çeviride stringler o kelime yada cümlenin nerde ne olduğunu genel olarak belirtir. 
misal
<string name="accessibility_services_title">Services</string>
bu dize erişebilirlik kısmında bir başlığı gösteriyor.

<string name="dlg_close">Close</string> 
diyalog kutusu mesajı vs gibi..

Ayrıca yıllardır kullandığımız wi-fi bir anda wlan oldu..çok komik..neden ??

**Comment by aykutyenihan** [comment]
wlan terimini her ne kadar bende sevmesemde orjinal ingilizce romda da wlan şeklinde, yani eklenen değişen bişey yok neyse o.

**Comment by sedat27** [comment]
Ayarlar:
Personel hotspot: Kişisel Ağ Paylaşımı
Second Space: İkincil Alan
Cloned App: Uygulama Klonlama
App Lock: Uygulama Kilidi
Wlan: Kablosuz Ağ

**Comment by sedat27** [comment]
Onceki baslikta resimleride paylastim.
Orhan deleted yaziyorsa ve sistem basina sayi getiriyorsa. Deleted: adet silindi . Olabilir
Yada .... adet seçildi olabilir

**Comment by sedat27** [comment]
Cevirinin nerede kullanildigini bilmeden cevirmek zor. Bunun icin derimki once ingilizce olan miui8 bi turkcelessin. Sonra anlam bozukluklarini yavastan yapariz.
Galeri evet cok degisti. Video edit falanda gelmis
