### ISSUE TITLE
6.6.17 miui8 ilk beta sürümü hataları

### ISSUE THREAD

**Issue by aykutyenihan** [ingbrzy/MA-XML-8.0-TURKISH#60]
evet arkadaşlar miui8 çıktı bayağı iş var malesef.

**Comment by aykutyenihan** [comment]
![screenshot_2016-06-17-16-03-01-835_com android settings](https://cloud.githubusercontent.com/assets/16150035/16151837/af6e212a-34a7-11e6-8dfd-090357207a0b.jpg)
![screenshot_2016-06-17-16-03-33-460_com android settings](https://cloud.githubusercontent.com/assets/16150035/16151838/af6f8fb0-34a7-11e6-90e2-8df56c85bfa4.jpg)
![screenshot_2016-06-17-16-03-43-201_com android settings](https://cloud.githubusercontent.com/assets/16150035/16151839/af740ba8-34a7-11e6-9dc2-d583bc08c996.jpg)
![screenshot_2016-06-17-16-04-39-777_com android settings](https://cloud.githubusercontent.com/assets/16150035/16151841/af751f70-34a7-11e6-8d27-06be0784efa7.jpg)
![screenshot_2016-06-17-16-05-42-057_com miui securitycore](https://cloud.githubusercontent.com/assets/16150035/16151842/af778a58-34a7-11e6-9072-25e41391c2e0.jpg)
![screenshot_2016-06-17-16-06-28-740_com android contacts](https://cloud.githubusercontent.com/assets/16150035/16151840/af74211a-34a7-11e6-8413-714c1aa91a9c.jpg)
![screenshot_2016-06-17-16-08-55-123_com android camera](https://cloud.githubusercontent.com/assets/16150035/16151844/af9626a2-34a7-11e6-90a9-2b34033b4b1d.jpg)
![screenshot_2016-06-17-16-09-13-915_com miui securitycenter](https://cloud.githubusercontent.com/assets/16150035/16151846/af974794-34a7-11e6-97aa-157c92604197.jpg)
![screenshot_2016-06-17-16-09-25-363_com miui securitycenter](https://cloud.githubusercontent.com/assets/16150035/16151845/af960618-34a7-11e6-8b1a-1c83dcb5523e.jpg)
![screenshot_2016-06-17-16-09-50-002_com miui securitycenter](https://cloud.githubusercontent.com/assets/16150035/16151843/af9604ec-34a7-11e6-8db8-4afce4beb3b7.jpg)
![screenshot_2016-06-17-16-10-53-330_com miui weather2](https://cloud.githubusercontent.com/assets/16150035/16151847/af99aa84-34a7-11e6-80a4-d0db9040f5f7.jpg)
![screenshot_2016-06-17-16-12-34-905_com miui gallery](https://cloud.githubusercontent.com/assets/16150035/16151848/af9db69c-34a7-11e6-9023-f897d769fc2a.jpg)
![screenshot_2016-06-17-15-25-52-503_com android settings](https://cloud.githubusercontent.com/assets/16150035/16151851/afbbd73a-34a7-11e6-8ffa-eb49714dbbc0.jpg)
![screenshot_2016-06-17-16-00-18-054_com android phone](https://cloud.githubusercontent.com/assets/16150035/16151850/afbbdc76-34a7-11e6-89bb-b9f6db7f37a2.jpg)
![screenshot_2016-06-17-16-00-52-562_com android settings](https://cloud.githubusercontent.com/assets/16150035/16151849/afba6a80-34a7-11e6-8a4c-f55030a5be39.jpg)
![screenshot_2016-06-17-16-01-32-343_com miui home](https://cloud.githubusercontent.com/assets/16150035/16151852/afbe904c-34a7-11e6-8ce0-72392e9635c1.jpg)
![screenshot_2016-06-17-16-02-33-460_com android settings](https://cloud.githubusercontent.com/assets/16150035/16151853/afbeef24-34a7-11e6-86e0-5cf368a47487.jpg)

**Comment by felixamor** [comment]
Alpha sürümünden itibaren hiçbir güncelleme yapılmadı repoda. 
İngilizce kalan çok yer var, çeviri yavaş ilerliyor repomuzda. Rusça ve İspanyolca repoları tamamen çevrilmiş. Yabancı hiçbir kelime yok onlarda.

**Comment by salihkiraz** [comment]
çeviriye bizde destek olalım bu konuda neler yapılması gerekiyor

18 Haz 2016 Cmt 17:19 tarihinde felixamor <notifications@github.com> şunu
yazdı:

**Comment by MIUITurkey** [comment]
ingrbrzy nin MIUI v8 eklemesi için mail attım onu eklesin yeni dosyaları
ekleyecektir ordan devam ederiz.

18 Haziran 2016 20:43 tarihinde salihkiraz <notifications@github.com> yazdı:

> çeviriye bizde destek olalım bu konuda neler yapılması gerekiyor
>
> 18 Haz 2016 Cmt 17:19 tarihinde felixamor <notifications@github.com> şunu
> yazdı:
>
> > Alpha sürümünden itibaren hiçbir güncelleme yapılmadı repoda.
> > İngilizce kalan çok yer var, çeviri yavaş ilerliyor repomuzda. Rusça ve
> > İspanyolca repoları tamamen çevrilmiş. Yabancı hiçbir kelime yok onlarda.
> >
> > —
> > You are receiving this because you are subscribed to this thread.
> > Reply to this email directly, view it on GitHub
> > <
> https://github.com/ingbrzy/MA-XML-7.0-TURKISH/issues/60#issuecomment-226944917
> >,
> > or mute the thread
> > <
> https://github.com/notifications/unsubscribe/AHGIEpKp_3qNqO4SSYRonM7xR_9wQSQXks5qM_5xgaJpZM4I4WPG
> >
>
> > .
> >
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/ingbrzy/MA-XML-7.0-TURKISH/issues/60#issuecomment-226955164>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AHIfbxuDnEkfFDzF6GhLv-1txPq1ESZiks5qNC4zgaJpZM4I4WPG>
> .
>



-- 
[image: MIUI Türkiye Forumu]

**Comment by salihkiraz** [comment]
arkadaşlar yeni xml dosyalarını şu adresten buldum.
https://github.com/Acid-miuipolskapl/v8-XML-Compare/tree/90a67be48757cfb083ae27cf43e6c64f920a82b5

**Comment by aykutyenihan** [comment]
çeviri malesef durma seviyesine geldi iyice.
