### ISSUE TITLE
Sürüm 6.6.17/18/20 ve Üstü

### ISSUE THREAD

**Issue by raoc999** [ingbrzy/MA-XML-8.0-TURKISH#65]
Arkadaşlar güncellemeye devam ediyorum, şikayetlerinizi not alıyorum şu an Tarayıcı, Dosya Gezgini, ... A harfinden m harfinin Kamerası dahil çevirdim, derledim, yükledim, Galeri dosyasını derliyorum. Birkaç dosyada Çince var onlara sonra bakacağım. Alpha sürümlerle uğraşmamam iyi oldu. Sadece Hesap makinesi ile uğraştım, gelen betada şunu gördüm ki boşuna çevirmişim. Hepsini silmişler. Alpha sürümlerde hızlı çeviri iyi değil zaten bakıyorsun gelecek hafta hepsini siliyorlar. Birkaç haftaya hepsi biter. Gelecek haftaya aksilik olmazsa S harfine kadar biter. Sizden ricam, ürün modelini söyleyerek hataları ve istekleri belirtin. Şu an Hermes, Gemini ve Nexus modelini baz alıyorum.

**Comment by felixamor** [comment]
Eyvallah hocam. Görünür göze batan yerleri şimdilik halletsek gerisi yavaş yavaş yapılır. Misal bildirim panelini indirir indirmez hava durumunu İngilizce görmek can sıkıcı. Ayrıca tarih gün/tarih/ay diye gidiyor..

Birde şu kilit ekranındaki yazı ile ilgili daha önce çok geri bildirim de bulunmuştuk ama el atılmadı maalesef. 
Global romlarda bu kısımda "kilidi açmak için kaydırın" yazıyor sadece. Bizde ise "kilidi açmak için yukarı kaydırın ^" gibi bir çeviri var. 

Kolay gelsin, elinize sağlık.

**Comment by aykutyenihan** [comment]
katılıyorum lafabetik sıraya göre gitmek yerine ilk önce önemli dosyalar çevrilse daha iyi, gerisi yavaş yavaş olur. Zaten çoğu dosya günlük kullanımda hiç görünmüyor bile, bugreport vs

**Comment by aykutyenihan** [comment]
Çeviri eksikleri genelde ayarlar menüsünde, zamanla eksikler kapanir. hocam şu son uygulamalarda ram kısmında uzun süredir hata duruyor ufak ama gözüme takılıyor. bide ana ekran ayarlarinda en baştaki kisayol taşı şeklinde olursa daha anlaşılır olur.

**Comment by CenkayKESER** [comment]
Hava durumu uygulamasını sizin çeviriye sadık kalıp yeni eklenen özelliklerle birlikte gönderdim. Size de uyarsa bir yerden bende çeviri yapabilirim. Özellikle MIUI 8 ile birlikte göze batan yerleri.

**Comment by raoc999** [comment]
Arkadaşlar 6.6.20 güncellemelerini ve güvenlik dahil çevirileri ekledim fakat bugünkü güncellemelerini çevirdiğim satırlar yok ?! Acaba bir yerde hata mı oldu diye kontrol edeceğim bu hafta ayarlardayim az kaldi
