### ISSUE TITLE
Sürüm 6.7.7/8 Hatalar - İstekler

### ISSUE THREAD

**Issue by raoc999** [ingbrzy/MA-XML-8.0-TURKISH#68]
Arkadaşlar şu an Settings'e kadarki dosyaları 6.6.30 olarak çevirip gönderdim. Ayarlardan da düzeltiklerimi ekledim. 6.7.8. sürümü ile Ayarlar dosyasına devam ediyorum. Bayram tatili ve gelen misafirlerden dolayı olmadık fireler veriyorum. Perşembeye kadar Ayarları yüklerim (6.7.8) sonraki dosyalar az ve önemsiz olduğundan kolaylıkla eklerim.

**Comment by felixamor** [comment]
Hocam elinize sağlık bu sürümde (6.7.8) göze batan tüm yerler Türkçe olmuş. Gayet başarılı.
Bu işlemlerden sonra ince ayrıntılara girersek iyi olacak. (Global romlarda olduğu gibi kilit ekranında sadece "kilidi açmak için kaydırın" gibi)

**Comment by 4fareis** [comment]
Bende son iki sürümdür kamera sürekli modlarda başlıyor siyah beyaz mod var bitane kamera uygulamasını çalıştırıyorum eskiz modda açılıyor  herşeyi denedim gene aynı

**Comment by aykutyenihan** [comment]
Çeviriden bağımsız olarak miui 8 hatalarla dolu hangi birini sayayım. Kendi adıma daha bir kaç sürüm beklemek lazım kullanmak için, miui7 daha iyi.

**Comment by sedat27** [comment]
Orhan kardesim eline sagli.
6.7.11 surumundeyim gayet guzel.
Ayarlari da halledersen nefis olacak.
Gozume carpan burasi oldu.

![screenshot_2016-07-13-13-56-00-360_com miui home](https://cloud.githubusercontent.com/assets/9906622/16817218/76ca23d4-494a-11e6-9f2e-8598f814c61a.png)
Gecmisi ara yerine arama geçmişi daha guzel olur.
![img_20160713_223853](https://cloud.githubusercontent.com/assets/9906622/16817246/9cdd7580-494a-11e6-9762-ef72c4b17617.jpg)

**Comment by sedat27** [comment]
Ben mi pro ,miui8 kullaniyorum. Hicbir hata yok. Kusursuz su anda.
Ceviride tam oldumu harika olacak

**Comment by aykutyenihan** [comment]
hocam hazır çevirirken uzun yerleride sadeleştirsen diyorum mesela arama çubuğundaki yazı gibi bikaç yer gözükmüyor ve kullanılan kalan ram kısmındaki hata her sürümde orda :)

**Comment by oguzhan5200** [comment]
Güzel gidiyor herşey ama hala stabilite sorunları var mi note pro kullanıyorum china developer rom ile arasın ciddi akıcılık farkları var. bu dil ile alakalı değil sanırım çünkü ingilizceye çevirdiğimdede aynı takılmalar devam ediyor. tavsiyem biraz ingilizceniz varsa gapps yükleyip gereksiz çince programları kaldırıp china rom kullanın. raoc99 kardeşim gerçekten güzel emek sarfediyor. her sürümü deniyorum her sürümde eksiklikler gideriliyor.

**Comment by raoc999** [comment]
Arkadaşlar önceleri de söylediğim gibi 6 ay kadar şehir dışında görev yapıyorum. -şahsı- İnternet ne deyse yok çevirdiklerimi de ekleyemiyorum. Şehir merkezine inince ekliyorum. Şu anda ayarlar dosyasını ekliyorum. Biraz dah sabır. RAM vb eksikleri yakında düzelteceğim.
