### ISSUE TITLE
Sürüm 6.7.28 Hatalar

### ISSUE THREAD

**Issue by aykutyenihan** [ingbrzy/MA-XML-8.0-TURKISH#69]
hocam ellerine sağlık %100 sorunsuza yakın bir çeviri olmuş. Teşekkür ederim kolay gelsin.

![screenshot_2016-07-31-12-06-25-755_com miui gallery](https://cloud.githubusercontent.com/assets/16150035/17275629/77ce5ad6-5717-11e6-8675-73068bce0980.png)
![screenshot_2016-07-31-11-59-03-351_com android settings](https://cloud.githubusercontent.com/assets/16150035/17275630/77d42146-5717-11e6-9f4b-52215818ade1.png)
![screenshot_2016-07-31-11-58-06-415_com android phone](https://cloud.githubusercontent.com/assets/16150035/17275647/cef012aa-5717-11e6-8ae2-be2969f53e73.png)
![screenshot_2016-07-31-12-13-15-665_com miui gallery](https://cloud.githubusercontent.com/assets/16150035/17275669/5f72d6fa-5718-11e6-94ab-88c4cc834b89.png)

**Comment by aykutyenihan** [comment]
Arama çubuğu bir süre sonra ingilizce oluyor hocam kendiliğinden.

![screenshot_2016-08-01-00-33-17-811_com miui home](https://cloud.githubusercontent.com/assets/16150035/17279559/d143f16c-577f-11e6-8c0e-f505bbfb7248.png)

**Comment by raoc999** [comment]
Arkadaşlar daha bitmedi çünkü şu an sdadece Hermes-Note 2 üzerinden gidiyorum, Mi5 modelininde eklerini yapıyorum. Bildiğiniz üzere köydeyim, bazı haftalar ummadık misafirler geliyor ve o hafta onlarla ilgilenmekten şehre inemiyorum. 6.7.21 e ait güncellemeleri atıyorum. Hermes için %90 tamam. Şimdi Gemini modelinin sıralamasını yapıyorum. Bu esnada mail atan arkadaşlara cevap yazamadım kususra bakmasınlar. (Bu sitedeki ROMlar elle kurulur, otomatik güncelleme yapmaz) (İmla hataları düzeltilecek) Sağlıcakla kalın, Son 8 klasör var

**Comment by aykutyenihan** [comment]
eksik kısımlar sürekli duruyor hocam. istersen yardım edelim?

**Comment by aykutyenihan** [comment]
![screenshot_2016-08-19-21-54-14-454_com miui gallery](https://cloud.githubusercontent.com/assets/16150035/17820975/04ca8212-6658-11e6-900d-15e4daebf376.png)
![screenshot_2016-08-19-21-53-28-605_com android calendar](https://cloud.githubusercontent.com/assets/16150035/17820980/09abdf38-6658-11e6-94d8-782f261d37f4.png)
![screenshot_2016-08-19-21-53-09-275_com miui weather2](https://cloud.githubusercontent.com/assets/16150035/17820999/138f6dee-6658-11e6-8211-5219027dbe41.png)
![screenshot_2016-08-19-21-52-57-741_com miui weather2](https://cloud.githubusercontent.com/assets/16150035/17821005/1b29a128-6658-11e6-89cc-ac1fecc29d82.png)

**Comment by aykutyenihan** [comment]
![img_20160819_220850](https://cloud.githubusercontent.com/assets/16150035/17821307/a43277be-6659-11e6-8c00-fb1eda23a769.jpg)

**Comment by aykutyenihan** [comment]
![screenshot_2016-08-20-08-28-28-353_com android thememanager](https://cloud.githubusercontent.com/assets/16150035/17829203/2f073c16-66b0-11e6-9d39-bbf5e36008b2.png)

**Comment by aykutyenihan** [comment]
![screenshot_2016-08-20-11-19-52-347_com android phone](https://cloud.githubusercontent.com/assets/16150035/17829978/1ba5ad02-66c8-11e6-8bfe-acce9f08308c.png)

**Comment by SonerYakup** [comment]
Sa mi4c üzerinde çalışmalar varmı şimdi den kolay gelsin
