### ISSUE TITLE
xml issues

### ISSUE THREAD

**Issue by ingbrzy** [ingbrzy/MA-XML-8.0-TURKISH#71]
@raoc999 check what you did http://translators.xiaomi.eu/XML_MIUI8-Turkish-tr.html

**Comment by ingbrzy** [comment]
@raoc999 please fix it... thanks

**Comment by raoc999** [comment]
Last time, I updated for 6.8.18 etc... Please re-sorting Turkish language file... Maybe said I did. But I didnt download. I need, last time, thanks your help, by Orhan

**Comment by ingbrzy** [comment]
@raoc999 at first fix your XML issues again http://translators.xiaomi.eu/XML_MIUI8-Turkish-tr.html

then I will sort them
