### ISSUE TITLE
6.8.8./11/12/15//16/18 Güncellemeleri

### ISSUE THREAD

**Issue by raoc999** [ingbrzy/MA-XML-8.0-TURKISH#72]
Arkadaşlar üsteki sürümlerin güncellemelerini yapıp ekledim. Şimdi yeniden sıraya dizip 6.8.22 güncellemesini yapacağım. 3 ürünün eklerin yaptım. Şimdi 2-3 kadar ürünü daha entegre edeceğim. Ve yazım hatalarını, cümle kısaltmalarını yapacağım. Herkese iyi testler... Hataları lütfen yazın. Orhan

**Comment by oguzhan5200** [comment]
hocam şu kilit açmak için kaydırın yazısının yanındaki   ^  yukarı işaretini kaldıralım lutfen acayip rahatsız edici görünüyor. tel. mi note pro. birde ordaki metin çok uzun ''kilit açmak için yukarı kaydırın'' yerine   sadece   ''Açmak İçin Kaydırın'' olsa çok daha şık durur diye düşünüyorum
