### ISSUE TITLE
Çeviri İle İlgili Durum!

### ISSUE THREAD

**Issue by raoc999** [ingbrzy/MA-XML-8.0-TURKISH#73]
Arkadaşlar; 6.8.22 ve 6.8.25 güncellemeleri yapılmadı. Bu hafta tüm dosyalardaki hatalar ve satır sıralamaları ile uğraştım. Çünkü yeni ürünleri ekledikçe satırlar çok karıştı. Bazen aynı dosada aynı satırı farklı farklı yerlere eklemişim. Normalde 6.8.18 sürümüne göre Hermes'i %100 bitirmeme rağmen halen bir sürü çevrilmemiş yerler görüyordum. Bunların sebebini çözmekle uğraştım. Normalde sadece yeni sürümdeki eklerin gözükmesi gerekirken böyle sorunlar canımı sıktığından, tamamen elden geçiriyor ve yeni güncellemeleride ekliyorum.  Sorun yok yani, yavaşlık devam ediyor, bayramdan sonra günlük değişiklikleri uygulayacağım. Şimdilik ek olarak Mi4 ve yeni bir model daha ekleyeceğim.

**Comment by zulkarneynfk** [comment]
hocam mrb..redmi note 3g wcdma kullanıyorum v8 in hiçbir sürümünü kullanamıyorum çekim gücü yarı yarıya düşüyor.bu problemi nasıl halledebiliriz

**Comment by raoc999** [comment]
Bu konuda teknik bir yazı yazmayı ve bunu xiaomi yetkililerine
göndermelisin bizde buradaki yetkiliye yazarız ama iş xiaomi de biter.

29 Ağu 2016 17:13 tarihinde "zulkarneynfk" <notifications@github.com> yazdı:

**Comment by zulkarneynfk** [comment]
ingilizce yok malesef :) her haftaki güncelleme de yüklemeyi yapıyorum bakıyorum sorun aynı..haftalık güncellemelerin altına kısaca çeviri kullnarak durumu yazıyorum ama problem devam ediyor:) 
teşekkür ederim ilginiz için,sizin iletmeniz daha etkilir düşüncesi ile size yazmak istedim.

**Comment by Tmp341** [comment]
@zulkarneynfk Donanım uyumsuzluğu falan olabilir mi? Eğer v7 sıkıntı çıkarmıyor fakat v8 çıkarıyorsa, @raoc999'un dediği gibi, xiaomi yetkililerine danış. Ürün resmi redmi note 3g ise sen derdini anlatan ufak bir yazı yaz (yetkililere anlatabileceğimiz gibi) çevirisini yaparım ben yollarsın.

**Comment by zulkarneynfk** [comment]
cihaz redmi note 3g wcdma, v8 in ilk güncellemesinde 3g problemi vardı.2g de çekim iyi ama 3g ye geçiş yapmıyordu..sonraki güncellemede 3g ile bağlantı sağlandı fakat şebeke çekim gücü 3/2 azaldı..açık alanda bile 2 diş çekim vardı..sonraki güncellemelerde ise aynı sorun devam etti yarıyarıya çekim az şu anda..kapalı alana girildiği anda hat çekmiyor..v7 ye geçiş yapmak zorunda kalıyorum.v7 de ise herhangi bir sorun yok.
teşekkür ederim ilginiz için.çeviri yaptığınız da ben iletişe geçerim

**Comment by Tmp341** [comment]
Şunu dene, derdini anlayacaklarını sanıyorum:
`I have a Redmi Note 3G WCDMA. On the first release of v8, there was a 3g problem. 2g was fine but i couldn't be able to open 3g. On the next release, 3g connection was provided but network signal reduced around 60 percent. Even in the open field, i couldn't be able to get 50 percent signal. Later releases weren't fixed that problem. When i enter a building, i lose the signal completely. I have to use v7, there is no problem on that.`

**Comment by oguzhan5200** [comment]
orhan hocam,

Allah aşkına şu kilit ekranındaki hatayı düzeltelim :) her kilit ekranı geldiğinde sinirim bozuluyor :(
<a href="http://hizliresim.com/1NdAL1"><img src="http://i.hizliresim.com/1NdAL1.png"></a>

**Comment by kesn19** [comment]
Hocam redmi note 3 cıhazımda kamera-galeri geçiş sorunu var. 6.8.18 sürümü kurulu. Ayrıca stabil v8.0.1 olan romda da aynı sorun varmış.

**Comment by raoc999** [comment]
Evet gördüm, moderatöre yazıyorum, gelecek haftadan itibaren daha sıklıkla güncelleme yapacağım...

**Comment by aliyoruk38** [comment]
![img_20160920_121816](https://cloud.githubusercontent.com/assets/11637852/18664757/ab80d678-7f2c-11e6-8f19-4445e7f95a65.jpg)
6.9.15 sürüm İngilizce oldu bu kısım
