### ISSUE TITLE
6.9.15 Sürümü Hata ve Eksikler

### ISSUE THREAD

**Issue by kesn19** [ingbrzy/MA-XML-8.0-TURKISH#74]
Öncelikle emeğiniz için teşekkürler. Cihazım redmi note 3 (Hennessy) bu haftaki güncelleme sonucu gözüme çarpan ingilizce yerler ve bazı anlamsız yerler şunlardır:
![img_20160919_170007](https://cloud.githubusercontent.com/assets/19407466/18667338/d4e3f412-7f38-11e6-984d-bf1cc5499649.jpg)
![img_20160919_170123](https://cloud.githubusercontent.com/assets/19407466/18667339/d4e5e240-7f38-11e6-9e13-990f026a86dd.jpg)
![img_20160919_170257](https://cloud.githubusercontent.com/assets/19407466/18667342/d4fff6a8-7f38-11e6-9eda-5f50a3970bac.jpg)
![img_20160919_170352](https://cloud.githubusercontent.com/assets/19407466/18667343/d506e1ca-7f38-11e6-93e7-469841b57420.jpg)
![img_20160919_170451](https://cloud.githubusercontent.com/assets/19407466/18667341/d4f08448-7f38-11e6-99a2-c5c71cb7f9dc.jpg)
![img_20160919_170551](https://cloud.githubusercontent.com/assets/19407466/18667340/d4edd676-7f38-11e6-96f2-ccef9a1a9a6c.jpg)
![img_20160919_170635](https://cloud.githubusercontent.com/assets/19407466/18667344/d5084cb8-7f38-11e6-8292-b3cec64364c8.jpg)
![img_20160919_170903](https://cloud.githubusercontent.com/assets/19407466/18667345/d50bc6e0-7f38-11e6-92ea-fff93457d00f.jpg)
![img_20160919_171012](https://cloud.githubusercontent.com/assets/19407466/18667348/d526bef0-7f38-11e6-9122-8d0c6a7d6d54.jpg)
![img_20160919_171109](https://cloud.githubusercontent.com/assets/19407466/18667346/d518978a-7f38-11e6-80e3-05a884edde58.jpg)
![img_20160919_171228](https://cloud.githubusercontent.com/assets/19407466/18667349/d529c3b6-7f38-11e6-8624-17f9a2d6ae28.jpg)
![img_20160919_171805](https://cloud.githubusercontent.com/assets/19407466/18667352/d54ac6ce-7f38-11e6-946f-0c9a42692a30.jpg)
![img_20160919_172030](https://cloud.githubusercontent.com/assets/19407466/18667350/d535f848-7f38-11e6-8294-d7fb44469879.jpg)
![img_20160919_172151](https://cloud.githubusercontent.com/assets/19407466/18667354/d5424184-7f38-11e6-8993-3aff841cd6ca.jpg)
![img_20160919_172549](https://cloud.githubusercontent.com/assets/19407466/18667351/d545f82e-7f38-11e6-8091-d55a8445f907.jpg)
![img_20160919_172717](https://cloud.githubusercontent.com/assets/19407466/18667353/d54d98ae-7f38-11e6-9da0-d85e938d95a1.jpg)

**Comment by raoc999** [comment]
@kesn19  bu şekilde gönderdiğin için çok teşekkür ederim. Böyle olunca sorunları düzeltmek çok kolay oluyor. İlk resimde olanlar Teleservice dosyasından kaynaklanıyor, o dosyayı tamamen bitirmiştim ama bazı sorunlar olduğundan çok önceki sürüme dönüp yeniden elden geçirmeye başladık. Bazı yerlerdeki Türkçe çeviri ifadelerinde eksik ve hatalar var doğru, neyin ne için olduğunu görmeyince; düz mantıkla çeviri yapıyorum. Bunları telefi edeceğim. Şuan okulların açıldığı hafta olmasından dolayı yoğunuz, gelecek hafta itibari ile günlük değişiklikleri yetiştirmeye çalışacağım.
