### ISSUE TITLE
6.9.22 Sürümü Bilgileri

### ISSUE THREAD

**Issue by raoc999** [ingbrzy/MA-XML-8.0-TURKISH#76]
Arkadaşlar; 

Kaynak kodu olan tüm ürünlerin eklenmesine başlandı, bu esnada söylenen imla vb. hatalarda düzeltilip ekleniyor.  E harfine kadar olan tüm dosyalar, tüm modellere göre derlenip eklendi. (6.9.22 sürümüne göre)

**Comment by aykutyenihan** [comment]
mi 4c için herhangi bir dosya lazımsa göndereyim hocam.

**Comment by raoc999** [comment]
Sağol Aykut, şu an olanları bir bitireyim. Açıkta birşey kalırsa isterim...

**Comment by raoc999** [comment]
Arkadaşlar, gelecek sürümde Galeride çoğu yer İngilizce olacak galiba, Geçiş problemlerini düzeltilecek diye kamera ve galerideki çoğu yer silindi. Çekirdeğe ait bir dosya da resmi Türkçe çevirisi yapanların ki ile değiştirildi. Bu ise pek çok modelde SD kart, depolama gibi alanların ingilizce olacağı manasına geliyor. Sonraki sürümlerde düzeltilir. Bilginize.

**Comment by Tautar** [comment]
Merhaba;
Telefonum Redmi Pro;
1- Herhangi bir mesaj geldiğinde bildirim ışığı yanıyor fakat okuduktan sonra sönmüyor sürekli yanıp sönmeye devam ediyor. Bununla ilgili bir çözüm var m acaba ?

2- Kamerdan resimleri görme problemi bu sürümdede devam ediyormu ?

**Comment by raoc999** [comment]
Kamera sorunu 6.9.22den sonraki sürümde düzelecek galiba. Bildirim ışığı ile ilgili sorun devam ediyor, ama düzelir zira şu an kullandığımız sürümler hep beta.

**Comment by aykutyenihan** [comment]
hay sizin kamera sorununuza yav... şu düzelecek diye haftalarca yarı ingilizce yarı türkçe kullanıyoruz telefonu üstelik sadece bir iki modelde sorun olduğu halde bütün cihazlar ingilizce galeri kullanmak zorunda. O arada birde stabil sürüm çıkarsa o da haftalarca hatta aylarca ingilize kalıyor. Stabil sürüm miui 7.5 kullanıyorum çıkan son sürüm stabil miui 7 ama hala ingilizce kalan yerler var öylede kaldı. böyle sorunlu olduğunu bilseydim xiaomi alırmıydım bilmiyorum.

**Comment by raoc999** [comment]
@aykutyenihan  bence bu konuda Xiaomiye söylenecek söz yok. Zira adamlar Türkiyede ürün satıp birde TR desteği vereceğiz dememişler. Kamera ve Galeri sorununa gelince; çekirdek dosyalarının büyük olmasından, dosyaları işleyemiyormuş. Şuan bir çekirdek dosyasının çevirisini kabul etmeyip resmi sürüme döndürdü. Sebebi dosya büyük. Mecburen büyük oluyor, çünkü tüm modellerin içeriklerini eklemek zorundayım bende biliyorum sadece benim telefon modelini çevirsem hiç sorun olmayacak... Kısaca Xiaominin yazılım mühendisi biraz kafayı çalıştırıp, OK gibi kelimeyi her dosyada birkaç kez çevirmek yerine net kalıpları ve soruları sadece bir dosyada bir kez yazsa..... Onlarca dosya kb seviyesine düşecek. Yıllar önce uydu alıcısı yazılımı yaparken. Sürekli çöken yazılıma, binlerce satır incelemesine son vermek için böyle bir çözüm sunmuştum. Olmaz molmaz dediler ama sonra yaptıklarında havalara girmişlerdi. Ayrıca biryeri çeviriyorsun, saatlerce uğraşıyorsun sonra bakıyorsun tüm o satırları silmişler neymiş gereksizmiş. O zaman gereksiz satırları çevirmenlere niye veriyorsun. Sadece çevrilecek satırları yazın ve tüm modelleri Kamera ise Kamera dosyasında toplayın. Ben tüm modellerde farklılık varmı diye tek tek inceliyorum. Xiaomi gibi çinliler daima kopyala üsülü ile çalıştıklarından maalesef yazılımları bir arpa boyu yol alamıyor. Gittikçe gıcık oluyorum. FlyOS, eui gibi başka projelere mi geçeyim diyorum ama hepsi aynı şey. iphone'umu özledim artık! MiDrive dosyasını çeviriyorum, gereksizmiş. Gereksizse neden telefon modellerinin içinde dosyası var ki? Çevirmene verilecek dil dosyası çeviri yapılmayacak kodlardan arındırılmış olmalı...

**Comment by aykutyenihan** [comment]
e sende dönüp dolaşıp xiaomiye kızmışsın :)

**Comment by aykutyenihan** [comment]
ayrıca adamlar destek vereceğiz demiyorlar ama bazı modellere global rom verip bazılarına vermiyorlar. bir telefona global rom vermek ne kadar zor olabilir 40 modele verirken. Bu yüzden kızıyorum xiaomiye.

**Comment by raoc999** [comment]
arkadaşlar telefon alırken şuna dikkat edin mtk işlemcili ise o telefon ucuz olur ama yazılımı pahalı olduğundan ya ona yeni sürüm gelmez, note 2 gibi yada gelse çok sonra gelir. qualcomm işlemci telefon pahalı olur ama yazılımı çok düşük maaliyetli olduğundan yeni sürümlere hızlı geçersiniz, sorunlar çabuk çözülür. Buradaki bilgiyi yazılımcılar daha iyi bilir.

**Comment by raoc999** [comment]
Arkadaşlar Mi5S ve Mi5S Plus içeriklerinide ekliyorum. Şu an sadece 6.9.29 derlemesinden iki dosya attım. M harfinden sonrakileri 6.9.29 olarak devam edeceğim. Önceden bitirdiğim dosyaları 6.9.22den 6.9.29 sürümüne derleyip siteye ekledim. Şu sıralar az değişiklik gelirken kısa sürede bitirip; Mi Drive, Mi Discover gibi ek dosyalara yoğunlaşacağım. Ayrıca Mi Band 2 çıktı onuda elden geçirmek lazım.

**Comment by aykutyenihan** [comment]
yazılım pahalı olmasından değilde mediatek çinli olduğundan işlemcinin kaynak kodlarını geç verdiği için geç geliyor, qualcomm daha açık bir şirket.

**Comment by raoc999** [comment]
İş kaynak kodda değil googleda bitiyor. Qualcoom google iyi çalışıyor, mtk iyi işlemci yapabilir ama ekip zayıf. Amd, Nvidia gibi. Nvidia MS ile çok iyi çalışıyordu. AMD yazılımda berbattı. İntelin ürünlerinde çok hatalar var fakat yazılım ekibi çok çok güçlü. Hemen açıkları kapatıyor, sürücünün beraberinde kıytırık ama tasarımı güzel şeyler verip daima iyi oluyorlar.
