### ISSUE TITLE
XMLs issue

### ISSUE THREAD

**Issue by ingbrzy** [ingbrzy/MA-XML-8.0-TURKISH#77]
@raoc999 fix your xmls issues
http://translators.xiaomi.eu/XML_MIUI8-Turkish-tr.html

**Comment by raoc999** [comment]
I'll fix it until Thursday but we have old problem came again. Going problems in passing gallery from the camera. Unable image preview. Had previously. There are about 4 in the latest version. Can you fix this? You fixed it in build 7.xx series. Orhan

**Comment by ingbrzy** [comment]
nope.. fix it ASAP.. its blocking us from building daily test builds!

**Comment by raoc999** [comment]
Thanks, I fixed all problems but new problems may arise. I'll fix it. I am combine all models. Thus, all products must be stable and the same layout.

**Comment by ingbrzy** [comment]
again...

**Comment by raoc999** [comment]
Camera preview problem continue...

**Comment by ingbrzy** [comment]
try take a new photo... somewhere you translated path to the camera photos so it cant be found now.. you have to find it and remove from your translation...!

**Comment by ingbrzy** [comment]
and fix those errors which you made http://translators.xiaomi.eu/XML_MIUI8-Turkish-tr.html

**Comment by ingbrzy** [comment]
@raoc999 fix at first your XML issues in http://translators.xiaomi.eu/XML_MIUI8-Turkish-tr.html

its blocking us..!

**Comment by raoc999** [comment]
Until now there was no error. Suddenly bugs out! I think there's something wrong. First, it should only be translated lines in the file. I upload the final file and leaving. It has become boring.

**Comment by ingbrzy** [comment]
its because you do not respect one basis rule.. never include in your translation values and defaults.. now its full of errors due to that and has to be removed.. its causing issues like with your camera app...
