### ISSUE TITLE
Önemli Bilgi 6.9.xx ve sonrası!

### ISSUE THREAD

**Issue by raoc999** [ingbrzy/MA-XML-8.0-TURKISH#79]
Arkadaşlar;

  Şu Kameradan çekilen resimleri önizleme sorununu bildirdim, bir sürü sorun çıktı. Ne gibi şimdiye kadar çevrilmiş satırlar (kamera-önizleme) çalışırken) çevrilmemesi gerekiyormuş. Eeee bunları tekrar İngilizce haline döndürüldü. Sorunlar devam ediyor. Üstelik ha bitti derken bu kez ortaya bir sürü Türkçe-İngilizce ibareler çıkmaya başladı. Şimdi silmem lazım gelen daha bir sürü satır daha varmış. Böyle saçmalık mı olur. Senin salakça hazırlanmış dil dosyasından daha bir sürü problem çıkar. Çevirmeye ne gerek var ki. Çekirdek dosyaları, stabil sürüme döndürdü. Problem düzelmedi, demek ki çeviride sorun yok, o zaman geri döndür değil mi? Sıkıldım. Saatlerce çeviriyorum, o satır çevrilmeyecek!. Çevrilmeyecek satırı ya işaretle, yada dosyada gösterme. Çevrilmeyecek satır, menüde gözüküyor! İngilizce olarak. Diğer dillerde çevrilmiş. 
  Velhasılı kelam şimdi Ayarlarda yaptığım son değişikliği atıyorum. Ve isteyen devam etsin. Veya stabil sürüm, resmi developer kullansın. Dün bir tane hata yokken bugün hiç dosya upload etmemişken dünya yer çıktı. Gerçekten çok kızdım. Birkere böyle dil dosyası olmaz. Aynı tabiri aynı dosyada 3-4 kez çevirmek demek bunların yazılımdan zerre çaktığı yok. Şimdilik askıya alıyorum.

**Comment by Tmp341** [comment]
Çevrilmeyecek satırı herkesin anlaması zor.
