### ISSUE TITLE
Sürüm 6.10.13 (Türkçe Test)

### ISSUE THREAD

**Issue by raoc999** [ingbrzy/MA-XML-8.0-TURKISH#80]
Arkadaşlar çeviri artık %95 olarak bitti. Tüm modelleri ekledim. Şu andan itibaren bu yazılımı kullanacak arkadaşlarda istirhamım Model ve Problem olarak geribildirim yapmaları.  Özellikle Türkçe yazılı yerlerde devrik cümle, imlâ hatası olan yerleri lütfen bildirim. Benim telefon Note 2 olduğundan üst telefonlarda parmakizi okuyucu var ve onunla ilgili acaba sorun var mı? Şu saatten sonra kimse çeviri berbat diye mail atmasın. Stabil RO'daki çeviri güzel diyen çıkarsa aklına şaşarım. Zira kendi yaptığım cümleyi çok iyi biliyorum. Benim mesaj yazdığım yere iletim, veya yazdığım yere ya da, mesela yazdığım yere örnek yazılmış farkı yok. Ben bu işe başlarken Celladdin'in taban çevirisini baz aldım ve buradan yazarak düzelten arkadaşlar sayesinde bu hale geldi. Berbat, kötü diyenler lütfen örneklendirsinler. Ona göre düzeltme yapayım. Yoksa saçma sapan mail atmasınlar. Ekran alıntısı yaparak gönderen arkadaşlara çok teşekkür ediyorum. Halen birkaç yerde hatalar var. Misal: Sicaklık gibi. Hava durumu TR sayfaya değilde ENG sayfasına yönlendiriyor. Ona ben müdahale edemiyorum ama söylerim değiştirirler. Lütfen gördüklerinizi yazın. Ayrıca isimlerinizde belirtirseniz, katkılar bölümün de adınız olur. Herkese şimdiden teşekkürler...
Orhan ÇAKMAK

**Comment by heyelan96** [comment]
![screenshot_2016-10-15-07-31-43-368_com miui home](https://cloud.githubusercontent.com/assets/20803990/19407434/d34ec336-92aa-11e6-962e-1374d9a2f0c2.png)
Selam abi nereye yazcamı bilemedim. Son güncellemeyle birlikte. Bi sıkıntı oldu abi tel yüzde 19a gelince com.anroid.system.. Diye giden  bi hata veriyo ana ekran sürekli kapanıp açılıyo. Şarja takınca düzeliyor. Bi anlam veremedim

**Comment by 4fareis** [comment]
Heyelan96 recovery wipe cache yapmaktan başka yolu kalmadı aynı sorun bende de oldu ama backup data yap datayı yedekle fabrika ayarlarına dönünce telefon data yı recovery den geri yükle ben yaptım şuan bi problem yok

**Comment by raoc999** [comment]
Telefonun modeli ne? Bunu bildirelim. Ayrıca bu sayede ekrana gelen cümlede devrik olmuş. Onuda düzlteyim. Raporunuz, ticari amaç için...

**Comment by heyelan96** [comment]
Redmi pro abi

**Comment by heyelan96** [comment]
Çevrim olmayan yerleri atacaktım ss almıştım bi baktım böyle bi hata aldım önce hatayı bildireyim dedim

**Comment by aliyoruk38** [comment]
![img_20161015_163400](https://cloud.githubusercontent.com/assets/11637852/19410447/678a2a82-92f5-11e6-8ae6-36c98f67ae0a.jpg)
![img_20161015_163345](https://cloud.githubusercontent.com/assets/11637852/19410448/71daff98-92f5-11e6-8e23-4ea6a449b627.jpg)

Daha fazla ücretsiz tema al daha mantıklı olur diye düşünüyorum

**Comment by heyelan96** [comment]
bu gece yeni rom yayınlamışlar. onu indirip tekrar denicem. çevrilmeyen yerlerin ssini almıştım onlarıda atarım abi

**Comment by kutlusancak** [comment]
Merhabalar gece yayımlanan romda kameradan foto ön izleme galeri geçişi çalışmıyor önceki romlarda olduğu gibi (Redmi Pro)

**Comment by raoc999** [comment]
@aliyoruk38 dediklerini dikkate alıyorum.  Birinci resimdeki içerik bende Türkçe, ikinci resimde dediğin gibi olmalı. Hangi modeli kullanıyorsun? O modele göre 1. resmin içeriğine bakayım.  Üstelik Hotspot etkin yerine iNet etkin demeli.. Yani Paylaşım veya iNet etkin diye değiştirdim. Note 2 de öyle...

**Comment by raoc999** [comment]
@kutlusancak  evet kameradan---> galeri geçişi halen çalışmıyor. Bu problemden dolayı bir sürü satırı sildik. O satırlar çevrilmeyecekmiş. Hayret değişen birşey olmamış. Demek ki satırlardan değil. Silinene satırlar yüzünden bazı yerler İngilizce!?

**Comment by raoc999** [comment]
@aliyoruk38 Şunu sormak istiyorum benim yaptığım çeviridi Mesajlar diye birşey yok. Mesajlaşma var. Stabil veya official ROM mu kullanıyorsun?

**Comment by aliyoruk38** [comment]
![screenshot_2016-10-16-00-44-26-240_com android settings](https://cloud.githubusercontent.com/assets/11637852/19413566/c6ab5e52-9339-11e6-840b-378a06b14ce6.png)
Redmi note 3 pro global developer kullanıyorum cihazda herhangi bir değişiklik yapmadım

**Comment by aykutyenihan** [comment]
o rom'un çevirisini burası yapmıyor. :)

**Comment by heyelan96** [comment]
Selam abi forumda söylemiştim. Tekrardan indirin demişlerdi yeniden yüklemişler. Ama yine aynı sorunla karşılaştım cihaz redmi pro. Tek bende olsa neyse amca oğlundada aynı sorun oldu onun cihazda note 3 pro

**Comment by raoc999** [comment]
Bu hafta pekçok satırı sildik, sorun oluyor diye. -Yöneticinin isteği ile- ben sorunları ileteceğim. Benimde gördüğüm bazı sorunlar ve ki bunlar çeviri ile ilgili, kütüphanede olmayan bazı İngilizce yerler gördüm. Bunların esas dosyaları veya nerden çektiğini soracağım. Hepsini bir derleyip salı veya çarşamba sorarım.  Temiz bir şekilde kurmanızı öneririm. Zira eski yazılımdan bellekte kalanlar olabilir Wipe/dalvik cache

**Comment by raoc999** [comment]
Sorun şu önceden %19 altına pil inince güç tasarrufuna geçilsin mi diye soruyordu şimdi soramıyor, ya çeviri satırlarından -şuç benim- ya silinene satırlardan ya da beta sürüm güçle ilgili yeni şeyler eklendi, tutmadı. Bir iki güne yazar durum bildiririm. Ayrıca bu durumda telefonu şarja takın. %20 üstü olsun. Önceki sürüme dönün veya üste arkadaşların belirttiği yöntemi kullanın. Sadece sövmeyin zira BETA sürüm, yani arıza çıkar! demektir.

**Comment by heyelan96** [comment]
Abi yanlış anlaşılmasın kişisel önce kişisel alayım. Senin işin çok zor o kadar kodlarla çevirilerle uğraş yetmeyip bide burda sorun çıkaranlarla uğraş. Bende sana söyleyim genel hatadır yukardakilerle sen iletişime geçersin anca diye. Çabana hayranım. Dediğin doğru beta sürüm her zaman bi hata çıkma olasılığı vardır yeni bişeler deneniyor sonuçta. 4fareis in dediği yöntemi denedim yine hata verdi. Olsun bi sonraki güncellemeye yada sonrasına düzeltilceğini bildiğim için sıkıntı etmiyorum. Emekleriniz için çok sağolun teşekkürler abi :) küfür eden arkadaşlarda gitsinler zamzunga iphone a falan para bayılsınlar...

**Comment by raoc999** [comment]
Beyler yazılımlar yeniden yüklendiğinden, %19 altında sorun yaşayanlar lütfen yeniden güncellesin. Ayrıca Global Beta ve Stabil ROM'larda bazı cümleler gördüm............. Github çevirilerini artık anında yapmayacağım. ROM'lar hazırlanırken teslim edeceğim. Başta çevirmeme karşı çıkanlar ve müdahale edenler, kendi çevirilerini neden kullanmıyorlar da buradaki çeviriyi alıp birkaç ufak değişiklik yapıp, kendi isimlerini yazıyorlar anlamıyorum. İlginç...  Bu durumda ilginç bir tedbir aldım. Gelecek haftadan itibaren aradaki farkları göreceksiniz :)

**Comment by oguzhan5200** [comment]
Recep kardeşim selam,
3. kez söylüyorum ama şu olaya bi müdahele etmedin. Şu simgeyi kaldır be kardeşim. Takıntı var ben de :)

[![image](http://i.hizliresim.com/PQZpR7.png)](http://hizliresim.com/PQZpR7)

**Comment by raoc999** [comment]
Arkadaşlar bu telefonda sağ-sol, yukarı-aşağı yönlerini ben ekledim. Normalda resmi olan yazılımda yok. Oğuzhan arkadaşımız gibi istemeyenler varsa kaldırayım. Çevirmen olarak benim oyum iki tane olduğundan, bir kişi için kaldırmak mı lazım yoksa, kullanım kolaylığından, telefona yabancı olanlara yardımcı olmak için kalmasından mı yanasınız.
Kalsın mı? Gitsin mi?

**Comment by kutlusancak** [comment]
Kötü durmuyor takıntılı olanlar dışında kimsenin gözüne batmaz sanırım :) yönler önemli

**Comment by raoc999** [comment]
İlluminati, Piramit, mısır, masonluk vb... gibi mi çağrıştırıyor. Yok öyle birşey...

**Comment by oguzhan5200** [comment]
''İlluminati, Piramit, mısır, masonluk vb... gibi mi çağrıştırıyor'' :) Koptum :) Bende biraz simetri hastalığı var. Aynısından cümlenin başına da koyarsan belki içim rahatlar :)

**Comment by raoc999** [comment]
Tamam bu olur, çıkartmıyalım ama ekleyelim. Aslında yer dar, kısaltınca yazı biryere kayıyor, ekleyince  yapış yapış... Hallederiz kardeşim, seni mi kıracağız.

**Comment by aykutyenihan** [comment]
ben orjinalde nasılsa öyle olması taraftarıyım, hem o oklar her yöne birbirinin aynısıda değil. Beni rahatsız etmez ama oy hakkımız varsa istemezük. :)

**Comment by 4fareis** [comment]
Yukarı işaretinin kalmasından yana oy kullanıyorum 👍

**Comment by oguzhan5200** [comment]
'' kilidi açmak için **yukarı** kaydırın '' zaten yukarı yazıyor aynı zamanda simge koymak mantıksız değil mi? Birde mi cihaz kullanan bir kişinin yön belirten göstergeye ihtiyaç duyacağını sanmıyorum ki yanlış görmediysem global romlarda sadece ''açmak için kaydırın'' yazıyor.  Aynı zaman da dikkat ederseniz aynı bölümde yazı çıkmadan önce yukarı işareti 1 saniyeliğine varsayılan olarak mevcut yinede karar sizin tabi çoğunluk ne isterse o olsun.

[![image](http://i.hizliresim.com/6mLJv9.jpg)](http://hizliresim.com/6mLJv9)

**Comment by raoc999** [comment]
6.10.17 ve 6.10.18 güncellemelerini yaptım, ama yüklemiyorum, gelecek sürüme eklenecek

**Comment by arifakinti** [comment]
Orhan mail attım görmedin galiba?

**Comment by raoc999** [comment]
Arkadaşlar şu an Note 4 aldım, global romu bir inceliyeyim dedim, şikayetler geliyor ya... stabil rom çok geriden geliyor, üstelik çoğu yerden birşey anlamadım. En son yazın biryerde güncelleme yapmıştım ve şimdilik şöyle çevireyim sonra düzeltirim dediğim yerleri kelimesi kelimesini kopyala yapıştır yapmışlar. Bence elden geçmesi lazım.... Buradaki ROMu kullanan arkadaşlar, gördükleri hataları yazıyla, resimle göndersinler ki, global sürümle uğraşan arkadaşlarda görüp, kendi projeleri için bir daha test etmek zorunda kalmasınlar onlarda düzeltsinler. Ayrıca Global ROM'da Bölge ve Yaşlı Modu gibi ek seçenekler var. Buradaki ROMda yok, bunuda eklememiz lazım. Mesela bendeki Note 2 de Bölge seçeneği. olmadığından varsayılan Hindistan geliyor bu sefer Tema Mağazası Hint Temaları ile dolu ki hiç bir tanesini sevemedim. Hintlilerin kafası çöl galiba. Tek renk tonu var kum... Kısaca hataları, istekleri sadece bu site üzerinden gönderin. 6.10.19 güncellemelerini de yaptım. Aksilik olmazsa yarına güncellerim. Şimdilik şu note 4u rootlamam lazım, bu işe global romu kullanmak istememden başladım. Oğuzhan nasıl sadece bir yukarı tuşuna takılıyorsa bende imlâ hatalarına, saçma uydurukça kelimelere takılıyorum.

**Comment by aykutyenihan** [comment]
keske note 4 almasaydın hocam onunda şimdi pro, snapdragon versiyonu çıkar mediatekler yalan olur :)

**Comment by arifakinti** [comment]
Yazacak bir sürü şey var orhan. 2 3 tane olsa neyse.

**Comment by raoc999** [comment]
@arifakinti 

Yaz kardeşim, ha mail ha burası, başlamak bitirmenin yarısı. en azından birkaç tane yazarsın. İngilizce kalan kısımları yazma. Türkçede devrik, eksik olan yerleri yaz. İngilizce yerler genelde yeni sürümlerden kaynaklanıyor ki onları bir sonraki haftada düzeltiyor. Hemen yazarsan yarına yetiştiririz.

**Comment by raoc999** [comment]
Bu haftalık geribildirimler kapandı! 6.10.20 de gelecek tüm değişiklikleri güncelledim ve yükleyeceğim. Hava Durumu nete bağlanınca ENG sayfasına gidiyor. Bunu benim düzeltmem imkansız. Eğer Ayarlarda Bölge seçme seçeneği olsa hiç sorun olmayacaktı ama modifiye edilmiş bu ROMlarda böylebir seçenek yok, oysa Resmi ROMda var. Türkiyeyi seçince direkt TR sayfası açılıyor. Kamera olayında ise Çekilen resimlerden sonra önizleme yapınca ilk kullanımdan dolayı Hizmet Şartları ekranı gelmeli fakat o ekran çok düşük bir anlık gözüküp geri dönüyor. Herhalde çözülür... Detaylıca bildireceğim. Diğer bir hususta Ayarlarda bazı tabirleri İng çevirisinden farklı yaptım. Mesela TRsi Kişi listesini yapılandır olan seçeneği Hesap listesini yapılandır gibi yaptım nedeni ise bazı yerlerde anlatmak istediklerini birebir çevirince anlamıyorsun. Burada da Mi, Google vb... hesabındaki kişilerden bahsediyor ama ing. çok farklı.... Menüleri tek tek inceliyorum, Parmakizi ile ilgili cümleleri düzeltiyorum. Aslında tüm içeriği yeniden daha anlaşılır ve kolay, göze hoş gelecek şekilde düzenliyorum... Gelecek 6.10.20 sürümünde görüşmek üzere....
Orhan

**Comment by oguzhan5200** [comment]
6.10.20 türkçe dil hiç yok :) 
Mi note pro :)

**Comment by raoc999** [comment]
Sana özel Oğuzhan. Artık yukarı işaretini bir daha görmeyeceksin :):) Galiba compiler yaparken hata yapmış vb... Söyliyeyim. Bakalım nedenmiş. Bu arada TR yokken. Bak bakalım ayarlar altında Dil hariç bölge ayarı varmı regional ve lite mode var mı. Eğer varsa demek ki bunlar bölge ve lite modu kaldırıyorlar

**Comment by oguzhan5200** [comment]
suikast resmen :) kaldırdım yeniden yüklemem lazım :( hiç ugrasamıycam valla :)

**Comment by arifakinti** [comment]
Orhan bu mesajindan sonra senin özürlü olduğun kanaatına vardım. Ben sana mail atıyorum sen buraya cevap yazıyorsun. Ulan maile cevap yazsana. Demek burdan yazsak mail den cevap verecem. Allahım sabır ver. Ve bu saatten sonra sen varsan eu da ben yokum. Kullanmıyorum artık. Lanet gelsin yapacağın çeviriye. Bir sürü anlatım bozukluğu devrik cümle var, burdan tek tek resim mi yukleyim. İki dk sosyal hesaplardan göndereyim diyorum yok buraya yaz diyorsun. Bir iki tane olsa zaten yazarım. Birsürü var ama. İngilizce yer var diyorum, diyorsun ki yeni surumden kaynaklı. Benim gördüğüm ingilizce yerler en az 3 4 sürumdur var ama. Nasıl oluyor bu? Bir çeviri yapacaksın ama altından kalkmamiyorsun. Bırakta işin ehli insanlar yapsın. Birde global Devoloper e laf atıyorsun. Allah rızası için biri redmi note 3 Pro global dev sonra eu dev kurşun. Hangisi daha kullanışlı yazsın buraya da bu gafil görsün. Bu yazdıklarıma mail deki gibi mesaj yazma bak. Yok 6 aydır rize deydim yok yetiştiremedim falan yazma. Kaç aydır burdasin hala aynı çoğu şey. Madem yoksun yetistiremiyon yukardaki tavsiyeme uy, işi ehline bırak.
