### ISSUE TITLE
Build 6.10.13 issues

### ISSUE THREAD

**Issue by raoc999** [ingbrzy/MA-XML-8.0-TURKISH#81]
@ingbrzy 

Hi, We have some problems;

There are new problems. The most important of these:
1. If the battery drops below 19%; A: Can not switch to power saving and screen back and forth.
b: Connect the charger to think improving. Going problems.
C: Some models; com.android.systemui stopped

2. Camera ---> Gallery problem continues ...

I do not know if there are problems in other languages? We can delete all unnecessary files and rows in Turkish.

I write comes new problems. 
Orhan CAKMAK

**Comment by ingbrzy** [comment]
5.1..? download roms again... should be fixed... then check whats translation issue and whats not by switching to EN lang...

**Comment by raoc999** [comment]
ok

**Comment by raoc999** [comment]
Hi;
I think you need to make a correction on this page. Is it because I passed the test, or did it go? "Turkish (Celaleddin, ekilci )" -> Turkish (raoc999 or Orhan CAKMAK)

https://xiaomi.eu/community/threads/6-6-16-17-18-miui-8.32197/
Thanks

**Comment by raoc999** [comment]
Now I bought Note 4. Official ROM installed. Camera -> Gallery have problems. The problem with the main software. not in translation.

**Comment by raoc999** [comment]
In software on this site; Theme shop just India, not official.

**Comment by raoc999** [comment]
Offical ROM has: There region setting, but we dont have

**Comment by raoc999** [comment]
I will find and insert our language

**Comment by ingbrzy** [comment]
Redmi Note 4 with you Turkish translation has same issue or Global ROM..?

There are no Turkish Themes yet...

**Comment by raoc999** [comment]
Theme problems with our roms. I know not Turksih theme. Our roms hasnt "region" setting. I think default option İndia. If open theme manager we see India site. But Official ROM has open orjinal Theme Site. I will find differents for region settings ( official and unofficial setting file ). We are missing region setting. I will report

**Comment by ingbrzy** [comment]
nope.. its ok... India is set for get more themes.. other regions has limited sources... less than half of india...

**Comment by raoc999** [comment]
@ingbrzy 
Camera -> Gallery: current issues in transition: the first time asks terms of service. In the meantime, back. If you accept the terms of service, no problems. However, it passes very quickly, going back. There's something wrong about the Terms of Service. (For Gallery) I installed Note 4 software. I accept the terms of service quickly. Now, no problem. However, the software may be in the future. Terms of Service should wait. Not wait and was continuous loop.

**Comment by raoc999** [comment]
Additional problem: we open details of the weather situation; We're going to the page in English. m.accuweather.com/eng/........---> m.accuweather.com/tr/

**Comment by ingbrzy** [comment]
in gallery - whats translation issue there?

weather - not possible with translation..

**Comment by raoc999** [comment]
I mean

1. Weather: Add Regional settings possible go to Turkish Page, but not regional in setting (but official rom has)
2: Kamera to Gallery problem in Turkish., English language does not. So is there a problem with the translation? (%s, %d etc) I'll look.
I am uploading last fixes. I will correct mistakes. Thanks your help.

**Comment by raoc999** [comment]
No Turkish language in Mi Note Pro

**Comment by ingbrzy** [comment]
not possible...

**Comment by ingbrzy** [comment]
ah great.. you touched framework-res.apk... thats why...

**Comment by ingbrzy** [comment]
fixed https://github.com/ingbrzy/MA-XML-8.0-TURKISH/commit/7d2aa8bb7af5d86c05b09683a52705b339e2676e

Never change that again!!!!!

**Comment by raoc999** [comment]
I am big problem, right.... Thanks, I will...
