### ISSUE TITLE
6.10.20 issues

### ISSUE THREAD

**Issue by raoc999** [ingbrzy/MA-XML-8.0-TURKISH#84]
We are using %XX format not use XX%.... Getting an error in power savings. When? It falls below 19% power. So we are going to use as 19%. two lines is making trouble in systemui.apk file. Eng:%d%% -> Tr %%% d
Maybe it's just as though %1s?

**Comment by ingbrzy** [comment]
![dfg_2016-10-28-20-47-47](https://cloud.githubusercontent.com/assets/1762519/19818432/0dd3630e-9d50-11e6-92a9-beb6afcf8243.png)

**Comment by raoc999** [comment]
Thanks, lastly
