### ISSUE TITLE
Sürüm 6.10.27 Hataları-İstekler-Problemler

### ISSUE THREAD

**Issue by aykutyenihan** [ingbrzy/MA-XML-8.0-TURKISH#85]
![img_20161029_204120](https://cloud.githubusercontent.com/assets/16150035/19831764/b0b451bc-9e1a-11e6-975f-3f3d98993ccd.jpg)
![img_20161029_204146](https://cloud.githubusercontent.com/assets/16150035/19831765/b0b60a48-9e1a-11e6-9a51-0123c409da39.jpg)
![img_20161029_204318](https://cloud.githubusercontent.com/assets/16150035/19831766/b0b649ea-9e1a-11e6-9110-1a2da9e9384f.jpg)
![img_20161029_204629](https://cloud.githubusercontent.com/assets/16150035/19831775/ed583d0e-9e1a-11e6-9aef-323317057e67.jpg)
![img_20161029_204259](https://cloud.githubusercontent.com/assets/16150035/19831776/ed5ad3d4-9e1a-11e6-89e4-394b27b2fc98.png)

**Comment by aykutyenihan** [comment]
![screenshot_2016-10-30-23-49-36-240_com miui home](https://cloud.githubusercontent.com/assets/16150035/19839923/069a5188-9ef4-11e6-9423-42977a52e2f7.png)
![img_20161030_235213](https://cloud.githubusercontent.com/assets/16150035/19839924/069bd2c4-9ef4-11e6-87a1-d040600c24c1.jpg)

**Comment by raoc999** [comment]
Çok sağol Aykut... Düzelttim. Sadece Profile denilen İng. yer kaynakta yok. Diğer dillere bakacağım. Birde şöyle birşey gördüm. Almanca dilinde İng. kaynaktan fazla şey var. Bende Almancadan ekliyorum. Özellikle Kablosuz Ekranla ilgili şeyler Almanca da var İng. yok
@aykutyenihan

**Comment by raoc999** [comment]
Bu arada Parmakizi ile ilgili yerlerde İng. kısımlar kalmış. Bunları ben upload ettim, düzelteyim derken bunları da moderatör silmiş. Tekrar ekledim. Birde Note 4 için şöyle bir hata var. Pil seviyesi %19'a düştüğünde (fix edilmiş haliyle) ekran kapalı ise ve Tasarruf moduyla alakalı soruya da hiç cevap verilmemişse, artık parmakizi telefonu açmıyor. Belki anlatamadım ama ilginç bir problem, ama tasarruf moduyla ilgili soru cevaplanırsa, normal işlevine dönüyor. Çeviri ile alakalı değil, sistem parmakiziyle uykudan dönmüyor

**Comment by aykutyenihan** [comment]
hocam bir iki ufak hatalı nokta var baya bir sürümdür ama ekran görüntüsü alamıyorum. 
     birinicisi gelen arama ekranında cevaplama reddetme ve mesajla cevaplama kısayolları var biliyorsun ama hepsinde yukarı kaydır yazıyor yanlışmı değil ama daha önceleri onlar yanıtlamak için kaydır reddetmek için kaydır şeklindeydi ki olması gereken oydu.
    ikinciside biriyle telefon görüşmesi yaptık bitti kapattık ekranda örneğin (çağrı bitti00:20) şeklinde bir mesaj çıkıyor, arada bir boşluk olması gerekmezmi? sürekli gözüme takılan ama çokta takılmadığım noktalar bunlar.

**Comment by raoc999** [comment]
@aykutyenihan 
Aykut birinci dediğin düzelttim, upload ediyorum. Umarım düzelttiğim yer, bahsettiğin yerdir. İkinci dediğin yer beni deli eden yer. Çağrı bitti diye çevrildi sonra bir boşluk bıraktım yine bitişik çıkıyor, süreden önce boşluk bıraktım yine birleşik ve büyük harf. Acaba başka yerden mi çekiyor bilmiyorum. Tüm çeviridi sadece bir yerde var. Şimdi Arama bitti diye ve : ile arayı açıyorum. Bana geliyor ki İngilizce kaynak dosyası çok eksik. Şimdi Kablosuz ekran için baktım, Bir sürü İng. yer var. Ama kaynak dosyada aratıyorum böyle kelime ve satır bile yok. Almancada bayağı fazla satır vardı ekledim yine eksik. Soru şu acaba 5,6,7 sürümlerinden beri gelen bazı ekler, içerikleri göremiyor muyuz?

**Comment by raoc999** [comment]
@ingbrzy 
In other languages, the file path is different:
MA-XML-8.0-ENGLISH / English / main / miui.apk / res / values-tr / or
MA-XML-8.0-ENGLISH / English / main / miui.apk / res / values-tr-rTR /

Should it be corrected?

by Orhan

**Comment by raoc999** [comment]
@ingbrzy 
In other languages, the file path is different:
MA-XML-8.0-TURKISH/Turkish/main/miuisystem.apk/res/values-tr/ or
MA-XML-8.0-TURKISH/Turkish/main/miuisystem.apk/res/values-tr-rTR

Should it be corrected?

from German files

**Comment by ingbrzy** [comment]
Doesn't matter for miui.apk...

Dňa 1. 11. 2016 10:27 odpoludnia používateľ "recep.ali.orhan.cakmak" <
notifications@github.com> napísal:

**Comment by ingbrzy** [comment]
and fix you xmls issues http://translators.xiaomi.eu/XML_MIUI8-Turkish-tr.html

**Comment by raoc999** [comment]
6.10.31 :: 6.11.1 :: 6.11.2 güncellemeleri yapılıp, yüklendi.

**Comment by aykutyenihan** [comment]
tamam hocam olmuyorsa olmuyordur eline sağlık.

**Comment by sevgiesenler** [comment]
merhaba 
xiaomi.eu_multi_MI5SPlus_6.10.27_v8-6.0
attım ama google play a girince
maalesef google play hizmetleri durdu
hatası veriyor

**Comment by ingbrzy** [comment]
@sevgiesenler wipe user data

**Comment by raoc999** [comment]
@ingbrzy 

I looked at the source file. German, Polish and so on. The files are sorted specifically by your translator. I'm so happy to do this. No problem if you can not. Tell me how to do it ... Thanks for your help. Why? Because I looked at your files. You have a lot of lines. Same files. Some files are few. I think your files are the most smooth. Then I will  follow you.

**Comment by ingbrzy** [comment]
dont waste your time on sorting strings.. I will do that by our sorting script...

**Comment by raoc999** [comment]
SuperB

**Comment by sevgiesenler** [comment]
6.10.31 :: 6.11.1 :: 6.11.2 güncellemeleri yapılıp, yüklendi.
nerden bulabilriim bu versionları acaba

**Comment by raoc999** [comment]
@sevgiesenler 
Bunları bulamazsın sadece kaynak dosyaları çevrilip kütüphaneye eklendi. Haftasonu ingbryz, xiaomi.eu sitesinde bu haftaki 6.11.3 sürümü yayınlayacak. Oradan indirip kurabilirsin.

**Comment by sevgiesenler** [comment]
ilgilerinize  çok tşkler

**Comment by raoc999** [comment]
@ingbrzy 
When you are available... Can you sort the rows my files? Thanks

**Comment by kutlusancak** [comment]
![screenshot_1970-01-23-12-27-25-790_com miui home](https://cloud.githubusercontent.com/assets/22856709/20033955/e06b849c-a3b6-11e6-9982-f80a957f038f.png)

Mi 5S 6.11.3 ilk karşılaştığım hata. Şarj bildirimi %19 hatası düzelmiş elinize, emeğinize sağlık.

**Comment by SiberMedya** [comment]
Miu sistem arabirimi hatası alıyorum Türkçe de.
İngilizce de sorun yok.
mi max ve redmi note3 pro iki farklı cihazda oldu
mi max stabil rom da bile oldu.
birkaç gün sorunsuz çalışırken bu hata veriyor sürekli, ekranı kitliyor hata sürekli çıktığı için.

**Comment by aykutyenihan** [comment]
resmini verdiğim hataların kablosuz ekran, kapat vs hemen hepsi duruyor

**Comment by raoc999** [comment]
@aykutyenihan; ve diğer arkad
