### ISSUE TITLE
6.11.3 Problemler, Öneriler vb (issues)

### ISSUE THREAD

**Issue by SiberMedya** [ingbrzy/MA-XML-8.0-TURKISH#86]
Miu sistem arabirimi hatası alıyorum Türkçe de.
İngilizce de sorun yok.
mi max ve redmi note3 pro iki farklı cihazda oldu
mi max stabil rom da bile oldu.
birkaç gün sorunsuz çalışırken bu hata veriyor sürtekli ekranı kitliyor hata sürekli.

**Comment by ilkerxxx** [comment]
CAMERA programınada bi el atın arkadaşlar.
ingilizce olunca problem yok.
ama türkçe seçince zırıtıyor.
camera programında resim çektikten sonra çektiğimiz resmin simgesine tıklayınca galeriye gitmiyor. resmi açmıyor.  tekrardan başa dönüyor.
büyük ihtimalle çeviriden dolayıdır.
galeri yi açacak linkte belkide galeri uygulamasının ismide değiştiğinden açmıyorda olabilir
sorun bulunamıyorsa bence camera hiç cevirilmesin. ingilizce dilde problem yok çünkü

**Comment by raoc999** [comment]
@ilkerxxx 
İlker dediğini önceden denedim. Bir haftakamera ertesi hafta galeriyi ing. biraktım sorun kalkmadı. Bir sonraki hafta ikisinde ing. yapacakken. Galeri yazılımı  komple değişti sorun kalktı. beta sürümde de bir yere geldik ondan sonra sorun yeniden başladı. İtalyanca ve Almanca dosyları tek tek karşılaştırdım bu iki dosyada herşey düzgün ama ayarlar vb başka bir dosyada hata olmuş olabilir.  Pil problemindeki gibi birşey de olabilir. Oradaki sorun da bizim % rakamdan önce iken onlarda sonra, onların formatına geçince düzeldi... Burada bir bir tek karakter tüm işi berbat ediyor.

**Comment by raoc999** [comment]
@SiberMedya 

Buradaki yazılım ve 6.11.3 ile mi sorunlar başladı? Öyleyse senin ürünlere göre kodları incelerim. Resmi romu denedin mi?

**Comment by aykutyenihan** [comment]
aman hocam galeriyi kamerayı yine ingilizce yapayım deme yeter bizde sorun yok derdini biz çekiyoruz.

**Comment by SiberMedya** [comment]
Bu rom larda denedim Türkçe de sorun vermişti.
Garip olan birkaç gün düzgün çalışıyor ne oluyorsa miui arabiirim hata veriyor döngü halinde, cihazın cache silmek bile fayda vermiyor. 

xiaomi.eu_multi_MIMAX_V8.0.3.0.MBCCNDG_v8-6.0
xiaomi.eu_multi_MIMAX_6.10.27_v8-6.0
xiaomi.eu_multi_MIMAX_6.10.13_v8-6.0
> 
Buradaki yazılım ve 6.11.3 ile mi sorunlar başladı? Öyleyse senin ürünlere göre kodları incelerim. Resmi romu denedin mi?
>

**Comment by ilkerxxx** [comment]
Ingilizce ve turkce dil dosyalari nerde acaba bende kontrol edeyim. Belki goze carpan bisey olur

**Comment by raoc999** [comment]
@aykutyenihan 
Aykut senin model ne? Sende sorun yoksa bizim modellerde varsa çeviriden değil o zaman. İşin ilginç tarafı bazı hatalar var ama bunlar yazılımla ilgili galiba, çünkü Almanca ve Türkçe'de de aynı sorunlar var. Mesela bölge seçeneği buradaki romda yok, resmisinde var. Sıfır kurulumda açılış kurulumunda çoğu seçenek iptal olmuş ve sistem kendini hindistanda varsayıyor. Sadece bende mi var. Parmakizi hafif ıslak elde ve soğukta çalışmıyor.... Ucuz malın yahnisi... Almanca, İtalyanca dillerinden olmayan satırları ekliyorum. Kablosuz Ekran ile ilgili eklediğim satırların çevirisini Note 2 de görüyor Note 4'de ise ing. olarak görüyorum? Ürün sayısı artıyor, bir modelde pil seçenekleri % ile ifade edilmiş başka modelde %1s olarak değer çekilmiş. Mecburen birisini yazıyorsun aksi halde iki aynı satır diye hata veriyor. Bu sefer bir modelde çalışıyor diğer modelde çalışmıyor. Artik tutarsız olmaya başlayacak. Alt modellere 6.0 vereceklerse versinler ve onların güncellemesini daha geniş aralıklarla yapsınlar.

**Comment by aykutyenihan** [comment]
mi4c benim model. hocam bırak çeviri böyle kalsın, dediğin gibiyse durum boşa çırpınmaya cirpindikca daha kötü yapmaya gerek yok

**Comment by raoc999** [comment]
Arkadaşlar bugün telefonun (Note4) içindeki APK dosyaları çekip decompile yaptım. Birde ne göreyim hiç elimizi sürmediğimiz dosya ve yarım yamalak çevrilmiş bir sürü dosya var. Yarım olarak çevrili dosyalar çok önceden geliyor, güncelleme ve eklentiler dail olmadığından esas dosya ile aralarında çok far var. Birde Polanya çevirisinde çok fazla şey var. Moderatör'de bu dilde çeviri yapıyor diye biliyorum. 3. parti uygulamalar da eklenmiş. Mesela Mi Band Tools... Bunun da çok azı çevrilmiş diğer yarısı İng. çevirip bizim dile de ekleyeceğim. Faydalı uygulama. Çevirmediğim ve üzerinde durmadığım iki dosya var. Cit ve EngineerMod... Sebebi ise ne deyse her telefonda bun dosyalar ya farklı yada satır yerleri hep değişik. Gereği yok diye düşünüyorum. Çevirideki hataları düzeltmeye odaklanacağım ama kamera, galeri gibi şeyleri Aykut kardeşimin dediği gibi düzeltmeye çalışmayacağım. Sonuçta ben programcı değilim ve geriye dönüp yeniden başlamak istemiyorum. Bunu ARGE bulsun. Detaylı bir yazı yazıp Xiaomiye atarım. Sonuçta Resmi ROM'da da var ve oradaki çeviri benim değil. Burada Türkçe karakter, bizim kullandığımız tarih, konum, % gibi işaretlerden kaynaklı sorunlar olabilir. En son pilde gördük ki %19 yazarsan kabul etmiyor, 19% yazacaksın. Şuanki saat uygulaması da bendeki telefonda hata veriyor elle ayarlamak zorunda kalıyorum. 
Son olarak: 6.11.7  :: 6.11.8 eklentileri yapılıp siteye eklendi.

**Comment by raoc999** [comment]
Aykut normalde çevrilecek herşey bitti. Bunu kaynak dosya ile Türkçe çeviriden görebilirsin. Artık çevrilecek hiçbirşey yok. Sadece yeni eklentiler İng. kalır. Ama gel gör ki halen ing. var. O ing. satırları, tabirleri kaynak dosyada arıyorsun yok öyle birşey. Tüm telefon modellerinde arıyorsun yok. Nereden geliyorlar ?. Bende bunları bulmaya çalışıyorum. Herkes için: Diğer taraftan bu işi ben üstüme zimmetlemedim. Kodları inceleyip ekleme yapabilirsiniz.  İsteyen, hata bulan, kendi kullandığı modele göre ekleme yapsın. Ben Note 2, Note 4 ve Mi5 modellerinine göre çeviri yapıyorum. Bazı modellerin string satır başları aynı ama çektiği değerler farklı. Ona ben birşey yapamam. Birde şunu insanlar gözardı ediyor. Bu sitedeki yazılımla resmi yazılımla aynı olamaz. Burada hata olasılığı yüksektir. Mesela bende navigasyon yazılımlarını kapatınca uygulamanın durduğuna dair hatalar geliyor. Şimdi bu çeviriden mi? Bilmiyorum. Çeviri nedenli hata raporunda Türkçede hata yok diyor. El elden üstündür. Kodları inceleyin, belki Ömer Faruk gibi hataları bulabilirsiniz. Dediğim gibi bana zimmetli değil, çeviriye de mecbur değilsiniz. Kodlar açık, inceleyip, ekleyin, isterseniz çıkartın. Yeter ki bir yere gelen işi daha kötüye götürmeyin. Ben paranın üstüne yatıp size koklandırmıyorum gibi birşey yok. Gönüllülük esaslı birşey. Benim anlamadığım israrla çevirmek istiyenler neden herkesin gördüğü yerden değilde özelden ulaşmaya çalışıyorlar... Özele gerek yok, istediğiniz gibi istediğinz dosyayı elden geçirin ve ekleyin. Simetrik ve düzgün olması için uğraşıyorum, yoksa ne referans ne de parasal bir beklentim yok. Zaten ihtiyacım da yok. İnanın bazen yazacak zamanım olmadığı halde aradan aradan birşeyler ekliyorum. Daha iyi olsun diye Aykut, Sedat gibi arkadaşlar gerçekten çok iyi iş çıkardılar, bazen aynı resimleri tekrar tekrar gönderdiler. Onların söyledikleri yerleri yapmama rağmen nasıl oluyorsa bende söyledikleri değişiklikler gözükürken onlarda gözükmüyor. Mesela "More" ve Kablosuz ekranlar ilgili yerleri koymama rağmen halen şikayetleri devam ediyor. Son olarak: Telefonda benim çevirmediğim, yarım kalmış dosyalar var. En azından 8 sürümde telefondaki tüm TR içerik silinip yeniden başlayacaktık ama kodunu görmediğimiz bu dosyaları nasıl düzelteceğiz?  Velhasıl: Kodlar açık, girin inceleyin, İng kodlarlar veya hangi dili biliyorsanız onla karşılaştırın.

**Comment by raoc999** [comment]
6.11.9 satırları eklendi: (Değişiklikler)
Kişiler : Canlı Görüşme
Saat: Zilden önce bildirim gelmesi
Mi Bulut Hizmeti: Eşitlenmiş öğelerin telefondan kaldırılması
Oyun Hızlandırıcısı: Yeni özellik, aslında 6.11.3 de olacaktı fakat ROM derlenmesinde bazı hatalar olduğundan gelecek sürüme sarktı.
Kişisel Yardımcı: Bu dosyanın bir kısmı eklendi çünkü dosya tamamen Çince
Güvenlik Merkezi: Bazı ifadeler değişti
Ayarlar: Arama özellikleri eklendi...
Tema Mağazası: 
Framework: ...
