### ISSUE TITLE
Sürüm 6.11.10 Hakkında Problemler vb.

### ISSUE THREAD

**Issue by raoc999** [ingbrzy/MA-XML-8.0-TURKISH#88]
6.11.10 hakkında bilgileri buraya bildirebilirsiniz. Gemini modeldeki Personal Assist ve bazı yerlerdeki Çince çeviriler Türkçeye çevrilmedi, çünkü ilerideki sürümde İngilizce hale getirilecek. Malum bazı modellerde 6.11.10 sürümü daha geç geliyor. vb...

6.11.10 SÜRÜMÜNÜ YÜKLEYENLER LÜTFEN WIPE/DALVIK CACHE YAPMAYI UNUTMASIN. Aksi halde uygulamalar kapatıldığında "....durdu" gibi hatalar ve Kablosuz Ekran gibi bazı ayarları eski haliyle görürler...

**Comment by raoc999** [comment]
Beyler;
6.11.10 sürümündeki tüm içeriği PCye aktarıp dosyaların içeriklerini decompiler ettim. Sonuç şu: Bize kaynak dosya -çevrilecek dosyalar- diye verilen ingilizce  ile telefondaki ingilizce dosyalar arasında bayağı farklar var. Şu an bir dosyayı derleyip ekliyeceğim. Şimdi bazı arkadaşların benim telefonda çoğu yer ingilizce demesinin sırrı ortaya çıktı. Kaynak dosyalardaki satırlar eksik. Farklı modellerde satırlarında farklı olabileceğini düşünürsek... Ben Note 4 içeriğini çıkardım. En azından birde Qualcomm işlemci bir başka modelin içeriğini de çıkarmak lazım. Bu konuda bir yazı yetkiliye göndereceğim. Aksi takdirde hiç bir zaman telefonlar tam Türkçe olmayacak. Çünkü kaynak dosyada çok çok eksiklik var. Sadece mediatek-res dosyasında 100e yakın satır eklenmemiş.

**Comment by ilkerxxx** [comment]
kaptan. bu miui 8 için lg klavye gibi bi klavye entegre edilemezmi

**Comment by raoc999** [comment]
@ilkerxxx 
Neden olmasın, yapacak biri lazım :)

**Comment by raoc999** [comment]
Beyler; Google hizmetleri eklendi. Ayrıca şu an bazı Mi uygulamalarını çevirip ekleyeceğim. Mi VR gibi.

**Comment by raoc999** [comment]
Ömer Faruk adlı arkadaşın söylediği hatalar düzeltilip, eklendi.

**Comment by raoc999** [comment]
Mi Band Tools adlı güzel bir yazılım var, bunu Türkçeleştirip (2.4 en son sürüm) sisteme ekledim. Üreticiye de çeviriyi gönderdim. Mi Fit yazılımından daha güzel.

**Comment by raoc999** [comment]
6.11.13/6.11.14/6.11.15/6.11.16 ve 6.11.17 sürümlerinde elen yeni satırlar ve değişiklikler eklendi. Kullandığı modelde halen İngilizce ve Çince yerler olana arkadaşlar var galiba. Note 4 modelinde sadece paylaşım yapılınca 1 connected 0 blocked denilen yer var kaynak dosyada böyle bir yer yok. Kaynak dosyada yok. Türkeçe çeviride ise bir kaç satır çevrilmedi onlarda Çince ve ay adları. Eğer böyle sorunu olanlar varsa bana apk dosyalarını göndersinler. O dosyaları açıp içlerine bakalım.  Sitede verilen kaynak dosyaları hem eksik hemde satırların çoğu yok. Geçen hafta 5-6 dosya ben çevirip ekledim, bu hafta kaynak dosyaya eklediler. Kaynak dosyalar tam olsa kimse şikayet etmez. Şikayet sadece çeviri hataları ile uygulama hatalarından kaynaklanır.

**Comment by kesn19** [comment]
Redmi note 3 (hennessy)  mediatek işlemcili model için kamera galeri geçişi için herhangi bir çözüm yok mu? Sizdeki redmi note 4 mediatek işlemcili acaba onda da aynı sorun varmı?

**Comment by raoc999** [comment]
@kesn19 
Evet bende de sorun devam ediyor.  Ama bazı modellerde sorun yok. Bu hafta Resmi sürümü kurup orada sorun var mı diye bakacağım. Geçen baktığımda sorun orada da devam ediyordu.

**Comment by raoc999** [comment]
MiVR dosyasını çevirip ekledim

**Comment by oguzhan5200** [comment]
bak şekil oldu :) genel olarak bir problem göremedim. 8.1.2 stabil olanı kurdum gayet güzel uzun kullanımda birşey görürsem paylaşırım
[![image](http://i.hizliresim.com/bk8mQG.png)](http://hizliresim.com/bk8mQG)

**Comment by raoc999** [comment]
Qualcomm tabanlı bir modelin içindeki tüm apk dosyalarını alıp bana gönderecek arkadaş var mıdır? Zannedersem Qualcomm tabanlı ürünlerde ing. yerler kalmış. Kaynak dosyada olmayan satırlar. ES File Explorer içinden dosyalara ulaşabilirsiniz.

**Comment by oguzhan5200** [comment]
deniycem becerebilirsem göndereyim

**Comment by oguzhan5200** [comment]
https://mega.nz/#!pRw3garB!ZBjyTu5YGLOUFbGWaPZQ_NHTu5pQlWQDODEKccPoJGA
minote pro 8.1.2 işine yararmı bilmiyorum developer değil çünkü :)

**Comment by raoc999** [comment]
@oguzhan5200 
Yarar Oğuzhan; ne kadar çok kaynak dosya o kadar çok düzeltme demektir. Adını altın harfle yazacağım :) Teşekkürler

**Comment by aykutyenihan** [comment]
şekil diyorsunuzda bence bilakis rezil gözüküyor acı ama gerçek. Kilit ekranını görmek istemiyorum sayenizde bakmayın ses çıkartmıyorumda için kan ağlıyor

**Comment by raoc999** [comment]
Aykut senin şu yazılıma katkın inkar edilemez. Yukarı işaretlerini kaldırıyorum

**Comment by aykutyenihan** [comment]
hocam ben orjinale en yakın ve basit olması taraftarıyım. elimde olsa '' yukari kaydır'' der gecerim yada acmak icin yukari kaydirin gibi. ama bu benim fikrim kimse katilmak zorunda değil

**Comment by aykutyenihan** [comment]
ayrica hocam apk dosyalari gonderirdim ama 300-400 mb dosya yapiyor romu direk indirsin ayni hesaba gelir

**Comment by raoc999** [comment]
romdan dosyaları alamıyorum, bütün gün şu internet paylaşımını açınca çıkan X connected x blocked nerede diye harcadım halen bulamadım. Dili değiştirince de diğerlerinde ing. çıkıyor kaynak dosyaya koymamışlar resmide var

**Comment by aykutyenihan** [comment]
romu bununla parçalarsan istediğini alabilirsin.

[SystemExtract-support_5.1.zip](https://github.com/ingbrzy/MA-XML-8.0-TURKISH/files/600912/SystemExtract-support_5.1.zip)

**Comment by ilkerxxx** [comment]
ama dili ingilizce yapinca problem yok



Mi telefonumla gönderildi"recep.ali.orhan.cakmak" <notifications@github.com>, 17 Kas 2016 17:22 yaz:

@kesn19<https://github.com/kesn19>
Evet bende de sorun devam ediyor. Ama bazı modellerde sorun yok. Bu hafta Resmi sürümü kurup orada sorun var mı diye bakacağım. Geçen baktığımda sorun orada da devam ediyordu.

**Comment by mamilux** [comment]
Merhabalar Hocam. Oneplus3 Kullanıyorum miui8 port rom kurdum türkçe yok yani morelocate den turkce seciyorum çşı gibi harfler gözükmüyor mesela Facebook ta veya system de popup ekranında bisim karakterler yok. ingilizce de de Facebook ta insanların adlarındaki ıçş ler eksik Jbart ile denedim ama bootlop oldu yardımcı olurmusunuz Lütfen? burda da Log.https://mega.nz/#!sZF2yJyJ!eyTGlVWz9YASbNC6155VDgXr5Fc3oFi_OcMRp9LqYWc
Saygılar.
