### ISSUE TITLE
6.11.17 Sürüm :: Şikayet ve Öneriler

### ISSUE THREAD

**Issue by raoc999** [ingbrzy/MA-XML-8.0-TURKISH#89]
* Sistem daha kararlı hale getirildi
*Kulaklık bağlandığında zil sesi yüksekliği iyi hale getirildi
*Kilit Ekranda PIN Kodu girişi iyi hale getirildi
*Bluetooth, Bildirim Ekranı ve Tema'larla ilgi sorunlar düzeltildi
*Başlatıcıdaki animasyonlarda ayarlar yapıldı
*Kısayol Menüsünde yeni mod eklendi
*Oyun Hızlandırıcısı iki simge açıyordu, düzeltildi
*HM4A eklendi...

Sorunlarınızı model ismiyle birlikte yazın lütfen. Halen bazı yerler İng. bunu biliyorum. Dosyalar %100 bitti. Bu yerler İngilizce kaynak dosyalarına eklenmemiş satırlardan oluşuyor. Bu yerleri şöyle bulabiliriz. Dili Almanca veya Fransızcaya çevirin. O yerlerden ne yazıyorsa gönderin. Bende Almanca dil dosyalarından arayıp ekliyeyim.

**Comment by heyelan96** [comment]
Redmi pro. Hocam burda "büyükten daha küçük" e tıklayınca küçükten büyüğe sıralıyor. "Küçükten daha büyük" diyince diyince büyükten küçüğe sıralıyor. Boyut olarak. Bu ters. 





![screenshot_2016-11-18-17-41-09-843_com android fileexplorer](https://cloud.githubusercontent.com/assets/20803990/20434683/aa3f4f8e-adb1-11e6-942a-3dcddba0f294.png)

**Comment by raoc999** [comment]
@heyelan96 

Küçükten büyüğe
Büyükten küçüğe
olarak düzelttim, teşekkür ederim, gelecek hafta düzelir.

**Comment by raoc999** [comment]
Beyler Mi Band Tools yazılımının çevirisini kaldırdım. Çünkü çeviriyi Mi Band Tools firmasına gönderdim, yetkilisi ise buradan kaldırmamı istedi. Gelecek sürümden itibaren daha iyi ve tam çevrilmiş haliyle Mi Band Tools yazılımını kullanabilirsiniz. Fiyatı biraz arttı ama (7,5 tl) tüm Mi Band ürünlerini rahatlıkla ve Mi Fit programından daha kapsamlı şekilde kullanabilirsiniz.

**Comment by raoc999** [comment]
Teelefonunda halen İngilizce yerler olanlar lütfen yazsın. Yönetici kayıp ve kaynakta olmayan satırları gönderdi. Eklemeye başladım. Umarım tüm sorunlar çözülür ve güzel bir yazılım olur. Bu arada 6.11.21  sürüme ait yenilikleri de ekliyorum.

**Comment by 4fareis** [comment]
![screenshot_2016-11-21-21-04-17-828_com android packageinstaller](https://cloud.githubusercontent.com/assets/18270175/20494853/78e6cf8e-b027-11e6-912a-c328ebf333b0.png)
![screenshot_2016-11-21-21-03-55-201_com android packageinstaller](https://cloud.githubusercontent.com/assets/18270175/20494854/7909762e-b027-11e6-9792-61407859df41.png)
![screenshot_2016-11-21-21-04-36-950_com android packageinstaller](https://cloud.githubusercontent.com/assets/18270175/20494855/791b6000-b027-11e6-9c87-3c5d031b98f5.png)

**Comment by raoc999** [comment]
@4fareis
Bu bölümleri söylemiştim. Google Play yazılımından kaynaklanıyor demişti. Galiba doğru zira bende buralar Türkçe olarak geliyor. Yinede bakıyım. Fakat Tamam, Başlat ve Engellendiğine dair bölümler Türkçe olmalı. Şimdi çevirilere bakınca buraları çevirdiğim gözüküyor. Bu durumda hangi sürümü kullanıyorsun?

**Comment by 4fareis** [comment]
@raoc999 redmi note 2 xiaomi.eu 6.11.17 kullanıyorum aslında çok bişey değil onlar olmasada olur. Ellerin dert görmesin teşekkürler çeviriler için.

**Comment by raoc999** [comment]
Bu arada Hotspot açıkken connected ve blocked diye gelen mesaj eksik kaynak koddan kaynaklanıyordu. Gelecek hafta en azından mediatek işlemcilerde düzelecek.

**Comment by raoc999** [comment]
6.11.21 değişiklikleri yapıldı;
(Parmakizi, imza, ekran hücresi, güvenlik, ana ekran, kişiler vb... değişiklikler olacak ?!

**Comment by aykutyenihan** [comment]
sarj %20 nin altına düşünce çıkan uyarıda ingilizce yerler var %19 remaining gibi. 

rehberdeki profile-profile vs eksik satır kaynaklı hatalar devam ediyor, wireless displayda muhtemelen devam ediyordur ama artık boşverdim. 

hava durumunda aşağıya çekip yenilendiğinde veri süresi doldu gibi anlamsız bir yazı çıkıyor önce daha iyiydi. Yine ayarlarında ''Sicaklık Birimi'' yazıyor.

galeride resim düzenleme ekranında Kırp ve Döndür ekrana sığmadığı için yarın gözüküyor, kırp döndür olsa tam çıkarmı acaba bilmiyorum yada daha kısa bişey.

kullanırken gördüğüm ama unuttuğum boşverdiğim yerler var ama genel anlamda çeviri tamamlandır diyebiliriz, eline sağlık hocam.

**Comment by raoc999** [comment]
@aykutyenihan 
Önceden düzgün olup şimdi bozulan yerler, çevrilmemesi gerekiyor diye moderatör tarafından silinen satırlardan kaynaklanıyor. Ama yazım hatası olan yerleri düzeltirim. W .Ekran için yazdım, dosya eksik diye, cevap gelmedi. Dediğim gibi verilen kaynak dosyası, doğru yanlış %100 çevrildi. Ama ben kaynak dosyanın eksik olduğuna artık %100 eminim. Çünkü gerçek kaynağa eriştim ve görüyorum. Şimdi imlâ hatalarını düzeltim ekliyorum

**Comment by heyelan96** [comment]
Hocam anadolu yazmıyor. Redmi pro

![screenshot_2016-11-22-23-50-51-964_com android contacts](https://cloud.githubusercontent.com/assets/20803990/20561310/09bb9964-b18f-11e6-9589-5b0ba3c3ce12.png)

**Comment by aykutyenihan** [comment]
Şurada da tek harflik hata kalmış 
![img_20161123_152137](https://cloud.githubusercontent.com/assets/16150035/20561689/d5775a1a-b190-11e6-8173-3cb0a413b165.jpg)

**Comment by raoc999** [comment]
Beyler 6.11.22 ve 6.11.23 değişiklikleri yapıldı ve eklendi. Geçen hafta Mi VR dosyasını çevirip eklemiştim, yeni değişiklikte Mi VR dosya içeriği MiVideo içine entegre edildi. Parmakizi ve MiVideoda bayağı değişiklik bekliyorum. Bakalım ne olacak.

**Comment by Xiaomizer** [comment]
![screenshot_2016-11-23-02-59-49-974_com android settings](https://cloud.githubusercontent.com/assets/23702775/20566928/e07973dc-b1a7-11e6-9e17-bb08b309c19a.png)
Merhaba Orhan Bey. Ekte görebilirsiniz ekran yerine erken yazılmış. Ayrıca uzatılmış ekran görüntüsü alma çalışmıyor. Mi4c ve Mi5 te dev ve stabil romda denedim. Global romlarda ise sorunsuz çalışıyor. Çeviri ile alakası yoktur belki ama belirtmek istedim. Şahsım adına sizden bir ricada bulunacağım. Burada onca insana cevap vermeye çalışıyor ve ciddi şekilde bir emek veriyorsunuz. Bunun için size sonsuz teşekkür ederim. Herkesin ihtiyacına cevap vermeye kırmamaya çalışıyorsunuz. Bu hareketinizide takdir ediyorum. Mesela kilit ekranında yukarı ok tuşu eklemiştiniz sonra bir arkadaş ya onu kaldırın ya da bu daha ekleyin simetri hastalığı var bende demişti sizde bir daha eklediniz. Aynısından arama cevaplama ekranında da var. Bende diyorum ki orijinal roma sadık kalsak çok daha sade ve güzel olur. Zaten istediğimiz de bu değil mi. Sade ve sorunsuz bir rom. Lütfen Rica ediyorum o ok işaretlerini orijinalindeki gibi kaldırın. Çünkü ok işareti zaten kilit ekranında görünüyor ardından açmak için yazısı görünüyor. Selam ve dua ile.

**Comment by mamilux** [comment]
Dostlar Turkçe karakter sorununa yok mu bi çözüm port rom için?

**Comment by raoc999** [comment]
Son Durum: (23.11.2016)
Beyler Mi3, Redmi 1S için eksik yerlerini buldum ve ekliyorum. Umarım diğer modelleri de bulurum

**Comment by aykutyenihan** [comment]
okları kaldırmışsın, Allahım sana geliyorum :) bu haftaki sürümde bildirimleri kilit ekranında silme olayıda gelecek xiaomi sağolsun 3 yıl önce gelen özelliği nihayet koydu romuna.

**Comment by raoc999** [comment]
@aykutyenihan 

Eee Aykut sen Beta Tester Liderisin. Doğrusu senin sayende çok yol aldım. Hataların %75'ini senin geri dönüşlerin sayesinde düzeltim. Yani, istiyorsan, hepsini yeniden İng. çeviririm :) Sağol

**Comment by aykutyenihan** [comment]
e liderimde neden benim haberim yok :) yok hocam bişeyi bozma bana yeter :P
