### ISSUE TITLE
Turkish Language Report from recep.ali.orhan ÇAKMAK

### ISSUE THREAD

**Issue by ingbrzy** [ingbrzy/MA-XML-8.0-TURKISH#90]
Hello there;
First of all thank you for your help. I want to say some problems.
1: Turkey no longer uses Daylight Saving Time. The clock is normal now. After updating, time is going back an hour. Our country not use Winter Time or Daylight Saving Time.
2: In some places (charge), the % sign is incorrect. Errors occur when you correct. Turkey is using 100%.
3: Resource file is insufficient. E.g; Some lines about Wireless Display are missing. If you turn on the Wireless screen. There are messages in English. I can not get a screenshot. The important thing is that when Hotspot is enabled, the notification is English: 1 connected 0 blocked
Such a text is not in the source file. No problem with official software.
4: The problem of switching from Camera to Gallery continues on some models, but it does not matter.
5: Other subtle details: If the call is over, "Call finished: 02.12 min" is displayed on the screen. (In Turkish: ÇAĞRI BİTTİ:02.15 min) Should be: Çağrı Bitti: 12.12 min
I mean there must be a space, not a union. There is no such place in the language files. Where does  get it from?
6:I looked at German and Italian languages. There are some places around here. Excess. Some people are e-mailing to me. They say "There are English sentence or question on our phone" Could it be? Because I translated 100% languages. Are the source files of Qualcom or Mediatek phones different? Is the official language the source file is different? I looked at the contact file yesterday. Some lines were more than that. There is also a zone/region and light mode option in the official software. (in settings) not important but but I want to real 100% translate

Thank you:
Orhan

**Comment by ingbrzy** [comment]
ad 1)
Go into Settings
Check the Date & time page
Select options for both Automatic date & time and Automatic time zone

**Comment by ingbrzy** [comment]
ad 3)
should be this https://github.com/ingbrzy/MA-XML-8.0-TURKISH/blob/d0b64fa2898cc5e7cede93eca07b0f69a7f47da7/Turkish/main/mediatek-res.apk/res/values-tr/strings.xml#L335

**Comment by ingbrzy** [comment]
Ad 6)
See attached file for missing strings in your translation...
[Missing strings_TR.zip](https://github.com/ingbrzy/MA-XML-8.0-TURKISH/files/603626/Missing.strings_TR.zip)

**Comment by raoc999** [comment]
I mean our Time Zone changed. System defaults will be GMT +2:00  (Amsterdam, Berlin), I am changed manually, but if I reupgrade, time will changed... We wont use Saving Time...


Thanks for fixed
