### ISSUE TITLE
XML recompile issue

### ISSUE THREAD

**Issue by ingbrzy** [ingbrzy/MA-XML-8.0-TURKISH#91]
`Contacts.apk/res/values-tr/strings.xml:876: error: Resource entry noContactsNoSimHelpText is already defined.
Contacts.apk/res/values-tr/strings.xml:845: Originally defined here.
Contacts.apk/res/values-tr/strings.xml:1004: error: Resource entry otherLabels already has bag item ^index_0.
Contacts.apk/res/values-tr/arrays.xml:4: Originally defined here.
Contacts.apk/res/values-tr/strings.xml:1005: error: Resource entry otherLabels already has bag item ^index_1.
Contacts.apk/res/values-tr/arrays.xml:5: Originally defined here.`

**Comment by raoc999** [comment]
I will fix, but you are very quickly. I used different computer and merge app... App changed my standart prosedure. Thanks
