### ISSUE TITLE
Sürüm: 6.11.24   :: Problemler, Öneriler, Hatalar vb...

### ISSUE THREAD

**Issue by raoc999** [ingbrzy/MA-XML-8.0-TURKISH#92]
Arkadaşlar, yeni sürümdeki hatalı ve eksik gördüğünüz yerleri lütfen belirtin. Belirtirken telefonunuzun modelini yazmayı unutmayın. Herkesin beklentisini %100 yapamayız. Fakat büyük çoğunluğun memnun, bir kısmının da idare ettiği birşeyler yapabilirsek ne mutlu.

Bu haftaki değişiklikler:
1. Parmakizi ve NFC ile ilgili optimizasyonlar
2. Ayarlarda yeni özellikler
3. Yeni müzik albümleri vb
4. Bazı hataların giderilmesi -özellikle pil-
5. Hava durumu ile ilgili düzeltmeler.

Mail ve İkinci alan dosyalarını başka dosyalarla -hata- ile değiştirdim. Geçen akşam ROM'lar yeniden yapılacağından tüm dosyaları -3.00s- tüm gece düzeltim ekledim. Fakat yapılan ROM dosyalarında hata devam ediyor. Herhalde dosyalarını yeni ROM dosyalarına eklemedi. Bir alt sürümü kullanabilir veya bu hafta o iki bölümü ing. olarak kullanabilirsiniz. Bu esnada geçen hafta söylenilen tüm hataları düzelttim. Birden fazla yerde yedekli çalıştığımdan, yaptığım düzeltmeler yerine, bir önceki yedeği upload etmişim.

**Comment by 4fareis** [comment]
![screenshot_2016-11-25-16-04-43-651_com miui weather2](https://cloud.githubusercontent.com/assets/18270175/20626162/91aecd90-b320-11e6-8885-edd1b52c0b5d.png)
Hava durumu güncelleme yapmıyor sabahtan beri 10 derece gmail durdu hatası alıyorum wipe cache yaptım gmaili silip inbox u kurdum sorun yok sistem genel olarak iyi dediği  gibi teşekkürler redmi note 2 kullanıyorum xiaomi.eu son sürüm

**Comment by raoc999** [comment]
Gmail durdu hatasını şöyle düzletebilirsin, Uygulamalardan Google'a ait önbellekteki içeriği ve güncellemelerini sıfırlarsan düzeliyor. Bu hatanın sebebi; Google'a ait çevirileri dil dosyalarına ekledim. Gelecek hafta Google Play ve Google'a ait çeviri dosyalarını sileceğim. Bende uyuz oldum. Hava durumu ile ilgili: Ağa bağlanmıyor, yeni yer ekleyince bulamıyor. Bu sorunu hemen yetkiliye yazıyorum. Ondan mı benden mi kaynaklanıyor bilemiyorum. Yeni bir satır eklemedim sadece Sicaklık yazan yeri Sıcaklık yaptım

Teşekkürler.

**Comment by aykutyenihan** [comment]
bu sürüm biraz sıkıntılı gibi geldi, gmail sorunu ve hava durumu sorunu genel bir sorun rom'un konusunda yazmış millet. efekler kısmı kalmış sonraya bıraktın heralde çok sorun değil ama miui mail uygulaması cihazlar olmuş içeriği komple ingilizce. Dahada bişeyler çıkacak gibi pis bi his var bu sürüm için.

**Comment by raoc999** [comment]
Aynen "efekti" de düzelttim ama ya bir dosyayı yanlış bir yere kopyaladım bundan sorun çıktı, ya da toplu hale şöyle gördüğün yerleri şöyle yap deyince dokunulmaması gereken bir yer değişti. Tam en iyi hale gelirken!

**Comment by raoc999** [comment]
Sorun benden kaynaklanıyor, farklı bir dosyayı E-Mail içine atmışım. Herkesten özür dilerim.

**Comment by aykutyenihan** [comment]
şunları yapmasan varya oyum sana ama halka inemiyorsun bir türlü :)

**Comment by raoc999** [comment]
Biz adam olmayız başkan...

**Comment by aykutyenihan** [comment]
sana yardımcı biri lazım kendi dünya işlerin yanında bide bu incik boncuk işlerle uğraşıyorsun acelede ediyorsun yetişsin diye gerek yok. eski mail apksını atarız bu haftayı kurtarırız. gmail ve hava durumu zaten senle alakasız durumdan bozuk.

**Comment by heyelan96** [comment]
redmi pro bunlar gördüğüm yerler hocam
![screenshot_2016-11-25-17-57-06-688_com miui securitycore](https://cloud.githubusercontent.com/assets/20803990/20633872/c98e3c22-b353-11e6-9a77-0befe737a4ce.png)
![screenshot_2016-11-25-18-01-12-399_com android settings](https://cloud.githubusercontent.com/assets/20803990/20633873/c9918756-b353-11e6-9713-fea0e3513bd0.png)
![screenshot_2016-11-25-18-05-19-295_com miui securitycore](https://cloud.githubusercontent.com/assets/20803990/20633874/c9968422-b353-11e6-9cb6-50e0e1e09df1.png)

hocam burda lisans vardı ne ara kolej olmuş :)
![screenshot_2016-11-25-18-04-00-667_com xiaomi account](https://cloud.githubusercontent.com/assets/20803990/20633902/e348d442-b353-11e6-8522-74e7f8a55d3e.png)
  bide hocam bu yerde ikişer tane yazılması var önemli değil ama atayım dedim
![screenshot_2016-11-25-17-52-53-343_com android settings](https://cloud.githubusercontent.com/assets/20803990/20633919/0e90e07c-b354-11e6-93e6-74e9fb474171.png)

**Comment by aykutyenihan** [comment]
gmail ve hava durumu genel bir sorun olduğu açıklandı bütün romlar yeniden yapılıyor yakında yayınlanır ve tekrar indirip yükleriz, xiaomi.eu sitesini takip edin.

miui upload email apksını yeni romu yükleyince düzelir büyük ihtimalle ama düzelmesse benim verdiğim apk yı system/app/email içine koplayayın geçen haftaki düzgün sürümdür.
https://www.dropbox.com/s/0tvb2c43kib8isy/Email.apk?dl=0

üstteki hataların çoğu daha önceden vardı çeviriden çok rom hatası ama ikinci alan bölümü daha önce düzgündü bu hafta bozulmuş yani çeviri hatası

**Comment by raoc999** [comment]
Arkadaşlar; WLAN ve Başlatıcı (Launcher) ile ilgili sıkıntı var mı? Böyle bir şikayet geldi.

**Comment by 4fareis** [comment]
Bende bir problem yok herşey sağlam kameradan galeriye geçme dışında Redmi Note 2

**Comment by aykutyenihan** [comment]
hava durumunu düzelten yama arkadaşlar. Mail uygulamasını dün vermiştim eski apk dosyası. Gmail sorunu içinde gmaili bu hafta komple silip miui mail uygulasından maillere bakıyorum mecburen. Çok sıkıntılı bir sürüm oldu bu hafta yapacak bişey yok beta sürüm demek bu demek zaten.

https://drive.google.com/file/d/0B4rjN-1Cvj0id1U2MnBydnZCNXM/view

**Comment by oguzhan5200** [comment]
Aykut hocam selam,

konu ile alakalı değil ama bana romun apk dosyalarının oldugu dosyayı parcalayıp yenıden  toplama işini yapabilecek bi program lazım. geçen bi tane paylaşmıştın ama o sadece parcalama işini yapıyor. desteğini rica ederim. (amaç china stabil romdaki istemediğim uygulamaları kaldırmak, root ederek yap diyeceksin ama china stabil rom rootlanmıyor mi yazısında takılıp kalıyor :) ) telefon mi note pro teşekkürler.

**Comment by raoc999** [comment]
6.11.28,29 ve 6.11.30 sürümlerine ait çeviriler yapıldı ama siteye eklemedim. Gelen hatalar ve önerilere göre Çarşamba veya Perşembeye kadar düzenleme yapıp. Perşembe günleri ekleme yapacağım. İş yoğunluğundan dolayı, bazen ufak boşluklardan yükleme yapayım derken hatalar yapıyorum. İncir çuvalı misali bu kez berbat oluyor.

**Comment by raoc999** [comment]
6.12.1 güncellemeleri çevrilip eklendi. Tüm ürünler nedeyse  6.12.1 oldu. Normalde Cuma günleri yazılım çıkıyordu. Acaba değişti mi, yoksa birden bir sürü ürünün içeriği değişmezdi. Tatil filan mı veya günler değişti mi?

**Comment by kutukcu** [comment]
Selamlar, stabil sürümün çevirilerini de mi buradan yapıyoruz acaba?

**Comment by raoc999** [comment]
Bir Allahın kuluda demiyor ki sen ne yapıyorsun yarın Cuma, ben halen çarşamba günündeyim. Son güncellemede gelen İngilizce yerleri çevirdim ama Perşembe günü atarım diye bekliyorlar. Meğer bugün Cuma olmuş. Ctesi izinli, Pazar günü çalıştığımdan günleri hep tersine çevirdim. Neyse gelecek hafta eklerim, fazla birşey yok

**Comment by murat2483** [comment]
selamunaleyküm öncelikle çok tşk ederim böyle bir hizmet için mi 5s  kullanıyorum parmak izi sorunu war ilgilenirseniz sevinirim

**Comment by umit35izm** [comment]
merhaba 6.11.24 romunda "mail" uygulamasının adı "Cihazlar" olmuş... Ayrıca ayarlar menülerinde ingilizce kalan çok yer var ne yazıkki...
