### ISSUE TITLE
Sürüm 6.12.1 Problem ve İstekler

### ISSUE THREAD

**Issue by raoc999** [ingbrzy/MA-XML-8.0-TURKISH#94]
Beyler, 6.12.1'e kadar olan tüm güncellemeler çevrildi ama geçen-hafta ile bu hafta arasındakiler eklenmedi. Ayrıca Mi5 serisi ürünlerle ilgili tüm eksik satırlar kaynak dosyaya eklendi ki çok fazla satır olduğundan halen çeviriyorum. Bunları hafta içinde yüklerim. Diğer tüm modellerdeki eksik satırları bulup tek tek ekliyorum.  Mi5 serisindeki Kişisel Yardımcı uygulaması Çince idi şimdi İngilizce olarak sisteme dahil edildi, onuda çevirip ekleyeceğim. Aksilik olmazsa Kamera geçişi hariç, mümkün olan en iyi hali olacak...

**Comment by murat2483** [comment]
Selamunaleykum mi 5s kullanıyorum  parmak izi sorunu başlatıcı hatası veriyor arada  şimdilik izlenimlerin bunlar

**Comment by murat2483** [comment]
Mi 5s Birde mi hesabı sayfasına girdiğimizde altta şifre değiştir yazıları kodlama gibi duruyor

**Comment by raoc999** [comment]
@murat2483 
Murat ve diğer Mi5/Mi5 Pro kullanıcılarına;
Bu ürünlere bir iki haftadır buradan yazılım güncellemesi yapılmıyordu, çünkü bazı hatalar vardı ve devam ediyor gibi... Ayrıca bu ürünlerin dil dosyalarındaki değişiklikler gelmiyordu fakat bu hafta yazılım çıkınca eksik satırları da eklediler. Şimdi onları çevirip sisteme ekleyeceğim. Gelecek hafta çeviri ile ilgili eksiklikler giderilir. Ama ürünü kullanırken oluşan hatalar konusunda site yöneticisine yazı yazabilir, resmi sürümü kullanabilirsiniz.

**Comment by raoc999** [comment]
Aylardır dediğimiz eksik satırlar var, sonunda eklendi. Ama işin kötü tarafı en az 2000 satır geldi. Yaklaşık 1000 satırda bazı ifadelerin değişmesi dersek ortada ortalama 3000 satır var ki tek tek ayıklamak zor. Özellikle bunlar Mi5 serisi için. Bendeki Note 4 ve türevlerinde toplasan 5 satır ing. vardır. Özellikle Mi5 Plus gibi ürünlerden gelen şikayetlere bir çözüm olur. Çünkü bu ürün sahipleri sürekli mail atıyordu. Bizde çok İng. yerler var diye. Doğal olarak kaynak dosyada bu satırlar yoktu. Telefon bende olmadığından bende gerçek mi yalan mı bilmiyordum.

**Comment by aykutyenihan** [comment]
nasıl yapacağımızı göster yardım edelim hocam ayıklamaya.

**Comment by murat2483** [comment]
Hocam sağolsun cvp için ama İngilizce olmadığından multi rom kullanıyorum:)) serdeniş için belirtmesi yanlış anlaşıldı galiba problem diyince ben çeviri harici sorunları gibide anlayınca:))  yardımcı olmak istedim  kusura bakmayin

**Comment by raoc999** [comment]
@aykutyenihan 
Tamam Aykut ben sana bir dosya göndereyim. O kadar çok satır eklendi ki, 3000 diyerek az demişim. Ayarlarda dünyanın eklentisi var. gemini/xdivert.apk/res/values/strings.xml ve gemini/Telecom.apk/res/values/strings.xml dosyalarını çevirebilirsin. Bu hafta 5 serisi olanlar için bir kısmını eklerim, gerisini beklerler. Ya bir hata var yada böyle ise çok iş var. Hata var diyorum zira aynı satırlar 3-5 dosyada var. Aykut çeviri yaparsan Türkçe dili indir ve aynı satıra arat göreceksin başka yerde çevrilmiş. Artık kopyala yapıştır, nasıl istersen. Çarşamba gibi bana ulaştır, ne kadar yaparsan

**Comment by heyelan96** [comment]
Hocam bu sürümde. Galeride mi cloud eşitlemesini kapattığımız albümleride miclouda eşitledi. Örn whatsapp imagesi micloud eşitlemesini kapatmıştım fakat bu sürümü yükledikten sonra eşitleme hâlâ kapalı olmasına rağmen eşitlemiş. Redmi pro

**Comment by aykutyenihan** [comment]
nerde dediğin dosyalar hocam gemini falan bulamadım, github falan pek anladığım şeyler değil.

bide şöyle basit bir hataya denk geldim hocam.
![img_20161205_105845](https://cloud.githubusercontent.com/assets/16150035/20877645/b83a853a-bad2-11e6-9ef8-3d250204a4e2.jpg)

**Comment by raoc999** [comment]
@aykutyenihan @murat2483 

Aykut o basit hata  için: Önceden orada iki kelime vardı kısaltayım düzelir dedim, düzelmedi, sonra başka bir kelime yazdım yine o kelimenin sonunu küçük yaptı, halen ve nedense o kelimenin sonunu küçük harfli yapıyor.
Murat: Eşitleme kapalıyken nasıl yapıyor bilmiyorum ama acaba Whatsup ayarlarında da eşitle gibi birşey mi var. Normalde Mi Cloud Whatsup dosyalarını eşitlemez diye biliyorum. Fikri olan yazsın, gerekirse yetkiliye yazı yazarız.
Aykut 2: https://github.com/Acid-miuipolskapl/v8-XML-Compare adresinde dosyaları bulabilir ve indirebilirsin.

**Comment by raoc999** [comment]
Arkadaşlar Android 7.0 değişikliklerini de çevirip eklemeye başlayacağım. Yakında 5 serisiyle 7.0 verilmeye başlanacak. Şimdilik 12.1/12.3/12.5 değişikliklerini ekliyorum. Ayarları halen bitiremedim. Çok karma çorba oldu. Satır eklemek çıkarmak, yeniden düzenlemek, sıfır çevirmekten çok zormuş

**Comment by aykutyenihan** [comment]
hocam bu çeviri işi beni aştı içinden çıkamadım kusura bakma. Bi gazla yardım edelim dedik ama ben neyin ne olduğu anlasam bile sana ancak köstek olurum. Sen yaparsın aceleye gerek yok şuan bile %100 gibi çeviriyi yapmış durumdasın eksik satırlar çokta önemli değil ki yavaş yavaş onlarıda kapatırsın.

**Comment by heyelan96** [comment]
Hocam wp images örnekti mesela. Ekran görüntüleri snapchat instagram facebook fotolarını eşitlemeye kapatmıştım. Bu güncellemeyi yükledikten sonra Bi baktım depo doldu dedi i.mi.com dan cloud a eşitlenenlere baktım eşitlemeye kapattığım albümleride eşitlemiş. Sıkıntı değilde düzeltilsin diye söyliyim dedim.

**Comment by raoc999** [comment]
@heyelan96 

Olsun, iyi ki söyledin. Bu hafta gelen sorunları ve benim gördüklerimi ileteceğim ama önce şu yeni eklenen yerleri bitirmeye çalışıyorum. Çünkü bir an önce Android 7 dosyalarını eklemeye başlamak lazım.

**Comment by heyelan96** [comment]
hocam anladığım kadarıyla verdiğiniz linkteki dosyalar mı türkçeye çevrilecek tamamen yavaş yavaş.
https://github.com/Acid-miuipolskapl/v8-XML-Compare bunlar.
eğer öyleyse zaten önceki türkçe dosyalarından bakarak. fazlalık varsada tranlateden falan tam tabirini bularak çevirinize birazda olsa yardımcı olabilirim. okulda aldığım birazcık kod bilgisiyle:)

**Comment by raoc999** [comment]
Tamam @heyelan96  ben bitirdim sadece Telecom dosyası kaldı, onuda gelecek haftaya hazırlarım. Bu arada 6.12.1/2/3/4/5/6/7/8 dosyalarını ekledim ve siteye yükledim. İnş. yarın hiç aksilik olmadan ve memnun bir şekilde kullanırsınız. Resmi çeviridi yeni eklenen birkaç satır gördüm onlar daha bu yere eklenmediğinden bende eklemedim. Gelecek hafta itibari ile Android 7 eklerini ve Enginner Mode yazılımını eklemeyi düşünüyorum. Tabi zaman bulabilirsem

**Comment by eryen** [comment]
Merhaba,

Redmi pro cihazda kullandigim romda, kamera ile foto cektikten sonra, galeriye gitmesi gereken tusa basiyorum, ekran kararip tekrar kameraya geri donuyor.

Ayni romda ingilizce kullandigimda, islev yerine geliyor ve galeri uygulamasina gidiyor.

Bu arada, hata sadece native kamera uygulamasi icin degil. Lenovo snapit vb birkac uygulama da kurdum, o uygulamalarin da prewiev tusjna basina geri atiyor.

Ayni sekilde dil ayarlari ingilizceye ayarlaninca, onlarin da hatasi ortadan kalkiyor.

Son gucellemeyi cekiyorum, onunla da tekrar deneyecegim

**Comment by raoc999** [comment]
Bu hata uzun zamandır devam ediyor. Bir ara düzelttiler, sonra Galeri ve
kamera yazılımında hiçbirşey değişmemişken yeniden sorun oldu. Düzeltmek
için çevirinin boyutu fazla oldu gibi saçma birşey söylediler. Sonra bir
hayli satırın silinmesi gerekiyor diye rapor gönderdiler. Satırları sildim
değişen birşey olmadı. Daha sonra şarj %19 altına düşünce hata olmaya
başladı. Sonra bunun % işaretinin rakamdan önce olmasından kaynaklandığı
çıktı. Demek istediğim Türkçedeki bazı düzenlemeler, biçimler bu hataya
neden olabilir. Tarih, % gibi.... Bizde bekliyoruz

recep.ali.orhan.cakmak

10 Aralık 2016 21:44 tarihinde eryen <notifications@github.com> yazdı:
