### ISSUE TITLE
XML ISSUES!

### ISSUE THREAD

**Issue by ingbrzy** [ingbrzy/MA-XML-8.0-TURKISH#95]
http://translators.xiaomi.eu/XML_MIUI8-Turkish-tr.html

Fix it ASAP!

**Comment by raoc999** [comment]
Turkish Language Report (6.12.x Series)

1: There is an error in the MiuiSystemUI.apk file. The error report is Chinese. I could not find the problem. Could you please fix it?
2: Too many unnecessary lines. Could you make a report next week? I want to delete unnecessary lines in all the files. Or there is no need to stop unused lines. Files are lightweight, fewer errors.
3: That's it for now. Thank you.

**Comment by raoc999** [comment]
OK, I fixed number 1
