### ISSUE TITLE
Sürüm 6.12.8 Problemleri, Öneriler vb...

### ISSUE THREAD

**Issue by raoc999** [ingbrzy/MA-XML-8.0-TURKISH#96]
Değişiklikler
1. Kilit ekranı, Durum Çubuğu, Bildirim Çubuğu (Üçüncü taraf temaların peyzaj modu sorunları)
2. Galeri (Siyah beyaz karalamalar)
4.Hava Durumu (Ana sayfa animasyon ayarlamaları, Şehirleri seçmek için kullanıcı arayüzü geliştirmeleri)
5.Ayarlar (Kişisel hotspot'unuza bağlanabilen cihaz sayısının sınırlandırılması)
6.Güvenlik (Oyundan çıktıktan sonra güç tasarrufu özellikleri devam etmek)

Arkadaşlar problemlerinizi telefon modeli, sürüm, problem açıklaması ve alabilirseniz ekran görüntüsü ile birlikte gönderin. Donanımsal problemleri veya çok derin sorunları yetkiliye iletiriz. Çeviri kaynaklı sorunları çözmeye çalışırız. Birde sürümün Beta olduğunu unutmayın. Üstelik buradaki sürüm Developer olduğundan hedef sadece yazılımı geliştirmektir. Onun için gider yapmayın :)

**Comment by aykutyenihan** [comment]
hocam bu genel bi sorunmu yoksa dille mi ilgili? hata raporu veren baska bi uygulama daha var

**Comment by aykutyenihan** [comment]
![screenshot_2016-12-10-12-51-58-853_com android browser](https://cloud.githubusercontent.com/assets/16150035/21072582/9e046cb2-bed8-11e6-8a9d-a9545b4bb3b9.png)

**Comment by oguzhan5200** [comment]
Arkadaşlar konuyla alakasız ama mi note pro için android 7 gelir mi? bi
forumda gelecek yazılmıs ama 6.0 verilmedi 7 imkansız diye düşünüyorum. Mi
Note a veriliyorken neden pro ya verilmez anlamış değilim. diğer
üreticilerden farklı bir yol izliyorlar. diğerleri önce üst modele verir
bunlar alt modele veriyor :)

2016-12-10 12:00 GMT+02:00 aykutyenihan <notifications@github.com>:

**Comment by aykutyenihan** [comment]
o bi forumda yazanda muhtemelen benim :) şu siteye dayanarak söylüyorum ama kesin bişey yok tabiki sadece araştırıyorum bu konuyu hemen her gün. 6 atlanmış olabilir ki öylede olmalı 7 çıkmışken 6 vermek gereksiz, mi4'e de 5 lolipop atlanıp direk 6.0 marsmallow gelmişti. Ha gönül isterki her sürüm gecikmeden eksiksiz verilsin ama xiaomi sabıkalı firma android sürümü konusunda. muhtemelen 7 gelir gerisi yalan olur.

**Comment by aykutyenihan** [comment]
hocam https://github.com/Acid-miuipolskapl/v8-XML-Compare/tree/master/libra başlığında biraz baktımda neden hemen her strings.xml dosyasında benim adım geçiyor? bunları ben göndermediğime göre nasıl oluyor bu iş?

**Comment by raoc999** [comment]
Beyler bir kaç İngilizce yer kalmış, kaynak dosyada yoklar bulup ekleyeceğim inş.

**Comment by aykutyenihan** [comment]
valla dosyalara bakayım dedim hepsinde ismim geçiyor, bunlar el değmemiş ingbrzy tarafından eklenen dosyalar değilmi? telefonmu gönderiyor ne yapıyor diyeceğimde benimkinimi gönderiyor meret o kadar kullanıcı içinden :)

**Comment by rasimayyildiz** [comment]
Merhaba. 6.12.8 mi 5s . anaekran üzerine basılı tuttuğumda sistem başlatıcı durdu diyor. İngilizce sevince sorun ortadan kalkıyor.
[url=http://hizliresim.com/6r51pN][img]http://i.hizliresim.com/6r51pN.png[/img][/url]

**Comment by rasimayyildiz** [comment]
Merhaba. 6.12.8 mi 5s . anaekran üzerine basılı tuttuğumda sistem başlatıcı durdu diyor. İngilizce secince sorun ortadan kalkıyor. Birde şimdi dikkat ettim hatanın arkasındaki iconlar ekran görüntüsünde çıkmadı o niye :)


![screenshot_2016-12-11-07-50-49-265_com miui home](https://cloud.githubusercontent.com/assets/24502994/21078503/8be155d4-bf7a-11e6-87b5-b4b295c3b98f.png)

**Comment by rasimayyildiz** [comment]
Hocam benim telefona henüz gelmedi 7.0 . ama İngilizce yapınca sorunu yok anlamadım bende. Xiaomi eu forumunda da aynı sorunları yasayan var

**Comment by murat2483** [comment]
Mi5 skullaniyorum sistem başlatıcı hatası ve parmak izi sorunu suanlik izlenimim

**Comment by murat2483** [comment]
Forma resim nasıl ekleniyor telefondan

**Comment by raoc999** [comment]
Bu arada Battlefleet Gothic Armada oynayan varsa çevirisini yapıyorum. 6000 kadar satır var. Çok profesyonel olmayacak.... Birkaç ekran resmi gönderirim. İsteyene gönderirim. Güzel bir strateji oyunu. 
Space Marine ve Tau Empire DLC sürümlerini de dahil edeceğim.

**Comment by aykutyenihan** [comment]
bu haftaki sürümde fiyasko oldu benim için geri döndüm geçen haftaya.

**Comment by alionur54** [comment]
Mi 5s 4/128 de 6.12.1 ve 6.12.8 sürümlerini kullandım. Türkçe dilde ikisinde de ana ekran ayarlarını değiştirmek istediğimde başlatıcı çöküyor. dili ingilizce yaptığımda ise sorun yok. parmak izi hatasından bahsediyorlar ama ben kullanmadığım için bilmiyorum. metok un çökmesini de iki kez gördüm. sanırım görüntülü arama uygulamasıymış.
