### ISSUE TITLE
7.1.5 Çeviri Hataları & Öneriler

### ISSUE THREAD

**Issue by CenkayKESER** [ingbrzy/MA-XML-8.0-TURKISH#99]
Merhaba,

Mi5s Plus ile tekrardan aranızdayım, çeviride bazı yerler dikkatimi çekti, umarım düzeltebiliriz.

-Ayarlarda iNet paylaşımı şeklinde bir ibare var bunu text boyutu sığmadığı için mi yaptınız yoksa özel bir sebebi mi var? Bence hoş olmamış.

-Ayarlarda yer alan nerdeyse her metindeki her kelime büyük harf ile başlıyor bu benim hiç hoşuma gitmiyor, sırf sebepten global rom kullanıyorum. Sorun olmazsa ben bu metinlerin hepsini elimden geldiğince düzenleyebilirim.

 Xiaomi.EU romları daha temiz bunları kullanmak daha mantıklı geliyor.

Cevaplar:
Selamlar Cenkay;
iNet paylaşımını dediğin gibi normal çevirince iki satıra taşıyordu, kısaltmak için öyle yaptım.
İkinci soruna gelince bende sırf metinleri simetrik tazda olsun, başlıklar büyük harfle başlasın açıklamlar normal olsun diye, göze güzel gözüksun diye yaptım. Zevkler farklı... :)

**Comment by 4fareis** [comment]
![screenshot_2017-01-07-12-00-57-089_com miui cloudservice](https://cloud.githubusercontent.com/assets/18270175/21740659/f34f38d6-d4c8-11e6-8840-c692c0c981dc.png)
![screenshot_2017-01-07-12-00-33-345_com miui cloudservice](https://cloud.githubusercontent.com/assets/18270175/21740660/fc1f2bc4-d4c8-11e6-87cc-012668fa6cfb.png)
![img_20170107_115959](https://cloud.githubusercontent.com/assets/18270175/21740661/040f7186-d4c9-11e6-96e2-512782c270b1.jpg)

Mi cloud da problem var kişiler açık yedekleme yapmıyor fotoğraflar kapalı yedekleme yapıyor birkaç sürümdür var

**Comment by aykutyenihan** [comment]
''çevirmenin'' bu durumda ne yapmasını bekliyorsunuz??

**Comment by 4fareis** [comment]
Çevirmenden bişey beklemiyoruz durumu gerekli yerlere iletir diye yazdım Çevirmenden memnunum global sürümde yada developer sürümde de var mı merak ettim pil %19 sorununu neden yazdık buraya ve düzeldi

**Comment by heyelan96** [comment]
Mi cloudda yedekleme kapalı olanları yapıp açık olanları yapmaması sıkıcı bi durum. Çevirmenden kaynaklanmıyor bence. Çünkü şimdiye düzelirdi.

**Comment by raoc999** [comment]
Bazı modellerde yine İngilizce kısımlar varmış, model model kontrol edeceğim. Keşke tüm modeldeki dosyalar birleşik olsa. Bir mail dosyasını onca modelle karşılaştırmak çok zor... Şimdilik ağırdan alıyorum. Bir oyunun çevirisini bitirmeye çalışıyorum...

**Comment by cenedi** [comment]
Merhaba. Mi5s'de Bildirimler ışığı açık olmasına rağmen şarj %100 olduğunda hiç bir ışık yanmıyor,Mevcut yeşil olan ışık sönüyor. Ayrıca  %10'nun altına düşmesine rağmen kırmızı veya herhangi bir bildirim ışığı yine yanmıyor.

**Comment by 4fareis** [comment]
Bütün makinalarda aynı sorun var sadece mi5s değil @cenedi

**Comment by cenedi** [comment]
4fareis@ diğer modelleri bilemiyorum hocam. Ayrıca bugün farkettim. Cihaz ne olursa olsun 4g'ye geçmiyor. Şehir merkezinde bir çok yere gitttim.  Aynı operatördeki bir çok kişide 4g yazısı vardı. Benim cihaz sadece 3g'deydi. Global stabil'de bu sroun yoktu. Yani sorunun 20. bant'la alakası yok. Turkcell,mi5s,Konya

**Comment by CenkayKESER** [comment]
Mi5s Plusta da 7.1.5 sürümü ile 4G sorunu mevcut. Bu genel bir sürüm. Muhtemelen Mi5s ile Mi5s Plus aynı platformu kullandığı için 2 cihazda 4G sorunu olabilir. Çeviri kaynaklı bir sorun olduğunu sanmam.

**Comment by raoc999** [comment]
@CenkayKESER 

Cenkay şimdi sanabirşey diyeyim, aynı sorunu olanlarda dikkat etsin. Yurtdışından telefon alıp buna IMEI atan arkadaşlar! IMEI attığınız telefon mesela 3310 ise  telefon şebeke sağlayıcıda özellikle AVEA ise 3310'un içeriğini alabilir. Daha öncede bu konuda çok şikayet geldi, hatta benim eski telefonda oldu AVEA yı aradım. Adam abi senin telefon XXX dedi. Yok dedim. Bende telefon XXX gözüküyor dedi, kibarca, jeton düştü ben XXX telefonun IMEI'sini yazdım. Doğal olarak o telefonun özellikleri kaydolmuş. Nasıl 4,5G yaparız dedim. Telefonumunu resmi olarak kaydetmem gerekiyor. Bizde telefonu değiştirdik. Şimdi hikaye gibi gelebilir. Ama eski telefonla ilgili Numaranın online içeriğine bakınca XXX telefon gözüküyor, online olarak 4,5G geçiş yapmaya çalışınca da telefonunuz desteklemiyor diyor. Oysa telefon fazlasını destekliyor.... Hayır çeviriden kaynaklanıyor diyen varsa? Çözüm getirsin. İng. dosya ile Türkçe dosyadaki satırlar aynı.

**Comment by cenedi** [comment]
raoc999 çeviriden kaynaklı değil hocam. Öyle olsaydı diğer sürümlerde de aynısı olurdu. Bu sürümle alakalı bir sorun var herhalde. Bu arada doğru imei atılı. Ama bu 4g almamaıza engel olmuyordu .

**Comment by kutlusancak** [comment]
@raoc999 iki adet mi5s de bizde mevcut 4g problemi var bi önceki roma dönüp sorunu geçiştirdik. Hücresel ağlar menüsünde otomatik şebeke seçiminde 4g ye gecmiyor diye manuel olarak seçmek istediğim zaman 4g şebeke buluyor, seçince altta bildirim olarak ağa kaydedildi yazmasına rağmen 4g gelmiyor. Bu problem çeviri veya imei kaynaklı değil daha çok rom 4g ye şebeke geçişi yapmiyor gibi.

**Comment by raoc999** [comment]
Arkadaşlar bu 4G geçişleriyle ilgili yöneticiye bildirim yapacağım, başka problem varsa, galeri ve kamera hariç onları da yazalım.

**Comment by aykutyenihan** [comment]
4g sorunu nedir bahsettiğiniz tam anlamadım ama şu videoyu bi izleyin belki çözüm olur.
https://www.youtube.com/watch?v=G2XVx6J7ArM

**Comment by 4fareis** [comment]
@raoc999 Orhan yukarıda belirttiğim sorun var mi cloud la ilgili eşitleme yapmaz oldu kişiler, fotoğraflar kapalı onuda kendi kendine yedekliyor. Tarayıcıdan i.mi.com a girdim öyle sildim fotoğrafları bakalım gene yedekleme yapacak mı?
